### ISSUE TITLE
Loss functions

### ISSUE THREAD

**Issue by ajohannsdottir** [lyst/lightfm#100]
Hi Maciej,
I haven't used C before, I am trying to understand how to read the _lightfm_fast_openmap.c file, since I am interested to see how you train the models via WARP, BPR and logistic. I am interested to adapt the algorithms for mutliple domains. 

I was hoping to see clearly f.ex following algorithm:
![screen shot 2016-07-09 at 23 14 01](https://cloud.githubusercontent.com/assets/16305550/16710559/e6dc3cb6-462a-11e6-803d-5b618f8884de.png)

**Comment by maciejkula** [comment]
You can have a look here: https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template#L756

LightFM uses a dialect of Python which compiles to C --- the actual code lives in the file I linked to.

**Comment by ajohannsdottir** [comment]
Thank you Maciej, exactly what I was looking for. 
I only looked at the file itself,and as you know it isn't readable. 

Best regards,
Agnes
