### ISSUE TITLE
Docker Build Fails to Install SciPy

### ISSUE THREAD

**Issue by seanlaw** [lyst/lightfm#101]
docker-compose build lightfm

Produces this on my Mac OS X:

    File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 966, in add_subpackage caller_level = 2)
    File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 935, in get_subpackage caller_level = caller_level + 1)
    File "/usr/lib/python2.7/dist-packages/numpy/distutils/misc_util.py", line 872, in _get_configuration_from_setup_py
    config = setup_module.configuration(*args)
    File "scipy/linalg/setup.py", line 20, in configuration
    raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
    Can't roll back scipy; was not uninstalled
    Cleaning up...
    Command /usr/bin/python -c "import setuptools, tokenize;__file__='/tmp/pip-build-XnyZzK/scipy/setup.py';exec(compile(getattr(tokenize, 'open', open)(__file__).read().replace('\r\n', '\n'), __file__, 'exec'))" install --record /tmp/pip-cBi7ka-record/install-record.txt --single-version-externally-managed --compile failed with error code 1 in /tmp/pip-build-XnyZzK/scipy
    Storing debug log for failure in /root/.pip/pip.log
    ERROR: Service 'lightfm' failed to build: The command '/bin/sh -c pip install .' returned a non-zero code: 1

I'm new to Docker but see that it is SciPy complaining about missing lapack/blas

**Comment by maciejkula** [comment]
Did you use the Dockerfile included in the lightfm repo? Your image needs
to have blas/lapack installed.

**Comment by seanlaw** [comment]
Yeah, I just used the plain default image from Docker and then built lightfm using the provided Dockerfile. I added this line to the Dockerfile:

    RUN apt-get install -y libopenblas-dev gfortran

And the install succeeded. Should this be added to the repo? Otherwise, the Docs won't reflect something that runs properly.

**Comment by maciejkula** [comment]
OK, do you think you could make a PR with the fix?
