### ISSUE TITLE
Docker Build Fails Tests

### ISSUE THREAD

**Issue by seanlaw** [lyst/lightfm#103]
Following the [issue #101](https://github.com/lyst/lightfm/issues/101),  I tried running the test as per the Docs:

    docker-compose run lightfm py.test -x tests/

And then I ran it from the Docker shell (see below). In both cases, the test fails to find lightfm_fast

    root@002ca3eaa9c1:/home/lightfm# py.test -x tests/
    ================================================== test session starts ==================================================
    platform linux2 -- Python 2.7.9, pytest-2.9.2, py-1.4.31, pluggy-0.3.1
    rootdir: /home/lightfm, inifile: 
    collecting 0 items / 1 errors
    ======================================================== ERRORS =========================================================
    __________________________________________ ERROR collecting tests/test_api.py ___________________________________________
    tests/test_api.py:7: in <module>
    from lightfm import LightFM
    lightfm/__init__.py:1: in <module>
    from .lightfm import LightFM
    lightfm/lightfm.py:9: in <module>
    from .lightfm_fast import (CSRMatrix, FastLightFM,
    E   ImportError: No module named lightfm_fast
    !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: stopping after 1 failures !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
    ================================================ 1 error in 0.30 seconds ================================================

**Comment by maciejkula** [comment]
Have you built the extension? Can you try running it from a different
directory?

**Comment by seanlaw** [comment]
No, I had not built the extension and noticed that Cython is not in the Dockerfile as well.

Then, I did the following:

    pip uninstall lightfm
    cd /home/lightfm
    apt-get install -y cython
    python setup.py cythonize
    ls lightfm

This shows that the extension is present (the lightfm_fast.pyx file). And then I install lightfm and ran the test again:

    pip install .
    py.test -x tests/

This results in the same error as my original post.

**Comment by maciejkula** [comment]
Off the top of my head:

1. Cython does not need to be in the container.
2. You do not need to run cythonize.
3. When the container is built lightfm is already installed.
4. When you run tests they fail because pytest picks up the source code
from the directory you are running the tests in instead of the installed
package. You must move the tests somewhere else or run them or run pip
install -e .

**Comment by maciejkula** [comment]
I just verified that after adding the libblas fixes lightfm is correctly
installed in the docker container.

You can check this by deleting the lightfm folder from the mounted
repository folder. This will prevent python from picking up the local files
(which do not have the extension built) in the import process, and tests
will complete.
