### ISSUE TITLE
predict_rank is slow for all items of a single user

### ISSUE THREAD

**Issue by DeoLeung** [lyst/lightfm#110]
I have a model of (30k, 1m) user/item
when I use predict_rank to predict all the ranks of a single user, it gets slow:

``` python
interactions = csr_matrix(
          ([1] * item_size, ([user_id] * item_size, item_ids)),
          shape=(user_size, item_size),
          dtype=np.float32)
# this takes very long
model.predict_rank(interactions)
# very fast
model.predict(user_id, item_ids)
```

isn't the ranks are just the recommended scores' order?
I guess predict_rank do predict for every interaction？

thanks,

**Comment by andyluther** [comment]
i believe `predict_rank` predicts the rank of every item for each user in interactions

**Comment by maciejkula** [comment]
This method is to be used when you're only evaluating a couple of interactions for every user, as is most common in evaluating models. It is quadratic in the number of nonzero interactions per user, so if you want to evaluate more items than that I suggest you use `predict` instead.

I updated the docstring to reflect this in https://github.com/lyst/lightfm/pull/111

**Comment by adsk2050** [comment]
> 
> 
> This method is to be used when you're only evaluating a couple of interactions for every user, as is most common in evaluating models. It is quadratic in the number of nonzero interactions per user, so if you want to evaluate more items than that I suggest you use `predict` instead.
> 
> I updated the docstring to reflect this in #111

In that case shouldn't the precision_at_k code be made to run on predict instead of predict_rank/predict_ranks? I am asking because precision_at_k is also very slow.

**Comment by tinawenzel** [comment]
> > This method is to be used when you're only evaluating a couple of interactions for every user, as is most common in evaluating models. It is quadratic in the number of nonzero interactions per user, so if you want to evaluate more items than that I suggest you use `predict` instead.
> > I updated the docstring to reflect this in #111
> 
> In that case shouldn't the precision_at_k code be made to run on predict instead of predict_rank/predict_ranks? I am asking because precision_at_k is also very slow.

@adsk2050 I agree. I tried to replicate prec@k using predict, but using predict results in a lot smaller prec@k scores than predict_rank.
