### ISSUE TITLE
Value ranges for Predict()

### ISSUE THREAD

**Issue by swanandj7** [lyst/lightfm#121]
_predict(user_ids, item_ids, item_features=None, user_features=None, num_threads=1)_ 
is giving me some prediction value. I am trying to set a range for the prediction ( ex. 0 to 1)
I am not able to set that range anywhere.

**Comment by DeoLeung** [comment]
AFAIN
you can use a single user_id, it will be repeated to match the item_ids, say, user 1, item 0, 1, 2
```python
predict(1, np.array([0, 1, 2]))
```

if you want to a range of user_ids, you need to custruct all user-item pairs, say, user 0, 1, item 0, 1, 2
```python
predict(np.repeat([0, 1], 3), np.tile([0, 1, 2], 2))
```

**Comment by maciejkula** [comment]
The values returned by `predict` do not have a defined range. If you'd like for them to be bounded by 0 and 1 I would suggest post-processing them, for example via the sigmoid function.

**Comment by swanandj7** [comment]
Sigmoid function was really helpful. Thanks!
