### ISSUE TITLE
How to incorporate `user_features` in the movielens example?

### ISSUE THREAD

**Issue by dofine** [lyst/lightfm#131]
Thank you for maintaining this project ! 

I'm just learning about recommendation system. After reading the example in the docs, I didn't find where to add `user_features` in the model?

Am I missing anything? e.g. for movielens dataset, I'd like to add occupation and sex as user_feature.
Forgive me for being a newbie :)

**Comment by dofine** [comment]
https://github.com/lyst/lightfm/blob/master/tests/test_movielens.py#L437

Find something in the tests :)

**Comment by maciejkula** [comment]
I'm afraid the Movielens dataset does not incorporate user features.

You can use item features, however: http://lyst.github.io/lightfm/docs/datasets.html#lightfm.datasets.movielens.fetch_movielens

**Comment by dofine** [comment]
@maciejkula What if I'd modify the code and add user features? Is that possible?

**Comment by maciejkula** [comment]
I'd be open to adding this additional data to the helper functions if it's there in the original data. Please submit a PR and we can have a look.
