### ISSUE TITLE
BPR and Logistic seem to be broken

### ISSUE THREAD

**Issue by TimonVS** [lyst/lightfm#135]
It seems that BPR and Logistic loss functions are broken (at least on Windows), or maybe I'm doing something terribly wrong.
It seems that BPR and Logistic always return the same predictions for every user (not exactly the same scores, but if you sort them, you get the same ranked list).

## Example: 

I'm using one of the MovieLens notebooks for this example (https://github.com/lyst/lightfm/blob/master/examples/movielens/warp_loss.ipynb).

<img width="824" alt="capture" src="https://cloud.githubusercontent.com/assets/876666/21344436/0ec17d94-c69c-11e6-84fc-d33483e480a9.PNG">

I also tested this with my own datasets, and got the same results.

**Comment by TimonVS** [comment]
Same issue on macOS with OpenMP enabled: ![https://i.imgur.com/EOBlEYh.png](https://i.imgur.com/EOBlEYh.png)

**Comment by maciejkula** [comment]
It's possible that the logistic and BPR losses rely more on item popularity (encoded in item biases) than WARP, and so the head and the tail of the list will have a large overlap between users. Can you check if the  recommendations start chaning beyond the first 10 or 20>

**Comment by TimonVS** [comment]
The issue persists after 25 recommendations: ![https://i.imgur.com/nvZnAqM.png](https://i.imgur.com/nvZnAqM.png)

**Comment by maciejkula** [comment]
I confirm there is an issue with the BPR loss. I will be pushing a fix this week and will keep you posted.

In the meantime, please use the WARP loss.

**Comment by TimonVS** [comment]
Thanks for the fix @maciejkula! When can I expect a new release on Pypi? :)

**Comment by maciejkula** [comment]
Out now, v1.11.
