### ISSUE TITLE
installation failed on linux mint

### ISSUE THREAD

**Issue by Sandy4321** [lyst/lightfm#138]
I use pip install lightfm
error is 
running build_ext

    building 'lightfm._lightfm_fast_openmp' extension

    creating build/temp.linux-x86_64-2.7

    creating build/temp.linux-x86_64-2.7/lightfm

    x86_64-linux-gnu-gcc -pthread -DNDEBUG -g -fwrapv -O2 -Wall -Wstrict-prototypes -fno-strict-aliasing -Wdate-time -D_FORTIFY_SOURCE=2 -g -fstack-protector-strong -Wformat -Werror=format-security -fPIC -I/usr/include/python2.7 -c lightfm/_lightfm_fast_openmp.c -o build/temp.linux-x86_64-2.7/lightfm/_lightfm_fast_openmp.o -ffast-math -march=native -fopenmp

    lightfm/_lightfm_fast_openmp.c:15:20: fatal error: Python.h: No such file or directory

    compilation terminated.

    error: command 'x86_64-linux-gnu-gcc' failed with exit status 1

**Comment by maciejkula** [comment]
You need to install Python development headers: `sudo apt-get install python-dev`

**Comment by sushant1104** [comment]
getting the error even after library is installed
