### ISSUE TITLE
fails to install conda install lightfm

### ISSUE THREAD

**Issue by Sandy4321** [lyst/lightfm#139]
d:\Recommender systems\code>conda install lightfm
Fetching package metadata .........
Solving package specifications: .
PackageNotFoundError: Package not found: '' Package missing in current win-64 ch
annels:
  - lightfm

You can search for packages on anaconda.org with

    anaconda search -t conda lightfm

**Comment by maciejkula** [comment]
Thank you for all the issues. Have you tried `pip install lightfm` within your Conda virtualenv?

**Comment by danlou** [comment]
I believe you need to specify the channel. I got it installed with:

`conda` install --channel https://conda.anaconda.org/mlgill lightfm

**Comment by maciejkula** [comment]
I'll go ahead and submit official packages to the conda repositories in the next couple of days.

**Comment by jariel17** [comment]
@maciejkula I tried `pip install lightfm`  in a conda virtualenv but still fails the installation with the message:
> Failed building wheel for lightfm
>error: option --all not recognized

**Comment by maciejkula** [comment]
Have you got an up-to-date version of `pip`?

**Comment by MrPhilosopher** [comment]
I got it installed by running `pip install lightfm` using cmd.

**Comment by Reddman5** [comment]
hey @jariel17  I have the exact same issue, did you manage to find a solution?

**Comment by rakshithvasudev** [comment]
Hey @maciejkula, this is a great package. I wish I could get it installed via conda. Unfortunately, it doesn't even install via pip. Is it possible for you to submit files to anaconda? Or can somebody please help me have a workaround to install this package?

**Comment by maciejkula** [comment]
I will look at building and distributing binary wheels for LightFM. In the meantime, could you try installing the Microsoft Visual C++ compiler?

**Comment by rakshithvasudev** [comment]
I tried after installing Microsoft Visual C++ compiler now, unfortunately, no luck! 
I had trouble installing Scipy via pip. That's why I switched to Miniconda. Now looks like that's biting me back.  Here is what it says: 

```
Collecting lightfm
Requirement already satisfied: requests in c:\users\rakshith\miniconda3\lib\site-packages (from lightfm)
Collecting scipy>=0.17.0 (from lightfm)
  Using cached scipy-0.19.0.zip
Requirement already satisfied: numpy in c:\users\rakshith\miniconda3\lib\site-packages (from lightfm)
Building wheels for collected packages: scipy
  Running setup.py bdist_wheel for scipy ... error
  Complete output from command C:\Users\Rakshith\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Rakshith\\AppData\\Local\\Temp\\pip-build-f1o9gyqz\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d C:\Users\Rakshith\AppData\Local\Temp\tmpo33j1792pip-wheel- --python-tag cp36:
  lapack_opt_info:
  lapack_mkl_info:
    libraries mkl_core_dll,mkl_intel_lp64_dll,mkl_intel_thread_dll not found in ['C:/Users/Rakshith/Miniconda3\\Library\\lib']
    NOT AVAILABLE

  openblas_lapack_info:
    libraries openblas not found in ['C:\\Users\\Rakshith\\Miniconda3\\lib', 'C:\\', 'C:\\Users\\Rakshith\\Miniconda3\\libs']
    NOT AVAILABLE

  atlas_3_10_threads_info:
  Setting PTATLAS=ATLAS
    libraries tatlas,tatlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries tatlas,tatlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries tatlas,tatlas not found in C:\Users\Rakshith\Miniconda3\libs
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
    NOT AVAILABLE

  atlas_3_10_info:
    libraries satlas,satlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries satlas,satlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries satlas,satlas not found in C:\Users\Rakshith\Miniconda3\libs
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
  <class 'numpy.distutils.system_info.atlas_3_10_info'>
    NOT AVAILABLE

  atlas_threads_info:
  Setting PTATLAS=ATLAS
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries ptf77blas,ptcblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries ptf77blas,ptcblas,atlas not found in C:\Users\Rakshith\Miniconda3\libs
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
  <class 'numpy.distutils.system_info.atlas_threads_info'>
    NOT AVAILABLE

  atlas_info:
    libraries f77blas,cblas,atlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
    libraries f77blas,cblas,atlas not found in C:\
    libraries lapack_atlas not found in C:\
    libraries f77blas,cblas,atlas not found in C:\Users\Rakshith\Miniconda3\libs
    libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
  <class 'numpy.distutils.system_info.atlas_info'>
    NOT AVAILABLE

  C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Atlas (http://math-atlas.sourceforge.net/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [atlas]) or by setting
      the ATLAS environment variable.
    self.calc_info()
  lapack_info:
    libraries lapack not found in ['C:\\Users\\Rakshith\\Miniconda3\\lib', 'C:\\', 'C:\\Users\\Rakshith\\Miniconda3\\libs']

    NOT AVAILABLE

  C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) libraries not found.
      Directories to search for the libraries can be specified in the
      numpy/distutils/site.cfg file (section [lapack]) or by setting
      the LAPACK environment variable.
    self.calc_info()
  lapack_src_info:
    NOT AVAILABLE

  C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
      Lapack (http://www.netlib.org/lapack/) sources not found.
      Directories to search for the sources can be specified in the
      numpy/distutils/site.cfg file (section [lapack_src]) or by setting
      the LAPACK_SRC environment variable.
    self.calc_info()
    NOT AVAILABLE

  Running from scipy source directory.
  non-existing path in 'scipy\\integrate': 'quadpack.h'
  Traceback (most recent call last):
    File "<string>", line 1, in <module>
    File "C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\setup.py", line 416, in <module>
      setup_package()
    File "C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\setup.py", line 412, in setup_package
      setup(**metadata)
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\core.py", line 132, in setup
      config = configuration()
    File "C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\setup.py", line 336, in configuration
      config.add_subpackage('scipy')
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
      caller_level = 2)
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\setup.py", line 15, in configuration
      config.add_subpackage('linalg')
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
      caller_level = 2)
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
      caller_level = caller_level + 1)
    File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
      config = setup_module.configuration(*args)
    File "scipy\linalg\setup.py", line 20, in configuration
      raise NotFoundError('no lapack/blas resources found')
  numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

  ----------------------------------------
  Failed building wheel for scipy
  Running setup.py clean for scipy
  Complete output from command C:\Users\Rakshith\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Rakshith\\AppData\\Local\\Temp\\pip-build-f1o9gyqz\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" clean --all:

  `setup.py clean` is not supported, use one of the following instead:

    - `git clean -xdf` (cleans all files)
    - `git clean -Xdf` (cleans all versioned files, doesn't touch
                        files that aren't checked into the git repo)

  Add `--force` to your command to use it anyway if you must (unsupported).


  ----------------------------------------
  Failed cleaning build dir for scipy
Failed to build scipy
Installing collected packages: scipy, lightfm
  Running setup.py install for scipy ... error
    Complete output from command C:\Users\Rakshith\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Rakshith\\AppData\\Local\\Temp\\pip-build-f1o9gyqz\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Rakshith\AppData\Local\Temp\pip-q1mppjh0-record\install-record.txt --single-version-externally-managed --compile:

    Note: if you need reliable uninstall behavior, then install
    with pip instead of using `setup.py install`:

      - `pip install .`       (from a git repo or downloaded source
                               release)
      - `pip install scipy`   (last SciPy release on PyPI)


    lapack_opt_info:
    lapack_mkl_info:
      libraries mkl_core_dll,mkl_intel_lp64_dll,mkl_intel_thread_dll not found in ['C:/Users/Rakshith/Miniconda3\\Library\\lib']
      NOT AVAILABLE

    openblas_lapack_info:
      libraries openblas not found in ['C:\\Users\\Rakshith\\Miniconda3\\lib', 'C:\\', 'C:\\Users\\Rakshith\\Miniconda3\\libs']
      NOT AVAILABLE

    atlas_3_10_threads_info:
    Setting PTATLAS=ATLAS
      libraries tatlas,tatlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries tatlas,tatlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries tatlas,tatlas not found in C:\Users\Rakshith\Miniconda3\libs
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_threads_info'>
      NOT AVAILABLE

    atlas_3_10_info:
      libraries satlas,satlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries satlas,satlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries satlas,satlas not found in C:\Users\Rakshith\Miniconda3\libs
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
    <class 'numpy.distutils.system_info.atlas_3_10_info'>
      NOT AVAILABLE

    atlas_threads_info:
    Setting PTATLAS=ATLAS
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries ptf77blas,ptcblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries ptf77blas,ptcblas,atlas not found in C:\Users\Rakshith\Miniconda3\libs
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
    <class 'numpy.distutils.system_info.atlas_threads_info'>
      NOT AVAILABLE

    atlas_info:
      libraries f77blas,cblas,atlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\lib
      libraries f77blas,cblas,atlas not found in C:\
      libraries lapack_atlas not found in C:\
      libraries f77blas,cblas,atlas not found in C:\Users\Rakshith\Miniconda3\libs
      libraries lapack_atlas not found in C:\Users\Rakshith\Miniconda3\libs
    <class 'numpy.distutils.system_info.atlas_info'>
      NOT AVAILABLE

    C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Atlas (http://math-atlas.sourceforge.net/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [atlas]) or by setting
        the ATLAS environment variable.
      self.calc_info()
    lapack_info:
      libraries lapack not found in ['C:\\Users\\Rakshith\\Miniconda3\\lib', 'C:\\', 'C:\\Users\\Rakshith\\Miniconda3\\libs']
      NOT AVAILABLE

    C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) libraries not found.
        Directories to search for the libraries can be specified in the
        numpy/distutils/site.cfg file (section [lapack]) or by setting
        the LAPACK environment variable.
      self.calc_info()
    lapack_src_info:
      NOT AVAILABLE

    C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\system_info.py:572: UserWarning:
        Lapack (http://www.netlib.org/lapack/) sources not found.
        Directories to search for the sources can be specified in the
        numpy/distutils/site.cfg file (section [lapack_src]) or by setting
        the LAPACK_SRC environment variable.
      self.calc_info()
      NOT AVAILABLE

    Running from scipy source directory.
    non-existing path in 'scipy\\integrate': 'quadpack.h'
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\setup.py", line 416, in <module>
        setup_package()
      File "C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\setup.py", line 412, in setup_package
        setup(**metadata)
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\core.py", line 132, in setup
        config = configuration()
      File "C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\setup.py", line 336, in configuration
        config.add_subpackage('scipy')
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\setup.py", line 15, in configuration
        config.add_subpackage('linalg')
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 1001, in add_subpackage
        caller_level = 2)
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 970, in get_subpackage
        caller_level = caller_level + 1)
      File "C:\Users\Rakshith\Miniconda3\lib\site-packages\numpy\distutils\misc_util.py", line 907, in _get_configuration_from_setup_py
        config = setup_module.configuration(*args)
      File "scipy\linalg\setup.py", line 20, in configuration
        raise NotFoundError('no lapack/blas resources found')
    numpy.distutils.system_info.NotFoundError: no lapack/blas resources found

    ----------------------------------------
Command "C:\Users\Rakshith\Miniconda3\python.exe -u -c "import setuptools, tokenize;__file__='C:\\Users\\Rakshith\\AppData\\Local\\Temp\\pip-build-f1o9gyqz\\scipy\\setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record C:\Users\Rakshith\AppData\Local\Temp\pip-q1mppjh0-record\install-record.txt --single-version-externally-managed --compile" failed with error code 1 in C:\Users\Rakshith\AppData\Local\Temp\pip-build-f1o9gyqz\scipy\


```

Thanks for your response.

**Comment by maciejkula** [comment]
It looks like there is something wrong with your miniconda installation. Try installing scipy from conda?

**Comment by rakshithvasudev** [comment]
It has already been installed. Conda did all the pre req installation when I wanted to install Sklearn.

**Comment by maciejkula** [comment]
Are you sure? It doesn't look like you have any linear algebra libraries
which makes me doubt you even have numpy?

On 16 Jun 2017 8:00 pm, "Rakshith Vasudev" <notifications@github.com> wrote:

It has already been installed. Conda did all the pre req installation when
I wanted to install Sklearn.

—
You are receiving this because you were mentioned.

Reply to this email directly, view it on GitHub
<https://github.com/lyst/lightfm/issues/139#issuecomment-309108480>, or mute
the thread

**Comment by maciejkula** [comment]
Correction: you seem to have numpy but without blasting/lack/mkl, which is
unusual. Try conda install scipy.

**Comment by maciejkula** [comment]
You can also try downloading the binary wheel from [here](https://ci.appveyor.com/api/buildjobs/uj88ko5l53rmqdkt/artifacts/dist%2Flightfm-1.13-cp36-cp36m-win_amd64.whl) (assuming you use Python 3.6), and installing it by running `pip install lightfm-1.13-cp36-cp36m-win_amd64.whl`.

**Comment by rakshithvasudev** [comment]
I uninstalled miniconda and installed anaconda. It works with pip install pip install lightfm now. I've finally installed lightfm. Thanks for your replies @maciejkula. Appreciate your help.

**Comment by Mohammed-Maamari** [comment]
error: command 'cl.exe' failed: No such file or directory

**Comment by maciejkula** [comment]
Hey @Mohammed-Maamari, have you [Googled it](https://www.google.com/search?client=ubuntu&channel=fs&q=cl.exe+conda&ie=utf-8&oe=utf-8)? Do those solutions not work for you?

**Comment by Mohammed-Maamari** [comment]
@maciejkula

**Comment by arshanabbas97** [comment]
Hey, I am trying to install lighfm in pycharm and facing the same error. I read the comments, @rakshithvasudev uninstalled miniconda and later on installed anaconda. I am confused, what should I do in this case! Here is the error: 
`>pip3 install lightfm 
Collecting lightfm
  Using cached lightfm-1.16.tar.gz (310 kB)
  Preparing metadata (setup.py) ... done
Requirement already satisfied: numpy in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from lightfm) (1.21.5)  
Requirement already satisfied: scipy>=0.17.0 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from lightfm) (1
.8.1)
Requirement already satisfied: requests in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from lightfm) (2.27.1
)
Requirement already satisfied: scikit-learn in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from lightfm) (1.
1.1)
Requirement already satisfied: urllib3<1.27,>=1.21.1 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from req
uests->lightfm) (1.26.9)
Requirement already satisfied: charset-normalizer~=2.0.0 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from
 requests->lightfm) (2.0.12)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from reques
ts->lightfm) (2022.5.18)
Requirement already satisfied: idna<4,>=2.5 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from requests->li
ghtfm) (3.3)
Requirement already satisfied: joblib>=1.0.0 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from scikit-lear
n->lightfm) (1.1.0)
Requirement already satisfied: threadpoolctl>=2.0.0 in c:\users\arsha\appdata\local\packages\pythonsoftwarefoundation.python.3.8_qbz5n2kfra8p0\localcache\local-packages\python38\site-packages (from scik
it-learn->lightfm) (3.1.0)
Building wheels for collected packages: lightfm
  Building wheel for lightfm (setup.py) ... error
  error: subprocess-exited-with-error

  × python setup.py bdist_wheel did not run successfully.
  │ exit code: 1
  ╰─> [25 lines of output]
      Compiling without OpenMP support.
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' wil
l not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running bdist_wheel
      running build
      running build_py
      creating build
      creating build\lib.win-amd64-3.8
      creating build\lib.win-amd64-3.8\lightfm
      copying lightfm\cross_validation.py -> build\lib.win-amd64-3.8\lightfm
      copying lightfm\data.py -> build\lib.win-amd64-3.8\lightfm
      copying lightfm\evaluation.py -> build\lib.win-amd64-3.8\lightfm
      copying lightfm\lightfm.py -> build\lib.win-amd64-3.8\lightfm
      copying lightfm\_lightfm_fast.py -> build\lib.win-amd64-3.8\lightfm
      copying lightfm\__init__.py -> build\lib.win-amd64-3.8\lightfm
      creating build\lib.win-amd64-3.8\lightfm\datasets
      copying lightfm\datasets\movielens.py -> build\lib.win-amd64-3.8\lightfm\datasets
      copying lightfm\datasets\stackexchange.py -> build\lib.win-amd64-3.8\lightfm\datasets
      copying lightfm\datasets\_common.py -> build\lib.win-amd64-3.8\lightfm\datasets
      copying lightfm\datasets\__init__.py -> build\lib.win-amd64-3.8\lightfm\datasets
      copying lightfm\_lightfm_fast_no_openmp.c -> build\lib.win-amd64-3.8\lightfm
      copying lightfm\_lightfm_fast_openmp.c -> build\lib.win-amd64-3.8\lightfm
      running build_ext
      building 'lightfm._lightfm_fast_no_openmp' extension
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed building wheel for lightfm
  Running setup.py clean for lightfm
  error: subprocess-exited-with-error
  
  × python setup.py clean did not run successfully.
  │ exit code: 1
  ╰─> [5 lines of output]
      Compiling without OpenMP support.
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' wil
l not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running clean
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
  ERROR: Failed cleaning build dir for lightfm
Failed to build lightfm
Installing collected packages: lightfm
  Running setup.py install for lightfm ... error
  error: subprocess-exited-with-error

  × Running setup.py install for lightfm did not run successfully.
  │ exit code: 1
  ╰─> [9 lines of output]
      Compiling without OpenMP support.
      C:\Program Files\WindowsApps\PythonSoftwareFoundation.Python.3.8_3.8.2800.0_x64__qbz5n2kfra8p0\lib\site-packages\setuptools\dist.py:642: UserWarning: Usage of dash-separated 'description-file' wil
l not be supported in future versions. Please use the underscore name 'description_file' instead
        warnings.warn(
      running install
      running build
      running build_py
      running build_ext
      building 'lightfm._lightfm_fast_no_openmp' extension
      error: [WinError 2] The system cannot find the file specified
      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.
error: legacy-install-failure

× Encountered error while trying to install package.
╰─> lightfm

note: This is an issue with the package mentioned above, not pip.
hint: See above for output from the failure.`

**Comment by haniyrasul** [comment]
This might work:
pip install lightfm --upgrade --ignore-installed scipy
