### ISSUE TITLE
max_sampled vs k vs n

### ISSUE THREAD

**Issue by zzzrpagliari** [lyst/lightfm#145]
`max_sampled` is the maximum number of negative example to be chosen when using WARP (how about BPR?). 
Which parameter controls the actual number of negative samples? Is it `max_sampled`, in a best effort kind of way?

The reason I'm asking is that `k `and `n `do not apply to WARP, per documentation. 

Thank you,

**Comment by maciejkula** [comment]
BPR always chooses one negative example per positive example.

WARP also attempts to find one negative example per positive example, but sampled negative examples that are ranked lower than the positive examples are discarded. The algorithm then tries again up to `max_sampled` times; if that fails, it just moves on to the next positive without performing a gradient step.
