### ISSUE TITLE
Load dataset from your machine

### ISSUE THREAD

**Issue by NSAryan12** [lyst/lightfm#150]
Hi,

is there anyway I can load datasets from my local machine in lightfm

Thanks

**Comment by maciejkula** [comment]
Yes, you can.

**Comment by drraghuram** [comment]
@maciejkula Is there any example code that shows how to load our own datasets into lightfm? 
Thanks

**Comment by harshgupta7** [comment]
http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/
