### ISSUE TITLE
item_features documentation

### ISSUE THREAD

**Issue by thadwoodman** [lyst/lightfm#161]
I'm really loving what you all have done here. Fast, easy to follow, already getting great recommendations.

The one thing I have struggled with a little is preprocessing a new dataset so that it is compatible with the `model.train()`.  Currently, I am reverse-engineering the MovieLens datasets to get a better understanding of the requisite formats – but it'd be really great to have some documentation along the lines of: "Item features are sparse matrices of the form M(item_id, feature_id)". Does that make sense?  Perhaps I'm missing something in the documentation. Happy to submit contributions if that'd help.

**Comment by joxer** [comment]
I agree with @thadwoodman, having a better documentation also for testing would be great! I'm having hard time figuring out out to do a dataset for training.

**Comment by maciejkula** [comment]
The current documentation says:
```
        """
        Fit the model.

        Arguments
        ---------

        interactions: np.float32 coo_matrix of shape [n_users, n_items]
             the matrix containing
             user-item interactions. Will be converted to
             numpy.float32 dtype if it is not of that type.
        user_features: np.float32 csr_matrix of shape [n_users, n_user_features], optional
             Each row contains that user's weights over features.
        item_features: np.float32 csr_matrix of shape [n_items, n_item_features], optional
             Each row contains that item's weights over features.
```

This is relatively close to what you suggest --- how would you improve it? I'm happy to have a look at PRs.

**Comment by tfzxyinhao** [comment]
+1
in real world,maybe have more than one feature for every user
is there has other tutorial for this ?

**Comment by maciejkula** [comment]
This blog post has a good section on how to build the feature matrices: http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/

Is this something you'd like to see documented more explicitly?

**Comment by thadwoodman** [comment]
@maciejkula Thanks! I eventually stumbled onto that after diving into the code a bit more. 

I was thinking that it might be helpful to mention it briefly in the documentation ("for requisite data formats, take a look at the inline documentation on lightfm.py") or to go through an example or converting a .csv or some other standard data file into something that is ready to be processed. That definitely would have saved me quite a bit of time.

**Comment by maciejkula** [comment]
I will absolutely accept PRs on this :)

**Comment by maciejkula** [comment]
Thanks for the suggestions. I think the docs are much better now!
