### ISSUE TITLE
Bad Zip File Error

### ISSUE THREAD

**Issue by MrPhilosopher** [lyst/lightfm#162]
Hi,
I am getting the following error when I tried to run the simple quick start program.

> C:\Users\Umer Qaisar\Anaconda3\lib\site-packages\lightfm\_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
>   warnings.warn('LightFM was compiled without OpenMP support. '
> Traceback (most recent call last):
>   File "C:\Data-My\test2.py", line 10, in <module>
>     data = fetch_movielens(min_rating=5.0)
>   File "C:\Users\Umer Qaisar\Anaconda3\lib\site-packages\lightfm\datasets\movielens.py", line 167, in fetch_movielens
>     item_metadata_raw, genres_raw) = _read_raw_data(zip_path)
>   File "C:\Users\Umer Qaisar\Anaconda3\lib\site-packages\lightfm\datasets\movielens.py", line 16, in _read_raw_data
>     with zipfile.ZipFile(path) as datafile:
>   File "C:\Users\Umer Qaisar\Anaconda3\lib\zipfile.py", line 1100, in __init__
>     self._RealGetContents()
>   File "C:\Users\Umer Qaisar\Anaconda3\lib\zipfile.py", line 1167, in _RealGetContents
>     raise BadZipFile("File is not a zip file")
> zipfile.BadZipFile: File is not a zip file

the code am running:
```
import numpy as np
from lightfm.datasets import fetch_movielens

data = fetch_movielens(min_rating=5.0)
print(repr(data['train']))
print(repr(data['test']))

from lightfm import LightFM

model = LightFM(loss='warp')
model.fit(data['train'], epochs=30, num_threads=2)

from lightfm.evaluation import precision_at_k

print("Train precision: %.2f" % precision_at_k(model, data['train'], k=5).mean())
print("Test precision: %.2f" % precision_at_k(model, data['test'], k=5).mean())

def sample_recommendation(model, data, user_ids):
    

    n_users, n_items = data['train'].shape

    for user_id in user_ids:
        known_positives = data['item_labels'][data['train'].tocsr()[user_id].indices]
        
        scores = model.predict(user_id, np.arange(n_items))
        top_items = data['item_labels'][np.argsort(-scores)]
        
        print("User %s" % user_id)
        print("     Known positives:")
        
        for x in known_positives[:3]:
            print("        %s" % x)

        print("     Recommended:")
        
        for x in top_items[:3]:
            print("        %s" % x)
        
sample_recommendation(model, data, [3, 25, 450])
```

**Comment by MrPhilosopher** [comment]
Found Error,
The downloaded zip file size was invalid, found the file from path and removed it.

ran the script again and it worked.

**Comment by maciejkula** [comment]
Awesome. Could you submit a patch that does this automatically? Say, tries 3 times before giving up if the file is invalid?

**Comment by MrPhilosopher** [comment]
I'll work on it.
