### ISSUE TITLE
has plan to support parallel?

### ISSUE THREAD

**Issue by tfzxyinhao** [lyst/lightfm#164]
feature request: support parallel `fit`

**Comment by maciejkula** [comment]
It already does, via keyword arguments to the `fit` function.

**Comment by tfzxyinhao** [comment]
Sorry for my incorrect description, I mean that support for distribute,
fit on multiple machine and then merge to one model

**Comment by maciejkula** [comment]
I'm afraid that's not in the works. I think you will find LightFM on a big machine is already fast enough for most use cases.

**Comment by tfzxyinhao** [comment]
In some scence, train data distribute on more than one machine

**Comment by maciejkula** [comment]
That is true. But I have no plans to support this.
