### ISSUE TITLE
Confusion about .predict() item_id boundaries

### ISSUE THREAD

**Issue by bcongdon** [lyst/lightfm#165]
I'm having a bit of confusion around the way to call `.predict()`, and the arguments it supports.

In the stackexchange example, the model is trained with the interaction and item_features matrices of shapes `(3221, 72360)` and `(72360, 1246)` respectively.

This leads me to assume that the model "knows" about 72360 items. Yet, when I try to predict the user-item score of user 0 with item 2000, (i.e. `model.predict(0, np.array(2000))`) I get this error:

```
assert self.item_embeddings.shape[0] >= item_features.shape[1]
```

Predicting with item_ids only works for item_ids less than 1246, which I took to be the number of item features.

Am I misinterpreting something, or is this intended behavior?

EDIT: I discovered that this error does not occur when you pass in the original item_features as a parameter to predict. Can you describe the reasoning behind this?

Thanks!

**Comment by maciejkula** [comment]
The model operates in terms of features: so it knows about 1246 features, the linear combinations of those can form any arbitrary number of items.

When you pass in the `item_features`, your item index indexes that matrix, then looks up the features in that row (so one or more of the 1246) in the embeddings matrices.

**Comment by bcongdon** [comment]
Ah, ok. I see. Thanks for the clarification!
