### ISSUE TITLE
item_embeddings

### ISSUE THREAD

**Issue by blancyin** [lyst/lightfm#169]
In lightfm.py, i saw
item_embeddings: np.float32 array of shape [n_item_features, n_components]
         Contains the estimated latent vectors for item features. The [i, j]-th entry
         gives the value of the j-th component for the i-th item feature. In the simplest
         case where the item feature matrix is an identity matrix, the i-th row
         will represent the i-th item latent vector.

i think n_item_features= m items + k item features
and  the first line is the first item embeddings(the one has item index 0) in train interactions, the m+1 line is the first item feature(the one has item feature index 0) in item_features matirx, one by one.
is't right?

**Comment by maciejkula** [comment]
No, that is not correct.

If you supply a feature matrix, the i-th column of that matrix has a latent representation in the i-th row of the embeddings.

If you do not supply a feature matrix, an (num_items x num_items) identity feature matrix is generated for you.

If you'd like to obtain the behaviour your describe, you need to supply a feature matrix of the appropriate structure.

**Comment by blancyin** [comment]
Thank you for your anwser, but i still did not understand.

I have trained a lightfm model, and i pickle.load this model. 
User feature matrix and item feature matrix  is userd.
I want to achieve the  feature and item latent, i don't konw the how to explain model.item_embeddings.

Then load the model and print the item_embeddings:

item_embeddings=model.item_embeddings
print item_embeddings.shape

the shape of item_embeddings.shape ,user_embeddings.shape,item_biases.shape,user_biases.shape
(1412757, 10)
(27001044, 10)
(1412757,)
(27001044,)

i think: 
10 is my no_components number (it is equal indeed)
1412757= m items + k item features (it is equal indeed)
27001044 = m' user + k' user features (it is equal indeed)

for k in item_embeddings:
   file.write(str(k))
and i print the model.item_embeddings, i found the latent, each latent is 10 dimension.

Can you tell me how can i find the correspondence between latent and item ?

**Comment by maciejkula** [comment]
The latent representation for the user/item represented by the i-th row of your feature matrix is given by the product of that row and the user/item embedding matrix.

So if you'd like to get the latent representation for user i, you'd take the i-th row (1 x num_components) of the user feature matrix, then multiply it with the (num_users x num_components) user_embedding matrix to obtain a (1 x num_components) latent representation for that user.

Is this what you're looking for?

**Comment by blancyin** [comment]
I am sorry for my poor english.

I know what your mean.
I want to calculate the item feature like your paper :
'bond' is same to '007'.

So i just use the i-th row in item_embeddings, i is the index of bond.

Thank you vere much

**Comment by maciejkula** [comment]
That's right!

No worries, happy I could help.
