### ISSUE TITLE
fit the model with only user_features and item_features.

### ISSUE THREAD

**Issue by pencoa** [lyst/lightfm#170]
In the basic situation, user-item interaction are inner products of users and items.
![wx20170422-000218](https://cloud.githubusercontent.com/assets/7123063/25286062/019d2d8a-26ef-11e7-8159-ab7c02477a5c.png)
Is it acceptable to fit lightFM model directly with user_features and item_features? 
Assume that there is a one-to-one correspondence between the features from users and items.

**Comment by pencoa** [comment]
In the document
`fit(interactions, user_features=None, item_features=None, sample_weight=None, epochs=1, num_threads=1, verbose=False)`
If interactions is a must to input, the others are optional?

**Comment by maciejkula** [comment]
All arguments with default values are optional, yes.

I'm not sure what you mean by 'fitting directly'? User and item features can have different cardinality.

**Comment by pencoa** [comment]
In some cases, the features from users and items can be selected to be the same. 
e.g, users have features a1, a2, a3
items have features a1, a2, a3
If user_1 and item_1 both have feature a1, then item_1 is recommended to user_1.

**Comment by pencoa** [comment]
if All arguments with default values are optional 
I will have a try to modify lightfm/lightfm.py lightFM class fit function
set interactions = None

**Comment by maciejkula** [comment]
This is not how this model works. There is no assumption that the user features and item features are the same.

**Comment by maciejkula** [comment]
Well, you'll always need interactions. Otherwise what do you fit your model on?

**Comment by pencoa** [comment]
soga

**Comment by pencoa** [comment]
Thanks for your reply.
