### ISSUE TITLE
how to use lightfm for other datasets than movielens ?

### ISSUE THREAD

**Issue by tugakariem** [lyst/lightfm#174]

**Comment by tfzxyinhao** [comment]
@tugakariem maybe you need to read [docments](http://lyst.github.io/lightfm/docs/home.html) first
and make attention on [example code](https://github.com/lyst/lightfm/tree/master/examples)
examples includes three demos show how to use lightfm

video [https://www.youtube.com/watch?v=9gBC9R-msAk](https://www.youtube.com/watch?v=9gBC9R-msAk)

notebook [https://github.com/tdeboissiere/Kaggle/blob/master/Ponpare/ponpare_lightfm.ipynb](https://github.com/tdeboissiere/Kaggle/blob/master/Ponpare/ponpare_lightfm.ipynb)

tutorial [http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/](http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/)
