### ISSUE TITLE
how to train by incremental ?

### ISSUE THREAD

**Issue by tfzxyinhao** [lyst/lightfm#178]
In my case, I have a problem with using lightFM

> new user produce  new data, and how to train by incremental

My understanding is that `fit_partial` use scene is that needs to get a good accuracy to stop training
is there have a solution to solve it

**Comment by Unimax** [comment]
why this was closed? i have same problem.

**Comment by impaktor** [comment]
You can't add new users or items to existing model, i.e. you can't change the dimension of the matrix, as that would be a new model.

You could initialize your model with some empty "dummy" rows/colums, that you then add new users to.

This is discussed in other issues here.
