### ISSUE TITLE
LightFM for Context Aware Recommender System

### ISSUE THREAD

**Issue by chrisbangun** [lyst/lightfm#182]
Hi @maciejkula 
I've been looking at this tool for a while and have a good impression on this. The examples are great too. However, I would like to know whether you have any example on how to use LightFM for Context-Aware Recommender System. It would be great if you can share some references.

Thanks

**Comment by maciejkula** [comment]
You can make it context aware by using suitably constructed item or user features. For example, you can add (quantised and one-hot-encoded) time of day to your item features in addition to any other features your item have.

**Comment by chrisbangun** [comment]
I see. So if I understand correctly, I have to build several matrix. one for item features, one for user features (if I have any) and the other one for user - item interactions matrix. Previously, I thought that the context is incorporated in one matrix, the user - item interaction matrix. So instead of have one value, we have a vector or list of values inside the user-item matrix.

**Comment by maciejkula** [comment]
Yes, that's correct.
