### ISSUE TITLE
newby problem

### ISSUE THREAD

**Issue by piero10** [lyst/lightfm#183]
sorry if my question seems stupid to you, but I spend two days with lightfm and didn't get, how it works.
I wrote simple example for test:
```
interactions = np.array([ [1, 0, 0, 0, 0, 0],
                                        [1, 1, 0, 0, 0, 0],
                                        [1, 1, 0, 0, 0, 0],
                                        [1, 1, 0, 0, 0, 0],
                                        [0, 0, 0, 0, 1, 1],
                                        [0, 0, 0, 0, 1, 1],
                                        [0, 0, 0, 0, 1, 1],
                                        [0, 0, 0, 0, 1, 1],
                                        [0, 0, 0, 0, 1, 1],
                                        [0, 0, 0, 0, 0, 1]])

n_users, n_items = interactions.shape
interactions = scipy.sparse.coo_matrix(interactions)

model = LightFM(learning_rate=0.05,
                loss='bpr',
                item_alpha=1e-6,
                no_components=30)

model.fit(interactions=interactions,
          epochs=20,
          num_threads=2,
          verbose=True)

scores = model.predict(user_ids=0, item_ids=np.arange(0, n_items))
print ["{0:0.2f}".format(i) for i in scores]
```
as you can see 0-user have a similar iteractions like users 1,2,3 have (all of thems have positive 1-th item)
and 0-user have no connection with other users, so in the result I expect to see something like:
0item                  1item                   2item                  3item                 4item                 5item
big number         big number         small number     small number    small number   small number

but I see:
['-0.42', '-0.42', '-0.31', '-0.31', '-0.21', '-0.20']
this result talk me that I should rank item 4 and item 5 highest than item 1. But it seems wrong to me.
Could you help me?

One more question I didn't get. when I use hybrid approach, I write:
```
model.fit(interactions=interactions,
               user_features=user_features,
               item_features=item_features, ...)
```
and then in prediction I should send the same "user_features" and "item_features" matrices to prediction method:

```
 model.predict( user_ids=user_ids, 
                         item_ids=item_ids,
                         user_features=user_features,
                         item_features=item_features)
 
```

??? is it right? it seems realy weird to me.... why should I send the same matrixes two times...

**Comment by maciejkula** [comment]
This is a tiny dataset, try running for more (say, 2000) epochs. Then you should see the result you expect.

Regarding your other question: I designed the library to allow using _different_ matrices at train and predict times.

**Comment by piero10** [comment]
maciejkula, thanks, I'll try. What about second question?

**Comment by maciejkula** [comment]
Sorry, what's the second question?

**Comment by piero10** [comment]
maciejkula, I'm sorry, you already answered it. 
> I designed the library to allow using different matrices at train and predict times.
Thanks for your work!
