### ISSUE TITLE
AssertionError after split dataset to train and test

### ISSUE THREAD

**Issue by chrisbangun** [lyst/lightfm#184]
Hi, I've spent quite some time in exploring LightFM and currently stuck on several things. Could you please look at my issue and lend me your help to resolve it?

1. How do we split our training and testing data? so far, I did it using `sklearn train_test_split` method? in recommender system problem, can we really do it like this?
`train, test = train_test_split(prebooking, test_size = 0.2, random_state=42)`

2. what are the best data representation that we need to create in order to make the most out of LightFM? For instance, I have the following data:
![screenshot from 2017-06-02 12-14-57](https://cloud.githubusercontent.com/assets/13383608/26711795/2a1e7480-478d-11e7-94fa-6f5ee5843bbd.png)

Having seen the code provided in the examples, I tried to do this:
```
def build_interaction_matrix(df, row_name, col_name, user_id_mapping, item_id_mapping):
    """
    given raw dataframe
    """
    n_rows = len(user_id_mapping)
    n_cols = len(item_id_mapping)
    mat = sp.lil_matrix((n_rows, n_cols), dtype=np.float64)
    for idx, row in df.iterrows():
        _rid, _cid =  user_id_mapping.get(row[row_name]), item_id_mapping.get(row[col_name])
        if row['interaction'] > 3:
            mat[_rid, _cid] = 1.0
        else:
            mat[_rid, _cid] = -1.0
    return mat.tocoo()

# Mapping user_id and item_id from train data to zero-based index
rid_to_idx_train, idx_to_rid_train,\
        cid_to_idx_train, idx_to_cid_train = get_df_matrix_mappings(train,
                                                        'user_id',
                                                        'item_id')
    
train_matrix = build_interaction_matrix(train, 'user_id', 'item_id', rid_to_idx_train, cid_to_idx_train)

# Mapping user_id and item_id from test data to zero-based index
rid_to_idx_test, idx_to_rid_test,\
        cid_to_idx_test, idx_to_cid_test = get_df_matrix_mappings(test,
                                                        'user_id',
                                                        'item_id')
    
test_matrix = build_interaction_matrix(test, 'user_id', 'item_id', rid_to_idx_test, cid_to_idx_test)
```
From the code above, I got two sparse matrix - train_matrix and test_matrix. Each has shape
```
train_matrix.shape: (1025081, 9282)
test_matrix.shape: ((450553, 8288)
```

Then I tried to feed it to the lightFM model:
```
model = LightFM(learning_rate=0.05,
                loss='warp',
                item_alpha=1e-6,
                no_components=30)
model.fit(train_matrix, epochs=500, num_threads=16)
```

Unfortunately, I got an error when executing this code:
```
train_precision = precision_at_k(model, train, k=10, num_threads=12).mean()
test_precision = precision_at_k(model, test, k=10, num_threads=12).mean()
train_auc = auc_score(model, train).mean()
test_auc = auc_score(model, test).mean()
print('Precision: train %.2f, test %.2f.' % (train_precision, test_precision))
print('AUC: train %.2f, test %.2f.' % (train_auc, test_auc))
```

the error is:
```
AssertionError                            Traceback (most recent call last)
<ipython-input-155-b9e86dfe1b93> in <module>()
----> 1 train_precision = precision_at_k(model, train, k=10, num_threads=12).mean()
      2 test_precision = precision_at_k(model, test, k=10, num_threads=12).mean()
      3 
      4 train_auc = auc_score(model, train).mean()
      5 test_auc = auc_score(model, test).mean()
      .....
    256         # we have them for all the supplied features
    257         if self.user_embeddings is not None:
--> 258             assert self.user_embeddings.shape[0] >= user_features.shape[1]
    259 
    260         if self.item_embeddings is not None:

AssertionError: 
```

Apologize, if I have so many questions. Any guides and advise would be really appreciated. Thank you so much

**Comment by maciejkula** [comment]
1. This way of splitting the matrix is not going to work. The usual sklearn tools split row-wise: this will of course not work here, where the entire point is taking some interactions from every row and putting them in the test set. Have a look at this [blog post series](http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/) to see an example of how to do the split.
2. Make sure your train and test matrices have the same dimensions. Having more users or items in the test set is nonsensical, as you would not have estimated representations for them in the training phase.

**Comment by chrisbangun** [comment]
hi @maciejkula 
thank you very much for your response.
Also, thanks for the reference. I'll redo my experiment as advised.
