### ISSUE TITLE
Failure while building docker container

### ISSUE THREAD

**Issue by davenovelli** [lyst/lightfm#185]
I've installed docker (version 17.03.1-ce) and attempted to build the contain using the instructions provided on the github.io site (https://lyst.github.io/lightfm/docs/home.html#using-with-docker) but hit an error before it completed. It appears it may be an issue with the python version (2.7) being incompatible with IPython 6.0+, which I believe requires Python >=3.3. It could also very likely be something else entirely!

Whether or not that's the issue, what changes would be required to the Dockerfile to install everything for Python 3?
[lightfm-docker.txt](https://github.com/lyst/lightfm/files/1047725/lightfm-docker.txt)

**Comment by maciejkula** [comment]
Handled in https://github.com/lyst/lightfm/pull/187
