### ISSUE TITLE
Build features vectors

### ISSUE THREAD

**Issue by jwheatp** [lyst/lightfm#191]
Hi,

About building users/items features vectors, I took a look at your examples in the repo and also at the post http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/, but I have a question about it.

I saw that you commonly used "tags" metadata about an item (or user), where you have several tags  values for a same item.

1. But let's take the case where we have, in the original metadata, only one tag value per item, and in total 100 different tags values. It will make a 100-dimensions vector, one-hot-encoded, with only one '1'.
Is it still a relevant feature item vector if it is that sparse ?

2. If I have several kind of tags (for example : item category, color, size type..), is it correct to concatenate my binary feature vectors together ?
Like this :

|        |     tag type A    |  tag type B | ...  |  tag type Z |
|:------:|:-----------------:|:-----------:|:----:|:-----------:|
| item 1 | 0 1 0 0 0 0 0 0 0 | 0 0 0 0 0 1 |  ... | 0 0 1 0 0 0 |
| item 2 | 0 0 0 0 0 0 1 0 0 | 0 1 0 0 0 0 |  ... | 0 0 0 0 1 0 |
|   ...  |        ...        |     ...     |  ... |     ...     |

Each 0 / 1 representing a different value encoded for each tag type

Thanks in advance

**Comment by maciejkula** [comment]
1. Yes, LightFM works best with sparse feature vectors.
2. Correct.

I would also recommend experimenting with indicator features: a feature that's 1 only for one item/user.

**Comment by jwheatp** [comment]
Thanks.

I built item feature vectors and user feature vectors. 
My item feature vectors increased well my precision score, but my user feature vector decrease slightly my precision score. I did many checks and my matrix is good, but I can't figure out why my precision score decrease. 
I know you don't have my code / data, but maybe you would have some clues about it ? Is there something special / harder with user vectors ?
Note: I normalized my matrix

**Comment by maciejkula** [comment]
Do you have per-user binary features? Do you have any features that lots of users have in common?

**Comment by jwheatp** [comment]
Yes, they are binary user features, and some features are shared by a lot
of users, such as the age bucket or the city they live in.

**Comment by maciejkula** [comment]
You could try excluding features, either individually or in groups, and measure the performance changes?

**Comment by jwheatp** [comment]
This is strange, because whatever the user feature group I try, It always decrease the accuracy.

Also, this is what I get for the user_biases matrix : 
```
[-4.84616089 -4.32035065 -4.42363214 -4.59546661 -4.87165165 -4.79935265
 -4.94092464 -5.11230135 -4.56947231 -4.36375046 -4.21067286 -4.38716269
 -4.1725626  -4.3375802  -4.24554253 -4.46307468 -4.42445707 -4.73932028
 -4.65806532 -4.51775551 -4.33859062 -4.4521699  -4.07685661 -4.85057259
 -4.41702795 -4.46412659 -4.5712266  -5.0045948  -4.38546419 -4.05183697
 -4.37861013 -4.53687239 -4.5924015  -4.55746889 -4.3572669  -4.5783453
 -4.63864565 -4.74321175 -4.44993877 -4.66760731 -4.82987118 -4.93526697
 -5.1922636  -4.5340414  -4.94212103 -4.23927116 -4.57736731 -4.67142248
 -4.49732637 -4.4367733  -5.08003712 -4.75161123 -2.26396394]
```

and for the predicted scores (using the `predict method` once) (top ten recommendations)
```
scores
-1.688872
-1.835690
-1.859145
-1.872488
-1.919604
-1.953401
-2.013271
-2.017010
-2.022043
-2.069141
```
Is it not strange that these values are negative ?

If I set the user_feature = None,  I get this for the scores 

```
1.106682
1.056287
1.000357
0.997396
0.994831
0.847245
0.827781
0.782809
0.765976
0.760468
```

**Comment by maciejkula** [comment]
Do you have per-user features, that is, is an identity matrix part of your `user_features`?

It's no _a prior_ worrying for scores to be negative. The values themselves have no interpretation.

**Comment by jwheatp** [comment]
> Do you have per-user features, that is, is an identity matrix part of
your user_features?

No, should it be the case ? Maybe I misunderstood something. Could you
please give more details / an example?

Thanks in advance

**Comment by maciejkula** [comment]
This is what I mean by 'per-user binary features': it if often useful for each user to have a feature that's one for them and zero for everyone else. This is in fact what happens if you do not pass any features in.

**Comment by jwheatp** [comment]
Thanks for your answer. Do you mean I should make an identity matrix first
and concatenate it with other custom features user vectors ? Like the
schema I did above but with an identity matrix concatenated on left?

**Comment by maciejkula** [comment]
Yes, I think that's worth trying.

**Comment by jwheatp** [comment]
Thanks a lot, it worked. I think I will do a blogpost or some PRs to explain some details of knowledge I missed during my work. I'll keep you informed ;)

**Comment by tkanngiesser** [comment]
@MatthiasKirsch did you make some progress on this in the meantime ? Happy to exchange some ideas

**Comment by maciejkula** [comment]
You should use the [`Dataset`](http://lyst.github.io/lightfm/docs/lightfm.data.html) functionality included in the latest version of LightM.
