### ISSUE TITLE
ImportError: No module named _lightfm_fast_no_openmp

### ISSUE THREAD

**Issue by fmacrae** [lyst/lightfm#193]
Tried installing via 
pip install lightfm

install looked clean but when testing with the sample code I get:

~$ python LightFM.py 
/home/finlay/lightfm/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
Traceback (most recent call last):
  File "LightFM.py", line 1, in <module>
    from lightfm import LightFM
  File "/home/finlay/lightfm/lightfm/__init__.py", line 4, in <module>
    from .lightfm import LightFM
  File "/home/finlay/lightfm/lightfm/lightfm.py", line 8, in <module>
    from ._lightfm_fast import (CSRMatrix, FastLightFM,
  File "/home/finlay/lightfm/lightfm/_lightfm_fast.py", line 12, in <module>
    from ._lightfm_fast_no_openmp import *  # NOQA
ImportError: No module named _lightfm_fast_no_openmp

Tried cloning and compiling too which worked clean

~$ cd lightfm && pip install -e .
Obtaining file:///home/finlay/lightfm
Requirement already satisfied: numpy in /home/finlay/.local/lib/python2.7/site-packages (from lightfm==1.13)
Requirement already satisfied: scipy>=0.17.0 in /home/finlay/anaconda2/lib/python2.7/site-packages (from lightfm==1.13)
Requirement already satisfied: requests in /home/finlay/anaconda2/lib/python2.7/site-packages (from lightfm==1.13)
Installing collected packages: lightfm
  Found existing installation: lightfm 1.13
    Uninstalling lightfm-1.13:
      Successfully uninstalled lightfm-1.13
  Running setup.py develop for lightfm
Successfully installed lightfm

Running the test script generates errors too:

~/lightfm$ python setup.py test
running test
running egg_info
writing requirements to lightfm.egg-info/requires.txt
writing lightfm.egg-info/PKG-INFO
writing top-level names to lightfm.egg-info/top_level.txt
writing dependency_links to lightfm.egg-info/dependency_links.txt
reading manifest file 'lightfm.egg-info/SOURCES.txt'
writing manifest file 'lightfm.egg-info/SOURCES.txt'
running build_ext
copying build/lib.linux-x86_64-2.7/lightfm/_lightfm_fast_openmp.so -> lightfm
============================================================= test session starts =============================================================
platform linux2 -- Python 2.7.13, pytest-3.0.7, py-1.4.33, pluggy-0.4.0
rootdir: /home/finlay/lightfm, inifile:
collected 2 items / 4 errors 

=================================================================== ERRORS ====================================================================
_____________________________________________________ ERROR collecting tests/test_api.py ______________________________________________________
ImportError while importing test module '/home/finlay/lightfm/tests/test_api.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_api.py:7: in <module>
    from lightfm import LightFM
E   ImportError: cannot import name LightFM
__________________________________________________ ERROR collecting tests/test_evaluation.py __________________________________________________
ImportError while importing test module '/home/finlay/lightfm/tests/test_evaluation.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_evaluation.py:7: in <module>
    from lightfm import LightFM, evaluation
lightfm/evaluation.py:9: in <module>
    from ._lightfm_fast import (CSRMatrix,
lightfm/_lightfm_fast.py:12: in <module>
    from ._lightfm_fast_no_openmp import *  # NOQA
E   ImportError: No module named _lightfm_fast_no_openmp
--------------------------------------------------------------- Captured stderr ---------------------------------------------------------------
/home/finlay/lightfm/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
________________________________________________ ERROR collecting tests/test_fast_functions.py ________________________________________________
ImportError while importing test module '/home/finlay/lightfm/tests/test_fast_functions.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_fast_functions.py:6: in <module>
    from lightfm import _lightfm_fast
lightfm/_lightfm_fast.py:12: in <module>
    from ._lightfm_fast_no_openmp import *  # NOQA
E   ImportError: No module named _lightfm_fast_no_openmp
--------------------------------------------------------------- Captured stderr ---------------------------------------------------------------
/home/finlay/lightfm/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
__________________________________________________ ERROR collecting tests/test_movielens.py ___________________________________________________
ImportError while importing test module '/home/finlay/lightfm/tests/test_movielens.py'.
Hint: make sure your test modules/packages have valid Python names.
Traceback:
tests/test_movielens.py:12: in <module>
    from lightfm import LightFM
E   ImportError: cannot import name LightFM
--------------------------------------------------------------- Captured stderr ---------------------------------------------------------------
/home/finlay/anaconda2/lib/python2.7/site-packages/sklearn/cross_validation.py:44: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. Also note that the interface of the new CV iterators are different from that of this module. This module will be removed in 0.20.
  "This module will be removed in 0.20.", DeprecationWarning)
/home/finlay/anaconda2/lib/python2.7/site-packages/sklearn/grid_search.py:43: DeprecationWarning: This module was deprecated in version 0.18 in favor of the model_selection module into which all the refactored classes and functions are moved. This module will be removed in 0.20.
  DeprecationWarning)
!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!! Interrupted: 4 errors during collection !!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!
=========================================================== 4 error in 1.39 seconds ===========================================================

**Comment by fmacrae** [comment]
Is it because I'm using Python 2.7?

**Comment by maciejkula** [comment]
It's probably because your import paths are wrong. You are trying to import from `/home/finlay/lightfm/lightfm/` (which you shouldn't have if you installed via pip and not cloned the repo) but the compiled extensions got installed somewhere else (in your virtual env or site packages). 

If you want to run tests, `pip install -e .` is the right way.

**Comment by fmacrae** [comment]
I installed via pip initially and due to the error
 ImportError: No module named _lightfm_fast_no_openmp
I then cloned the project and compiled it as instructed.  That is why my path changed to my home directory.
Tried reinstallation using 
pip uninstall lightfm
pip install -e lightfm


Ran the test code and still get:
~$ python LightFM.py 
/home/finlay/anaconda2/lib/python2.7/site-packages/lightfm/_lightfm_fast.py:9: UserWarning: LightFM was compiled without OpenMP support. Only a single thread will be used.
  warnings.warn('LightFM was compiled without OpenMP support. '
Traceback (most recent call last):
  File "LightFM.py", line 1, in <module>
    from lightfm import LightFM
  File "/home/finlay/anaconda2/lib/python2.7/site-packages/lightfm/__init__.py", line 4, in <module>
    from .lightfm import LightFM
  File "/home/finlay/anaconda2/lib/python2.7/site-packages/lightfm/lightfm.py", line 8, in <module>
    from ._lightfm_fast import (CSRMatrix, FastLightFM,
  File "/home/finlay/anaconda2/lib/python2.7/site-packages/lightfm/_lightfm_fast.py", line 12, in <module>
    from ._lightfm_fast_no_openmp import *  # NOQA
ImportError: No module named _lightfm_fast_no_openmp

**Comment by fmacrae** [comment]
I'm on ubuntu so default is python 2
installed pip3
~$ sudo apt-get install python3-pip
then lightfm using pip3
~$ sudo pip3 install lightfm

then the code works with python3 :)
~$ python3 movie_rank.py 
<943x1682 sparse matrix of type '<class 'numpy.int32'>'
	with 49906 stored elements in COOrdinate format>
<943x1682 sparse matrix of type '<class 'numpy.int32'>'
	with 5469 stored elements in COOrdinate format>

**Comment by maciejkula** [comment]
LightFM works with Python 2.7 too; I am convinced this was some misconfiguration of your Python installation/Python paths.

**Comment by fmacrae** [comment]
Thanks maciejkula, you are probably right but no point keeping the issue open for I am very new to python so have probably made a host of mistakes.  Saying that I've done little other than take latest ubuntu build then put annaconda on it using the default settings.  Then followed a bunch of steps to get tensorflow working along with pip installing dozens of things for Siraj's demos on Youtube

**Comment by maciejkula** [comment]
No worries. I'm glad it worked out.

**Comment by hixtc** [comment]
What do you need to do if the same thing happens on a MacBook pro-2017?
