### ISSUE TITLE
How to use LightFM with hierarchical items?

### ISSUE THREAD

**Issue by iozzyi** [lyst/lightfm#197]
Can I use LightFM to deal with recommendations on different levels of items? For example, the item can be configured by the user, so has a higher item level and a sub-item (configuration) level. Is it safe to make recommendations on the configuration level and then normalise and aggregate the scores for each product? What's the best way of going about this? Thanks

**Comment by maciejkula** [comment]
I think aggregation should be fine. You may also want to explore encoding your hierarchy in item features: for example, top level hierarchies may be columns 0 to 1000, sub-level 1000 to 10000 and so on.

**Comment by iozzyi** [comment]
Thanks for the tip, is there any reason why they should be organised in this way?

**Comment by maciejkula** [comment]
It's just feature engineering, really. You'll have features which denote categories/sub-categories etc. Because they are one-hot encoded it ends up looking a little that way.
