### ISSUE TITLE
AssertionError self.item_embeddings.shape[0] >= item_features.shape[1]

### ISSUE THREAD

**Issue by dofine** [lyst/lightfm#198]
I've been following the examples from http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/

My `item_features` is constructed from a csv data like
```
iid,tag
hash1,A
hash2,B
```
with `DictVectorizer` from `sklearn`
```python
item_features = pd.read_csv('data.csv')
item_features = pd.get_dummies(item_features, columns=['tag'])
item_features = item_features.T.to_dict().values()
vec = DictVectorizer(sparse=True)
item_features = vec.fit_transform(item_features)
```
I think the problems lie with `item_features = item_features.T.to_dict().values()` and `DictVectorizer` part?
The train set and test test shape is both (27393, 6676). And `item_features` shape is (6778, 6918). There are 241 distinct tags for item features.

**Comment by maciejkula** [comment]
If there are 241 distinct tags for item features, how is the column dimension of `item_features` 6918? Shouldn't it be 241? What is happening is that you most likely fit embeddings only for 241 features, but then supply a features matrix with far more features later.

**Comment by dofine** [comment]
It seems that I  added index of the pandas dataframe into the `item_features`. Will check it tomorrow.

**Comment by dofine** [comment]
Find out that 
```python
item_features = pd.get_dummies(item_features, columns=['tag'])
item_features = item_features.T.to_dict().values()
vec = DictVectorizer(sparse=True)
item_features = vec.fit_transform(item_features)
```
get wrong feature names with `['iid=hash1', 'iid=hash2', 'tag=A', 'tag=B']`, thus the shape of item-features is much much larger. But I don't know the difference between `OneHotEncoder` in sklearn and `get_dummies` in pandas. Maybe should learn more basics of it.

**Comment by chrisbangun** [comment]
I have similar problems to this. I've checked your code and found this from https://github.com/lyst/lightfm/blob/a37d0c2/lightfm/lightfm.py#L261:

`assert self.item_embeddings.shape[0] >= item_features.shape[1]`

What is the intuition behind this? Why must the number of item features be less than the number items?

**Comment by maciejkula** [comment]
@chrisbangun I opened a PR to improve the documentation on this point: https://github.com/lyst/lightfm/pull/206

Let me know if that answers your question --- if not, I'll try to expand until it's clear.

**Comment by dofine** [comment]
Read the docs and fixed my problems. 
Great work and thanks! @maciejkula

**Comment by maciejkula** [comment]
Great! Let me know if you have any further questions.

**Comment by dofine** [comment]
@maciejkula https://github.com/lyst/lightfm/blob/master/lightfm/lightfm.py#L311
Here the exception should be "The item feature matrix specifies more" instead of "The user feature matrix specifies more"?

**Comment by maciejkula** [comment]
Yes. Good spot.
