### ISSUE TITLE
nan AUC

### ISSUE THREAD

**Issue by Tullio-DH** [lyst/lightfm#199]
Hello,

to test a pure CF approach, I've first created a dataframe of rows as users and columns as items. The density is ~0.025; ratings are in the 0-10 range and missing interactions are NaN.

I've then converted it to a sparse matrix:
```
scoo_weighted_ratings = sparse.coo_matrix(weighted_ratings)
print('The dataset has %s users and %s items '
% (scoo_pivot_weighted_rating.shape[0], scoo_pivot_weighted_rating.shape[1]))
```
```
The dataset has 6873 users and 186 items 
```

and inputed it to lightFM as shown in the tutorial:
```
# Set the number of threads; you can increase this
# ify you have more physical cores available.
NUM_THREADS = 2
NUM_COMPONENTS = 5
NUM_EPOCHS = 3
ITEM_ALPHA = 1e-6

# Let's fit a WARP model: these generally have the best performance.
model = lf.LightFM(loss='warp',
                item_alpha=ITEM_ALPHA,
               no_components=NUM_COMPONENTS)

# Run 3 epochs and time it.
%time model = model.fit(scoo_weighted_rating, epochs=NUM_EPOCHS, num_threads=NUM_THREADS)
```
```
CPU times: user 4.93 s, sys: 13.8 ms, total: 4.94 s
Wall time: 4.94 s
```

However, I don't think much is being fit: 
```
train_auc = auc_score(model, scoo_weighted_rating, num_threads=NUM_THREADS).mean()
print('Collaborative filtering train AUC: %s' % train_auc)
```
```
Collaborative filtering train AUC: nan
```

what is the problem with my input? Are NaNs not allowed, to represent a non-existing interaction?

**Comment by maciejkula** [comment]
`NaN`s are absolutely not allowed. I already check most possible inputs for `NaN`s and generate appropriate errors, but apparently not this bit yet.

I'll add that check in a PR later today.

Missing interactions should be represented as zeros in your sparse interaction matrix.

**Comment by Tullio-DH** [comment]
Alright, thanks!
Don't you think this might be ambiguous however? Some datasets (including mine, which is a real one) do admit rating = 0. Of course I can easily change that to some arbitrary small numbers, and then replace the nans with zeros.

**Comment by maciejkula** [comment]
Also, LightFM is primarily an implicit feedback algorithm: it doesn't use ratings. If you think ratings are important, you could consider using them as [weights](https://github.com/lyst/lightfm/blob/master/lightfm/lightfm.py#L384).

**Comment by Tullio-DH** [comment]
I see. So, would you use an input matrix of only 1s and 0s (for the presence/absence of interactions) and a separate (identically shaped) matrix of ratings to be passed to the fit function as weights?

**Comment by maciejkula** [comment]
Correct; take care to remember that these are weights, not ratings, and the choice of their magnitude will affect convergence.

**Comment by maciejkula** [comment]
Checks merged in https://github.com/lyst/lightfm/pull/200
