### ISSUE TITLE
Collaborative filtering giving higher AUC scores than hybrid?

### ISSUE THREAD

**Issue by iozzyi** [lyst/lightfm#201]
When I use lightfm to score an implicit feedback purely based on user interactions I am getting high AUC scores around 80%. However, when I add the item features the AUC score drops considerably to around 55% for most item feature combinations (and I found 70% test score for a certain combination of features). I wonder if this just means the item embeddings are inaccurate (due to errors in the data) or it could be something else?

**Comment by maciejkula** [comment]
This could be for many reasons. Two leading ones:
1. If you supply explicit item/user features it only uses the features you provide: that is, a per-user and per-item feature is no longer used. If you'd like to retain your behaviour you need to concatenate your feature matrices with an identity matrix.
2. You may need to do a hyperparameter search.

**Comment by iozzyi** [comment]
Sorry, I am not so clear on point 1.
1. Is this just the way LightFM was built that it doesn't use some features when explicitly giving it an item feature matrix? What are the per-user and per-item feature? Did you mean it doesn't calculate a score separately for each user/each item for efficiency? Is this described somewhere in detail in the docs that I can read about it? Finally, if I concat an identity matrix to the feature matrix, I guess it will be in the rows otherwise the labels will be messed up. But why does that trigger LightFM to use per item features?
2. I guess it would not be a fair comparison without finding optimal hyperparameters for both models so I'll try that next.
Thank you.

**Comment by maciejkula** [comment]
If you don't provide any features, LightFM uses an identity matrix. This means that every user and every item get a single features that is unique to them.

If you do supply features, LightFM just takes them as given. This may mean a reduction in accuracy if your features are less expressive. If you stack things, you should do it column-wise: your output will be of shape `(num_items, num_items + num_metadata_features)`.

This is currently under-documented and is a frequent point of confusion. I will try to expand the docs soon.

**Comment by iozzyi** [comment]
Okay, thanks. I will leave this open until you have the link to the doc (in case other people searching find the same question).

**Comment by maciejkula** [comment]
Sounds good.

**Comment by maciejkula** [comment]
Added some more explanation to the docs: https://github.com/lyst/lightfm/pull/206

Any suggestions on how to make it clearer?

**Comment by iozzyi** [comment]
Just an example in the docs on how the identity matrix is appended to the item/user feature matrix would be nice? You wrote it here but I didn't see it in #206, '(num_items, num_items+num_features)'. Since LightFM already has code written to do this, it would be good to have a parameter option to append the identity matrix when supplying the item/user feature matrix. But otherwise clear, thanks.

**Comment by maciejkula** [comment]
Yes, that would be useful. I'll make that change.

**Comment by iozzyi** [comment]
Resolved then, thanks again :)
