### ISSUE TITLE
feature request: matrix of scores/rankings

### ISSUE THREAD

**Issue by Tullio-DH** [lyst/lightfm#202]
Hello,

sorry for the naif question, but what would be the simplest way to return a matrix/dataframe of the same shape as the input, but containing, e.g., the scores of the interactions, or the ranking per column (with each column a user, each row an item)?

I wondered if this could be made a default feature of LightFM (like the lightfm.evaluation functions) since it's what many users might need to store anyway.

**Comment by maciejkula** [comment]
`predict_rank` will return a (num_users x num_items) matrix, where nonzero `(i, j)` entries contain ranks of item `j` for user `i`. You specify which these should be by passing in a `test_interactions` matrix.

In general returning a _dense_ matrix of this form is infeasible: for many problems, it would require a ludicrous amount of memory. If that's what you'd like, I'd recommend just iteratively calling `predict` for every user.
