### ISSUE TITLE
How to save model checkpoint?

### ISSUE THREAD

**Issue by leminhlong5194** [lyst/lightfm#207]
Thank you for making this great tool,
I have a question regarding how I can save progress of my training.
After training for a list of training data how can you save the data so that the model does not need to retrain every time we want it to give out recommendations?

**Comment by maciejkula** [comment]
You can simply use Python's [`pickle`](https://docs.python.org/3/library/pickle.html) once you've fitted your model:
```python
import pickle

model = LightFM()
model.fit(data)

with open('savefile.pickle', 'wb') as fle:
    pickle.dump(model, fle, protocol=pickle.HIGHEST_PROTOCOL)
```

**Comment by leminhlong5194** [comment]
Thank you very much
