### ISSUE TITLE
How are the relevancy scores and AUC score created from the reconstructed matrix?

### ISSUE THREAD

**Issue by iozzyi** [lyst/lightfm#208]
I am trying out a similar model to LightFM however using Non-negative matrix factorisation.
From what I understand, I need to decompose the matrix (or numerically approximate) to get W, H where WH approximately equals X. Then I have Xr = WH. Now from Xr what is the model used to calculate the scores for each user so that I can get their top items? I ask because all the scores in LightFM are arbitrary negative numbers, where the most negative number indicates the most relevant item?

What is the condition for treating a predicted item relevancy as true positive and false positive to get the AUC score from Xr?

**Comment by maciejkula** [comment]
The scores in LightFM define the ranking: the higher the scores is for a given item, the more likely it is to be recommended. To get the top items, you should score all items and then retrieve the ones whose scores are the highest (this holds even when the scores are negative). The `Xr` in your terminology is exactly what is output by the `predict` method.

In the binary case (clicked/not clicked), the AUC score has a nice interpretation: it expresses the probability that a randomly chosen positive item (an item the user clicked) will be ranked higher than a randomly chosen negative item (an item the user did not click). Thus, an AUC of 1.0 means that the resulting ranking is perfect: no negative item is ranked higher than any positive item

**Comment by iozzyi** [comment]
So are all the ratings treated as binary for the AUC score in LightFM? I am using implicit feedback so there are counts of each interaction the user made with the items.

**Comment by maciejkula** [comment]
Yes, they are treated as binary.

**Comment by iozzyi** [comment]
Okay, that's all, thank you.

**Comment by iozzyi** [comment]
Hello,

I didn't fully understand how the latent item features are incorporated into the score in LightFM.

In the LightFM paper it says: 
p = user embedding, q = item embeddings, score = dot(q,p) + biases

I am having this issue when trying to calculate the scores with the item feature matrix:
    p = (N users, M items)
    q = (M items, Z features)
So when I make the product of dot(p,q) I get:
    scores = (N users, Z features)
I am actually doing 1 user at a time by taking a single row index from the user-interaction (N,M) matrix = (1 user, M items).
Then for a given user I have the scores as an array of (1, Z features) instead of (1, M items)
So now I don't have a score for each item?

But to calculate the AUC I believe I need a score for each item for each user? 
I have been following the example here: https://jessesw.com/Rec-System/ (There is a method def cal_mean_auc)

Thanks

**Comment by maciejkula** [comment]
Please have a look at my [paper](https://arxiv.org/pdf/1507.08439.pdf) for the full formulation. You may also find my recent [addition](https://github.com/lyst/lightfm/pull/206) to the documentation helpful.

**Comment by maciejkula** [comment]
Closing this for now. Let me know if you have any more questions.
