### ISSUE TITLE
Can I construct a LightFM model with existing matrices?

### ISSUE THREAD

**Issue by iozzyi** [lyst/lightfm#209]
Is there any way to wrap a LightFM model around existing matrices ? I've already done the factorisation, but would like to take advantage of LightFM's fast evaluation methods without having to re-implement them.

**Comment by maciejkula** [comment]
You can just instantiate the model and replace the existing attributes. It might be a bit fiddly.

This is probably not a very common use case, so I don't think I'll be adding any functionality to support it.

**Comment by iozzyi** [comment]
Thanks
