### ISSUE TITLE
What is the correct method of creating train and test splits on data for LightFM model?

### ISSUE THREAD

**Issue by iozzyi** [lyst/lightfm#215]
Are we supposed to give the LightFM model data splits like this:
train = large split (say 80% of interaction data) , test = small split (20% of the data)
- OR -
test = 100% of data, and train = 80% (20% is masked from train).

Which way is correct?

Thanks

**Comment by maciejkula** [comment]
The most common practice is to make sure that the training and the test set are disjoint: no interactions should be shared between the two.

That way your evaluation gives you a better measure of the model's generalization performance: its accuracy on data it has not seen during training.

**Comment by maciejkula** [comment]
@iozzyi https://github.com/lyst/lightfm/pull/222

**Comment by maciejkula** [comment]
Out in the newest version.
