### ISSUE TITLE
on input data shape

### ISSUE THREAD

**Issue by lucidfrontier45** [lyst/lightfm#216]
Hi, I have several questions on the input shape.
Some of them may be duplicate of other issues but I want to make it clear and comprehensive here.

1. Do I need to re-arrange user and item ids?
The first question is on actual id and index of sparse matrix. Suppose my data set has integer user id which does not start from 0 and not contiguous, like `[2,4,6,7,10]`. Do I need to re-arrange it to `[0, 1, 2, 3, 4]` for making input interaction matrix and feature matrix of `fit` method? I believe both index style give essentially the same sparse matrices.

2. Can I supply feature matrices some of whose ids did not appear in the interaction matrix?
Suppose there are 10 users (id=0-9) registered in my service. However only 5 (say id = `[1,3,5,7,9]`) have activities. Then the interaction matrix only contains data for those 5 users. Now can I just put the complete 10 user feature matrix to the `fit` method? I know this does not help accuracy. It's just for the convenience. I don't want to make a partial 5 user feature matrix from the complete 10 user matrix.

3.  Shape of feature matrix in `predict` method.
Suppose I want to make some prediction for user_id = 100, who has no past activity, only features.
As the doc says, `predict` method accepts `user_features (np.float32 csr_matrix of shape [n_users, n_user_features], `. Here, what is `n_users`?  1 or 100? In other words, Does this feature matrix only has one row or it's a matrix of row > 100 and at least row_100 has non zero values?

4. If I use the paired style api of `predict` what feature matrix shape?
For example, `user_ids = [1,1,20,20,100]` and `item_ids = [0,1,0,2,5]`. What is`n_users`? 3? 5? or 100?

Lastly, I only mentioned on user id/ matrix. Is the above discussion also valid for item part?

Thank you.

**Comment by maciejkula** [comment]
These are all good questions. My responses below.

1. You do not _need_ to make the contiguous and starting at 0; the model will work find. However, it will allocate parameters for indices in-between that you don't use, which will make your model larger (and potentially more noisy).
2. Yes, you can, subject to the same caveat as above.
3. User ids here are _indices_ into the feature matrices. So if your user id is 100, your feature matrix will need to have at least 101 rows; but if you make the user id 0, you can have a feature matrix with a single row.
4. With the values you provided, `n_users = max([1, 1, 20, 20, 100]) + 1 = 101`.

Users and items are symmetrical in this model, so this applies equally. You may find my [recent changes](https://github.com/lyst/lightfm/commit/82b215456720cb27c11ee595767c680583bda043) to the documentation helpful here.

**Comment by lucidfrontier45** [comment]
@maciejkula 

Thank you for response.
I wanna confirm if I understood it correctly.

A. On question 3 and 4 about the `predict` api, the user feature matrix's row indexes correspond to the user_ids passed as the first argument. If I passed [0, 1,4,10] as user_ids, the feature matrix must at least   has 11 rows and 4 rows (0, 1, 4, 10) should have non-zero values.

B. With paired style, same user_ids will be passed several times like [0, 1, 1, 1, 4, 4, 10] but feature matrix must not contain duplicated id and is the same as case A.

Are A and B correct?

**Comment by maciejkula** [comment]
1. That's correct.
2. That is also correct.

Again, the ids are just indices into rows of the feature matrices.

Hope this helps!

**Comment by lucidfrontier45** [comment]
@maciejkula 

Thank you very much!
