### ISSUE TITLE
Supporting MovieLens 1M/10M/20M dataset

### ISSUE THREAD

**Issue by nahidalam** [lyst/lightfm#223]
How can I get MovieLens 1M/10M/20M dataset to work with LightFM? Either of those 3 datasets will work.

**Comment by maciejkula** [comment]
It's naturally possible to use all these datasets: you simply need to parse them into suitable `scipy.sparse` matrices.

The easiest way of getting them would be with the help of the [Spotlight](https://github.com/maciejkula/spotlight) package. After installing it, you could simply run the following to obtain the sparse matrix representations of those datasets:
```
from spotlight.datasets import movielens

data = movielens.get_movielens_dataset(variant='1M').tocoo()
```

All the Movielens datasets are available (`('1M', '10M', '20M')`)
