### ISSUE TITLE
How to use user's features for movie recommendations?

### ISSUE THREAD

**Issue by Adnation** [lyst/lightfm#224]
Hey Thanks for this package. 

I checked this fetch_movielens method where we are extracting only

1. Train and Test data of interaction matrix
2. Movie Features
3. List of generes

So are we not using user's data like occupation, gender, age & zip code for recommendations?

If we are using those user features then can you explain me how?

If we are not then can you suggest me how can I incorporate the same?

**Comment by maciejkula** [comment]
They are not used in the canned datasets in LightFM, but there is no reason why you couldn't parse them into suitable feature matrices and use them in your model (have a look at the [docs](https://lyst.github.io/lightfm/docs/lightfm.html)).

**Comment by Adnation** [comment]
So is it user features in fit model like [https://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.fit](this) you are saying? If yes can you provide one example of such?
