### ISSUE TITLE
AssertionError when doing prediction 

### ISSUE THREAD

**Issue by Berenliu** [lyst/lightfm#226]
When I was using the model to do prediction like this

> preds = model.predict(user_ids, item_ids, item_features=item_feat,user_features=user_feat, num_threads=4)

Then the Error came out:

>   File "/root/anaconda/lib/python2.7/site-packages/lightfm/lightfm.py", line 623, in predict
>     assert len(user_ids) == len(item_ids)
> AssertionError

I am just wondering why should one check if len(user_ids) and len(item_ids) are equal.

**Comment by beduffy** [comment]
Hey,
I'm also wondering why this is so.

Why can't we predict scores for 500 items for 10 users?
len(user_ids) = 10
len(item_ids) = 500

This seems totally logical to me. However, the way around this is to use a loop where I call predict on each user. However, for my problem this will take over 10 hours for ~70k users and ~90k items.

**Comment by beduffy** [comment]
Fair enough.

Though, I'm still confused as to why do they have to be equal sizes though?

**Comment by maciejkula** [comment]
Because they define user-item pairs.
