### ISSUE TITLE
Add convenience features for beginners

### ISSUE THREAD

**Issue by blissray** [lyst/lightfm#229]
Hello. I am a beginner who recently started using lightFM.
I like this library because this library provides simple and relatively high performance.

However, I think this is unfamiliar for the first time for users who have studied ML with scikit-learn.

I think some modules are needed for this library.

For example
- module to convert data frame to coo matrix
- module for measuring RMSE or other measurement metrics
- a module that divides data into tests and trains

I would like to build PR but I hesitate because I do not know the plan for the development.
Could you tell me about future updates?

I want to make something to help this LightFM. :)

**Comment by maciejkula** [comment]
Hey, glad you found LightFM helpful! A couple of thoughts:

1. I think this could be useful! Would you mind writing an example (say, a Jupyter notebook)? I don't really want to include pandas as a dependency of this library.
2. The metrics are already here! Have a look at the [docs](http://lyst.github.io/lightfm/docs/lightfm.evaluation.html). (RMSE is not a good metric for evaluating recommendations, so it is not included.)
3. I added something recently [here](https://github.com/lyst/lightfm/blob/master/lightfm/cross_validation.py#L20). It's not on PyPI yet, but I will push it soon.

**Comment by maciejkula** [comment]
Update: the train/test split is out in the new version.
