### ISSUE TITLE
[OSX] GCC available via macports, yet setup does not find it

### ISSUE THREAD

**Issue by saihttam** [lyst/lightfm#23]
Because the support text asked for feedback on installation on OS X, I add my current installation issue:
---
      File "/private/tmp/pip_build_root/lightfm/setup.py", line 35, in set_gcc
        raise Exception('No GCC available. Install gcc from Homebrew '
    Exception: No GCC available. Install gcc from Homebrew using brew install gcc.
-----
However gcc is installed via macports:
[terminal]: port installed | grep gcc
  gcc48 @4.8.5_0 (active)
  gcc49 @4.9.3_0 (active)
-----
macports typically installs under /opt/local/. [1]
If you want to support this, I guess you could simply add to line 28 in setup.py?

[1] https://guide.macports.org/chunked/installing.macports.html

**Comment by maciejkula** [comment]
Thanks for opening the issue; could you have a look if https://github.com/lyst/lightfm/pull/24 solves this for you?

**Comment by saihttam** [comment]
This does not fix the problem completely regretfully as it results in the problem addressed issue #25. There are several gcc-related binaries in that folder. For me this includes:
['/opt/local/bin/gcc-ar-mp-4.8', '/opt/local/bin/gcc-ar-mp-4.9', '/opt/local/bin/gcc-mp-4.8', '/opt/local/bin/gcc-mp-4.9', '/opt/local/bin/gcc-nm-mp-4.8', '/opt/local/bin/gcc-nm-mp-4.9', '/opt/local/bin/gcc-ranlib-mp-4.8', '/opt/local/bin/gcc-ranlib-mp-4.9']
But you don't want the -ar- 's and the -ranlib-'s...
So I guess the setup must be more selective....

**Comment by maciejkula** [comment]
Can you try a `glob` pattern that works for your installation?

**Comment by saihttam** [comment]
Maybe something like this? (That solves the compile issue for me)
    patterns = ['/opt/local/bin/gcc-[0-9].[0-9]',
                '/opt/local/bin/gcc-mp-[0-9].[0-9]']
And I guess you would want to treat /usr/local/bin/ similarly...

**Comment by maciejkula** [comment]
I updated #24, can you try again?

**Comment by saihttam** [comment]
Tried
python setup.py test
(30 passed in 128.18 seconds)
and the movie lens example and both work fine. 
Thanks!

**Comment by maciejkula** [comment]
Great, let's see if it works with the other issue.

**Comment by maciejkula** [comment]
I pushed the updated code to pypi as version 1.5. Thanks for your help!
