### ISSUE TITLE
Not really an issue: what is the difference between lightFM and fastFM?

### ISSUE THREAD

**Issue by PabloMessina** [lyst/lightfm#232]
Does lightFM support Steffen Rendle's Factorization Machines, just like fastFM does?

**Comment by maciejkula** [comment]
Not quite: the interactions within item features or within user features are not modelled, only between them.

**Comment by PabloMessina** [comment]
I see, so what does "FM" stand for at the end of "lightFM", if I may ask?

**Comment by maciejkula** [comment]
Factorization Machines, but they are _light_ and not the whole deal. To be honest I didn't think about the naming too much.
