### ISSUE TITLE
mini batch feed for training

### ISSUE THREAD

**Issue by arita37** [lyst/lightfm#234]
Hi,

Is there a way to do mini-batch feed from a list of files to feed lightFM trainer ?
Sometimes, we need to deal out of RAM dataset.
Thanks, regards

**Comment by maciejkula** [comment]
Sure. You can just read your interaction data from disk in batches, construct sparse matrices, and fit them to subsequent `fit_partial` calls. Just make sure that all the matrices have the same number of rows (users) and columns (items).

**Comment by arita37** [comment]
Suppose we have
1 million of users and 1 million items
on text file 

Each mini-batch does not contain the same
number of user, item.

Is it fine ?








On Dec 1, 2017, at 6:05, Maciej Kula <notifications@github.com> wrote:

Sure. You can just read your interaction data from disk in batches, construct sparse matrices, and fit them to subsequent fit_partial calls. Just make sure that all the matrices have the same number of rows (users) and columns (items).

―

**Comment by maciejkula** [comment]
No, each minibatch be transformed into an interaction matrix with the same dimensions. This doesn't mean that each minibatch has to have the same number of interactions, or interactions from the same users.

Example: minibatch A has interactions `[(user 1, item 1), (user 1, item 2)]`, minibatch B has interactions `[(user 2, item 3), (user 2, item 4)]`. These are fine as long you transform each into sparse matrices of shape (2, 4) before passing them into LightFM (the same is true for Spotlight).

**Comment by arita37** [comment]
Hello,

Thanks,
But, how the sparse matrix is filled ?

with float for numerical values
with int=1 for category one hot encoding ?

Should we do the one hot index encoding ?

Thanks, regards
Kevin








On Dec 1, 2017, at 18:19, Maciej Kula <notifications@github.com> wrote:

No, each minibatch be transformed into an interaction matrix with the same dimensions. This doesn't mean that each minibatch has to have the same number of interactions, or interactions from the same users.

Example: minibatch A has interactions [(user 1, item 1), (user 1, item 2)], minibatch B has interactions [(user 2, item 3), (user 2, item 4)]. These are fine as long you transform each into sparse matrices of shape (2, 4) before passing them into LightFM (the same is true for Spotlight).

―

**Comment by maciejkula** [comment]
You should create a sparse matrix with 1s for those (user, item) pairs where an interaction happened. Leave everything else at 0.

**Comment by arita37** [comment]
Can we add context features as numerical,
like the age of persons (whatever stats...)
in the same sparse matrix ?

ie combine category with no category.

Kind regards.








On Dec 1, 2017, at 23:07, Maciej Kula <notifications@github.com> wrote:

You should create a sparse matrix with 1s for those (user, item) pairs where an interaction happened. Leave everything else at 0.

―

**Comment by maciejkula** [comment]
No, this would go in the user/item feature matrices. Please have a look at the [documentation](http://lyst.github.io/lightfm/docs/home.html).
