### ISSUE TITLE
Problem with item features

### ISSUE THREAD

**Issue by JaimePata** [lyst/lightfm#235]
Hi.
I was trying to use LightFM for a college project.
I'm using giving the model a item features matrix with shape (16010,687).
My interaction data matrix have shape (17832,16010).
I can train my model with model.fit(train,epochs=5,num_threads=4, item_features=item_features), where train contain my interaction data matrix and item_features my item features matrix.
After I train, if I want to predict something I get the following error:
ValueError: The user feature matrix specifies more features than there are estimated feature embeddings: 687 vs 16010.

What can be causing this?

**Comment by maciejkula** [comment]
What call are you making to the predict function? What is the shape of its arguments?

**Comment by JaimePata** [comment]
Sorry, I was wrong in my first post. I can make individual predictions. However I can't use functions to evaluate my model using a test set.
I was trying to test precision using test_precision = precision_at_k(model, test, k=4).mean()
test have shape (17832, 16010)

**Comment by maciejkula** [comment]
Ah, I see. The error message is actually quite misleading, see fix here https://github.com/lyst/lightfm/pull/236. The gist is that you need to pass in the item features to the evaluation method (the features are not stored in the model).

**Comment by JaimePata** [comment]
Oh, thanks a lot. I assumed that the item features was stored in the model, and the misleading error didn't help either haha, I was confused because I thought that the error was related to the users features, that I did not use.

Thanks, now is working as expected.

**Comment by maciejkula** [comment]
Thanks for the bug report!

**Comment by GitHub474878** [comment]
Another debug for latest version：Just because the user_id or item_id is larger than the matrix.shape.
