### ISSUE TITLE
Incorporate time dependant features

### ISSUE THREAD

**Issue by arita37** [lyst/lightfm#237]
Related to LightFM,

1) Is there a way to input time dependant user_features or item_features : stats on past purchase (refreshed periodically), no static features ?

2) How the traning model behaved if new trainings contain 
    also same past interactions, but with new ratings.

**Comment by maciejkula** [comment]
1. Sure, you could do that. To construct the features matrix, you need to treat the views of one user over time as new users, giving the features new values where they have changed, and keeping them constant where they haven't. For example, if you had 100 users, and wanted 5 time-views of each,  you'd end up with a feature matrix with 500 rows.
2. LightFM doesn't take ratings: it's an _implicit_ feedback model (which is what you want; models with ratings is something you almost never want).

**Comment by arita37** [comment]
Hello,

1)
thanks, this is similar to online fitting with partial fit.


2)
For ranking problem, is implicit feedback better tham sorting the rating ?

This is not clear , in which way it can be better.


Thanks.










On Dec 3, 2017, at 22:08, Maciej Kula <notifications@github.com> wrote:

Sure, you could do that. To construct the features matrix, you need to treat the views of one user over time as new users, giving the features new values where they have changed, and keeping them constant where they haven't. For example, if you had 100 users, and wanted 5 time-views of each, you'd end up with a feature matrix with 500 rows.
LightFM doesn't take ratings: it's an implicit feedback model (which is what you want; models with ratings is something you almost never want).
―

**Comment by maciejkula** [comment]
Have a look at this [paper](https://arxiv.org/abs/1206.5267). The bottom line is: data on which items users choose to rate is much more important than the rating given. Hence, implicit recommender systems.

**Comment by arita37** [comment]
Hello,

It makes sense for rating survey.
But, what about when we transpose
Nb of Clicks and Nb of Conversion into a rating system.

Isn’t those 2 actions different by nature/level ?

Thanks.


On Dec 4, 2017, at 0:23, Maciej Kula <notifications@github.com> wrote:

Have a look at this paper. The bottom line is: data on which items users choose to rate is much more important than the rating given. Hence, implicit recommender systems.

―

**Comment by maciejkula** [comment]
You can weigh those differently when fitting the model (using the `sample_weight` argument to the `fit` methods).

**Comment by arita37** [comment]
For time dependant features,
how the model recognize the 500 ‘virtual users’ into 100 users ?

Is user only recognize but his user feature ?
If 2 users having same feature, is it considered as same user ?

Thanks

**Comment by rwu1992** [comment]
Hi, I have a follow-up question on this. How do we build the interaction matrix in this case? For example, say a user purchased item 1 at time 1 and item 2 at time 2. Is my matrix simply [1,0] at time 1 and [0,1] at time 2? Or should it be [1,1] at time 2?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
