### ISSUE TITLE
Extend lightFm model to contextual-aware recommendation

### ISSUE THREAD

**Issue by robinsu** [lyst/lightfm#238]
We are looking forward some idea to extending lightFM model integrated online interaction events.
For example, once user browser specific product or watch specific music online, is it possible to combine user-item features and this specific item to build up new recommendation ranking?
Thanks a lot,
- Robin Su

**Comment by maciejkula** [comment]
LightFM has (1) user features and (2) item features, these are assumed to be constant over all interactions of that user and that item.

If you want to have contextual features (time-varying, or specific to a given interaction instance), you could integrate them in either user or item features. This way you would have more than one features row for a given user or item. For example, instead of having one row for item 10: `{'id': 10, 'category': 'foo'}` you could have two rows: `{'id': 10, 'category': 'foo', 'time-of-week': 'friday'}` and `{'id': 10, 'category': 'foo', 'time-of-week': 'tuesday'}`. With a little ingenuity in feature engineering you can make the model very flexible.

**Comment by altaha** [comment]
@maciejkula I'm trying to implement your suggestion above. As far as I can tell, you cannot have more than one set of features for a given user or item. So for your example, you cannot have two feature rows for item id 10... The only way I can think of is to create dummy item (or user) ids for each context. So then for your example the item features become:
`{'id': '10_friday', 'category': 'foo', 'time-of-week': 'friday'}` and `{'id': `10_tuesday`, 'category': 'foo', 'time-of-week': 'tuesday'}`
Which will also require that the interactions on item 10 to be split across item 10_friday and 10_tuesday

I think this is actually what you were suggesting, but I wanted to confirm that I have the right idea.

**Comment by FrancescoI** [comment]
> If you want to have contextual features (time-varying, or specific to a given interaction instance), you could integrate them in either user or item features. This way you would have more than one features row for a given user or item. For example, instead of having one row for item 10: `{'id': 10, 'category': 'foo'}` you could have two rows: `{'id': 10, 'category': 'foo', 'time-of-week': 'friday'}` and `{'id': 10, 'category': 'foo', 'time-of-week': 'tuesday'}`

Could it cause any trouble since rows won't be independent anymore?

**Comment by AakarSharma** [comment]
> LightFM has (1) user features and (2) item features, these are assumed to be constant over all interactions of that user and that item.
> 
> If you want to have contextual features (time-varying, or specific to a given interaction instance), you could integrate them in either user or item features. This way you would have more than one features row for a given user or item. For example, instead of having one row for item 10: `{'id': 10, 'category': 'foo'}` you could have two rows: `{'id': 10, 'category': 'foo', 'time-of-week': 'friday'}` and `{'id': 10, 'category': 'foo', 'time-of-week': 'tuesday'}`. With a little ingenuity in feature engineering you can make the model very flexible.

I tried this but it is giving this error
`TypeError: unhashable type: 'dict'`
@maciejkula Can you please tell what I am doing wrong here? I just added all the different features as a list and passed the tuple (user, list_feature) to dataset.build_user_features function.
