### ISSUE TITLE
Item - Item Recommandation + user feature

### ISSUE THREAD

**Issue by bsbor** [lyst/lightfm#239]
Hello,

I'm here to have your advice on the following.
My objective is to make item-item recommendation. (Recommend a list of products for a given product)
To do so I'm using the item embeddings (item_vectors = products['item_features'] * model.item_embeddings)

It is working like a charm.

But now, I want to have this  item-item recommendation adding a user feature, for example the sex. (ie : How can I have a recommendation for product X for for women)
Is it possible to do that in one model ? Or do I have to fit a model on female user and one on men users ?

Thanks in advance,

BsBor

**Comment by maciejkula** [comment]
You mean you want to have emeddings conditional on some other variable? I think you'll have to have separate models.

**Comment by italoPontes** [comment]
Are you using Item2Vec?

https://arxiv.org/abs/1603.04259

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
