### ISSUE TITLE
How to use predict function with feature matrix

### ISSUE THREAD

**Issue by Simon-KALIDO** [lyst/lightfm#240]
LightFM is indeed a great algorithm and I am using it for retailer to populate their marketing email content with personalised recommendations. However, there are several questions about "how to use predict function" of LightFM. 

1. I trained the model with user feature of (biographical data concat with identity matrix data) as you suggested in your notes. Train and test results turn out to be good. But when I do predictions, do I need to feed in exactly same user feature into the predict function? Can I simply use identity matrix (i.e. simply use None for user_features)? I guess this might be wrong.

2. I have large number of recommendations to be generated. When I use predict function with full user_features (biographical data concat with identity matrix data), the predict function is very slow and I cannot complete prediction within my preferred timeframe. Is this caused by the searching index against the coo matrix of user_features?

3. Is it possible to predict multiple users in one predict function? I tried this by explicitly feeding in user ids and item ids parameter by carefully build the np.array of (# users * # items) to ensure correct match. However, I found the prediction result is different from when I made predictions person by person. I think I should not predict multiple users in one predict function, right?

Thank you!
Simon

**Comment by maciejkula** [comment]
1. You need to pass in the feature matrix; these are not stored in the model object. This may make the model a bit harder to use, but allows you to _change_ the feature matrices.
2. The implementation complexity, both in training and in prediction, is linear in the number of nonzero features. I suggest you use the [`get_embedding`](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_item_representations) methods which give you the embeddings _given a fixed feature matrix_. Once you have them, making predictions is just a matter of a vector-matrix product between the user row and the item rows.
3. Yes, this is possible. The function accepts pairs of `(user_id, item_id)`. For example, passing `[1, 1, 2, 2]` for user_ids and `[1, 2, 1, 2]` will give predictions for `[(user_1, item_1), (user_1, item_2), (user_2, item_1), (user_2, item_2)]`.

**Comment by maffka123** [comment]
Hi @maciejkula,

I am trying now to predict for batch users, so I am using your suggestion above. Do I understand correctly, that in liпhtfm.py on the row 814: `n_users = user_ids.max() + 1` , meaning that if I will send users_ids  for the first batch, it will work, but starting from second not, because user_ids=[7,7,7,8,8,8] and features [1,2,3,1,2,3] will give n_users=9  and user_features.shape[0]=6 and throught an error "Number of user feature rows does not equal the number of users"
What am doing wrong?
