### ISSUE TITLE
Request for Opinion: User IDs which are not 32 bit integers

### ISSUE THREAD

**Issue by RAbraham** [lyst/lightfm#243]
Hi,
This is a request for advice if you have the time :).

LightFM and other libraries ask for a 32 bit integer id e.g for users. But, our user id is a UUID e.g. `0003374a-a35c-46ed-96d2-0ea32b753199`.  I was wondering what you would recommend in scenarios like these. What I have come up with is:
- Create a bidirectional dictionary either in memory or in a database to keep a UUID <-> Int mapping.  e.g. https://github.com/jab/bidict
- Use a non cryptographic hash function like MurmurHash3 or xxHash. I still have to test how bad the collisions would be for our dataset and it's impact in a real life scenario. If the collisions are minimal, maybe they could be used for recommendations?

Thanks,
Rajiv

**Comment by maciejkula** [comment]
Could you ask this question on StackOverflow and post a link here so that I could respond? That way more users can benefit from the response.

**Comment by RAbraham** [comment]
Absolutely. Here it is: https://stackoverflow.com/questions/48068147/recommender-systems-convert-uuids-to-32-bit-ints-for-recommender-libraries

Thanks a bunch.
