### ISSUE TITLE
Getting similar items

### ISSUE THREAD

**Issue by mstrauch** [lyst/lightfm#244]
Hi,
not really an issue. I am new to LightFM. Before I used implicit for generating recommendations but there was no build-in option for passing in user- / item-features.

Implicit defines a function on the model for getting similar items. Does adapting this function to LightFM work? I think I'm missing the theoretical background to see for myself.

```
def similar_items(self, itemid, N=10):
    scores = self.item_factors.dot(self.item_factors[itemid]) / self.item_norms
    best = np.argpartition(scores, -N)[-N:]
    return sorted(zip(best, scores[best] / self.item_norms[itemid]), key=lambda x: -x[1])
```

https://github.com/benfred/implicit/blob/master/implicit/als.py

**Comment by EthanRosenthal** [comment]
I believe the following should work with LightFM. One thing to note is that the similarity function below ignores the item biases that LightFM learns, but I think it should be suitable for generating sensible recommendations.

```python
def similar_items(item_id, item_features, model, N=10):
    item_representations = item_features.dot(model.item_embeddings)

    # Cosine similarity
    scores = item_representations.dot(item_representations[item_id, :])
    item_norms = np.linalg.norm(item_representations, axis=1)
    scores /= item_norms

    best = np.argpartition(scores, -N)[-N:]
    return sorted(zip(best, scores[best] / item_norms[item_id]), 
                  key=lambda x: -x[1])
```

**Comment by maciejkula** [comment]
This is correct. You can also use the `get_<user/item>_representations` methods to get the latent representations: http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_item_representations.

**Comment by mstrauch** [comment]
Hi,

thanks for your help.
Unfortunately the function returns some nan values along with this warning:

```
RuntimeWarning: invalid value encountered in divide
[(39022, nan), (36609, nan), (39031, nan), (36614, nan), (39036, nan), (36613, nan), (39037, nan), (39039, nan), (39041, nan), (39169, nan)]
```
There seem to be some nan values in scores after dividing by item_norms. Do you have some idea?

**Comment by mstrauch** [comment]
Figured it out: We have to replace zero values with very small numbers before dividing:

```
item_norms[item_norms == 0] = 1e-10
```

Here the full code again:

```
def similar_items(item_id, item_features, model, N=10):
    (item_biased, item_representations) = model.get_item_representations(features=item_features)
    # Cosine similarity
    scores = item_representations.dot(item_representations[item_id])
    item_norms = numpy.linalg.norm(item_representations, axis=1)
    item_norms[item_norms == 0] = 1e-10    
    scores /= item_norms
    best = numpy.argpartition(scores, -N)[-N:]
    return sorted(zip(best, scores[best] / item_norms[item_id]),
                  key=lambda x: -x[1])
```


Thank you very much for your support!

**Comment by maciejkula** [comment]
Yes, that would work.

I would suggest that having 0 norms is a symptom of a problem with your model. Do you have any user/item vectors you don't use? Does your feature matrix have rows with all zeros? Is your regularization too large?

**Comment by mstrauch** [comment]
You are right. I had rows of zero values in my feature matrix. No need for replacing zero values any more! Thanks.

**Comment by lesterlitch** [comment]
I'm not sure why you're using item norms here - doesn't scaling a vector not affect it's angle and therefore shouldn't affect the cosine distance? But then my recommendations come out different using this method (and better).

How come?

**Comment by JanKCZ** [comment]
Hi, hope you can help me with my question. I have applied the method from above, but I get terrible results for similar items (videos). If I compare the results with Implicit, with same dataset, the results are unusable (which I am pretty sure I am doing something wrong...). And sometimes I don't even get all the 20 similar items, but much less.

`def get_similar_items(video_id, N=20):
    item_representations = model.get_item_representations()[1]

    internal_idx = dataset.mapping()[2][video_id]

    # Cosine similarity
    scores = item_representations.dot(item_representations[internal_idx, :])
    item_norms = np.linalg.norm(item_representations, axis=1)
    scores /= item_norms

    best = np.argpartition(scores, -N)[-N:]
    return sorted(zip(best, scores[best] / item_norms[internal_idx]),
                  key=lambda x: -x[1])`
