### ISSUE TITLE
Access metadata

### ISSUE THREAD

**Issue by kristopheles** [lyst/lightfm#248]
I'm not quite sure if it's the right place to ask, but:

Is where a way to access the metadata of a recommended movie and it's score?
E.g. so you can create an object that contains genres, name and calculated score of the user/s?

**Comment by maciejkula** [comment]
I changed your wording from 'excess' to 'access', which is probably closer to what you mean.

When using a fitted model to predict, you will get the score. You need to keep track of everything else yourself.
