### ISSUE TITLE
Cannot find plugin 'liblto_plugin.so'

### ISSUE THREAD

**Issue by oddskool** [lyst/lightfm#25]
Hi,

When trying to compile the software on Mac OS X (Yosemite) with GCC installed with brew I get the following error:
```bash
14:35 $ python setup.py install
...
building 'lightfm.lightfm_fast' extension
gcc-ranlib-4.9 -fno-strict-aliasing -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/Users/e/Anaconda/anaconda/envs/py3k/include -arch x86_64 -I/Users/e/Anaconda/anaconda/envs/py3k/include/python3.3m -c lightfm/lightfm_fast.c -o build/temp.macosx-10.5-x86_64-3.3/lightfm/lightfm_fast.o -fopenmp -march=native -ffast-math
gcc-ranlib-4.9: Cannot find plugin 'liblto_plugin.so'
error: command 'gcc-ranlib-4.9' failed with exit status 1
```

I cannot find any liblto_plugin.so or liblto_plugin.dlyb on my system.

I tried to `brew install llvm` and `conda install llvmpy` but with no success :(

Any hint on how to fix that  ?

**Comment by maciejkula** [comment]
Could it be because you're trying to link to the Anaconda version of python? This should not be related to llvm at all.

Can you try using a non-Anaconda python installation?

**Comment by maciejkula** [comment]
You can also try #24 and see if that solves your issue.

**Comment by oddskool** [comment]
Ok, #24 fixed part of the problem, however I had to modify the CXX flags to get it to compile:

```
-                                          '-march=native',
+                                          '-march=corei7',
```

Otherwise gcc complains about unknown asm instructions (e.g. `no such instruction: vmovsd 16(%rdi), %xmm0`).

It's a bit odd since native architecture should be detected as corei7 I presume.

**Comment by maciejkula** [comment]
Are you using the anaconda python distribution? I can only suppose that could be part of the problem.

**Comment by oddskool** [comment]
Yes I do. 

Trying to compile with the brew python (2.7.9) in the path instead of the Anaconda one still triggers the "no such instruction" error.

So it seems that the error may be more related to something else (cpu architecture detection maybe?).

The gcc command with brew python:
```bash
gcc-4.9 -fno-strict-aliasing -fno-common -dynamic -I/usr/local/include -I/usr/local/opt/sqlite/include -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -I/usr/local/Cellar/python/2.7.9/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c lightfm/lightfm_fast.c -o build/temp.macosx-10.9-x86_64-2.7/lightfm/lightfm_fast.o -fopenmp -march=native -ffast-math
```

Output of `uname -a`:
```
Darwin 14.4.0 Darwin Kernel Version 14.4.0: Thu May 28 11:35:04 PDT 2015; root:xnu-2782.30.5~1/RELEASE_X86_64 x86_64
```

This is a MacBookAir under Yosemite.

At this point I managed to get past the issue and I believe it is likely related to a library or configuration you use, so maybe a sensible thing to do is to keep this thread for other users...

**Comment by oddskool** [comment]
Indeed, `gcc`'s native arch seems to be x86_64:

```bash 
$ /usr/local/bin/gcc-4.9 -dumpmachine    
x86_64-apple-darwin13.4.0
```

**Comment by maciejkula** [comment]
I see. Could you have a look at https://github.com/lyst/lightfm/pull/26?

It might fix the problem, according to http://stackoverflow.com/questions/9840207/how-to-use-avx-pclmulqdq-on-mac-os-x-lion/19342603#19342603

**Comment by oddskool** [comment]
with #26 same "no such instruction" error :(

**Comment by maciejkula** [comment]
I got hold of a mac and will try to reproduce your problem.

**Comment by maciejkula** [comment]
It is a problem with the Anaconda distribution. I have updated #26 to automatically drop `-march=native` whenever we know we're dealing with anaconda. This should finally fix it!

**Comment by oddskool** [comment]
Yes it works on my setup :+1:

**Comment by maciejkula** [comment]
Perfect, thanks for your help!
