### ISSUE TITLE
Explaining Recommendations

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [lyst/lightfm#251]
Hi,

What is the best way to get the explanation why lightfm recommend item-j for user-i?
The kind of explanation that I mean is, for user-i, you are recommended item-j, because in the past you interacted with item-a, item-b, ... .

**Comment by maciejkula** [comment]
You can try using item similarity to do that present support for your recommendations. For example, you could use cosine similarity between the embedding of the item you are recommending and items that the user has interacted with in the past to find items from the user's history that are most similar to the recommendation you are making.

**Comment by novan-p-simanjuntak** [comment]
@maciejkula, thanks for your explanation. I will try it.
