### ISSUE TITLE
Training Data

### ISSUE THREAD

**Issue by dalalkrish** [lyst/lightfm#252]
Hello Maciej,

This is an amazing package to have a recommender system up and running. Here is where I am trying to apply your package's hybrid recommendation solution. I have ten 'one-hour time blocks' and I want to recommend them for the 'contacts' based on their profile (equivalent to user-profile). Some contacts have been called before and some not. Contacts profile can be like "job role", "account size" and "time zone". I can see this is kind of similar to you Movie Recommendation example with the only change is that I have only ten 'one-hour block'. So I following question:
1) Do you think the hybrid solution is suitable here
2) Can you please post the training data so that I can structure my sparse matrix that captures contacts meta-data?

Will really appreciate your guidance. Thank you.

**Comment by maciejkula** [comment]
1. It could be --- I don't really have enough information to say. What is the purpose of your system?
2. It's your training data, so not sure I can post it :) What sort of trouble do you have with building the feature matrices?

**Comment by dalalkrish** [comment]
1. Purpose of my system is to rank the ten one-hour block in the order of highest likelihood for a contact to answer the call.

2. I am asking to post the feature matrices of the example you have posted along with the package. I'm struggling to understand how to structure feature matrices with the features that describe a 'contact' and his previously answered call preferences. Does this help you to understand y problem? :)

**Comment by maciejkula** [comment]
The features matrices of the Movielens and Stackoverflow datasets are available through the dataset fetching functions, as per the [documentation](https://lyst.github.io/lightfm/docs/datasets.html). Have a look at those and see if that helps.
