### ISSUE TITLE
Non binary implicit interaction value

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [lyst/lightfm#260]
Hi @maciejkula , thanks for LightFM. It has been really helpful.

I have some questions regarding value in user-item interaction matrices,
I want to create the recommender system with implicit feedback.
I see the examples in github (CrossValidated) and found that the value in user-item interaction matrices with implicit feedback is binary (1/0).
Can I use random number to represent interaction value?
This is because I must handle multiple interaction.
Say there are only only 2 interactions, (view and comment) and I use the following formula to get the value interaction of user-i and item-j.
`R(i,j) = 1/3 * view + 2/3 * comment`
Comment coeeficient is bigger than view since it's important to optimize comment than view.
Based on above formula, there is a chance that the interaction value is not a binary (e.g, if the user only view, the value of matrices[i,j] is 0.33).

My questions are:

1. Can the value of interaction a floating number (not a binary)?
2. Can I actually use above approach represent multiple implicit interaction?
3. Is this the best approach to represent multiple implicit interaction?

Thank you.

**Comment by maciejkula** [comment]
You can use the `sample_weights` [argument](https://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.fit) to weigh the importance of individual interactions.
