### ISSUE TITLE
Non binary User/Item features

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [lyst/lightfm#261]
Hi @maciejkula , thanks for LightFM, it has been really helpful.

I have some questions regarding user/item features representation.
I see CrossValidated example and the tag/item features representation is binary (E.g, if item has tag 'bayes' the value is 1, 0 otherwise).

My questions are:
1. Can I use numerical value (non binary) to represent item features?
E.g, I want to use user age, since this is not a categorical attribute, I want to use normalized numerical value (0-1), 0 means age 0, 1 means age 100. Is this possible?

2.  if point 1 is not possible, how can I represent numerical item features? 

Thanks.

**Comment by maciejkula** [comment]
Yes. However, the values should be normalized, and must not be large. In practice you may find that discretization works better.
