### ISSUE TITLE
Is Light FM suitable for one-class recommends?

### ISSUE THREAD

**Issue by skurzhanskyi** [lyst/lightfm#263]
Maybe this question has not to be in the issues, but I would like to ask if Light FM is suitable for one-class recommends? I mean if I have only rating 1 and that's all. For example, I have page information with user-page interaction. There's no rating, just the fact user was on this page or not.

Maybe, you have an idea about this?

Thanks a lot

**Comment by maciejkula** [comment]
This is, in fact, the primary purpose of LightFM. In the literature, this is referred to as _implicit feedback_.

**Comment by skurzhanskyi** [comment]
Oh, thanks, I'm a newbie to recommender system for now and more familiar with `one-class` term.
Once more question: If I have user/item model, can I show the most similar items for my chosen one.
Because I want to show similar items for an item depending on that item and user, who's on this page.

Thanks again

**Comment by skurzhanskyi** [comment]
Ok, I read all the issues and understood a big part of the points. But I have 1-2 questions, I'll ask it as the new issue.
