### ISSUE TITLE
Get item recommendation for a particular user on a particular item page

### ISSUE THREAD

**Issue by skurzhanskyi** [lyst/lightfm#266]
I still have some questions. But it looks more I need your advice.

I have user-item interactions and item features. I want to build a model that recommend items for a particular user on a particular item page. (users always on some items pages)

1. For a new user, it seems that it's better to recommend just similar objects. Is it better to build item-item model or just use `similar_items` from #244?

2. Main question: do you have any idea how to get item recommendation for a particular user on a particular item page. Maybe it's better to combine item similarity and user recommendation? 

Thanks a lot!

**Comment by maciejkula** [comment]
1. Try it and let me know!
2. Yes, that's a decent option and one that I've used in the past.

**Comment by maciejkula** [comment]
Hope this helped. Let me know if you have any further questions!

**Comment by skurzhanskyi** [comment]
Cosine similarity on item embeddings really worked well and was, actually, better than this similarity on item-user matrix. Thanks a lot!

**Comment by navido89** [comment]
@skurzhanskyi I am trying to solve the same problem as you. Were you able to get item recommendations for a particular user on a particular item page? I am interested in learning more about your suggestion on how to combine item similarity and user recommendation. Do you have any code examples on you? Thanks in advance.
