### ISSUE TITLE
Item features in get_movielens_item_metadata()

### ISSUE THREAD

**Issue by tdeboissiere** [lyst/lightfm#27]
In the get_movielens_item_metadata() function (lines 114 to 123)
=> the item id are added to genres but the genre index may overlap with the movie_id
Example : if movie has movie_id 3 but also genre 3,  there is no distinction between genre 3 and movie_id3

Is this intended ?

**Comment by maciejkula** [comment]
You are right, that will be the case for movies up to 18 (as there are 18 genres).

No, this is not intended. I'll have a think about whether this is worth fixing.
