### ISSUE TITLE
weight matrix changes after fit

### ISSUE THREAD

**Issue by tkernr** [lyst/lightfm#272]
I have noticed that the entries of the weight matrix can change after the fit as compared to the original.
Here is a toy example. 

a = csr_matrix([[1, 0, 0, 1], [0, 0, 1, 1], [0, 1, 0, 1], [0, 1, 0, 0]])
w = csr_matrix([[0.1, 0, 0, 0.1], [0, 0, 0.1, 0.1], [0, 0.1, 0, 0.1], [0, 0.1, 0, 0]])
w1 = w.tocoo()

w1.nonzero()
(array([0, 0, 1, 1, 2, 2, 3], dtype=int32),
 array([0, 3, 2, 3, 1, 3, 1], dtype=int32))

model = LightFM(no_components=2)
model.fit(a, epochs=10, sample_weight=w1, num_threads=1)

w1.nonzero()
(array([0, 2, 3, 1, 0, 1, 2], dtype=int32),
 array([0, 1, 1, 2, 3, 3, 3], dtype=int32))

On the other hand, if the weight matrix is defined as
w1 = coo_matrix([[0.1, 0, 0, 0.1], [0, 0, 0.1, 0.1], [0, 0.1, 0, 0.1], [0, 0.1, 0, 0]])
instead, its form seems to be preserved.

Why does the first approach not work? 
Any help is much appreciated. Thanks a lot.

**Comment by maciejkula** [comment]
Hint: when reporting issues, use proper code formatting (have a look at [the guide](https://guides.github.com/features/mastering-markdown/)).

**Comment by maciejkula** [comment]
Hint number 2: if you have a snippet of code that reproduces your problem, try to make it runnable. In your case, I had to add imports etc etc.

**Comment by maciejkula** [comment]
This happens because of dtype conversions inside LightFM (using scipy's `astype` operations). The order of the entries changes, but the matrix remains unchanged.

Having said this, I don't like that `astype` changes the original matrix: this should not be happening. I will be making a pull request moving away from the `astype` call.

**Comment by maciejkula** [comment]
https://github.com/lyst/lightfm/pull/279
