### ISSUE TITLE
Upper Bound and Lower Bound Value for Prediction Score.

### ISSUE THREAD

**Issue by novan-p-simanjuntak** [lyst/lightfm#273]
Hi @maciejkula , thanks for LightFM, it has been really helpful.

I have some questions regarding boundary value for prediction. I read your paper about lightfm. In that paper, you use sigmoid function to predict score for user-i and item-j, so its value must be be between 0 and 1,  but after I tried to predict the score using lightfm, it seems there is no exact boundary value, (e.g, prediction score is 5.5) and sometimes the prediction score is negative (e.g, -3.2). 

Is there upper bound and lower bound for lightfm scores?
The reason is because I want to try ensemble model where one of the model is lightfm.

Thank you.

**Comment by maciejkula** [comment]
No, there is no upper or lower bound. If you're ensembling with tree-based methods, you should be fine; otherwise, you may want to employ some sort of scaler.

**Comment by novan-p-simanjuntak** [comment]
@maciejkula , thanks, I will try tree-based methods.

What scaler do you think is good?
I am thinking of using  sigmoid function to scale the result between 0 and 1.

**Comment by maciejkula** [comment]
That may work, but I would double check that the sigmoid doesn't saturate too much.

**Comment by novan-p-simanjuntak** [comment]
@maciejkula , thank you.

**Comment by maciejkula** [comment]
No problem.
