### ISSUE TITLE
Can lightfm be used in pyspark RDD-based for distributed clusters in big data framework?

### ISSUE THREAD

**Issue by viciaky** [lyst/lightfm#274]
Hi , i noticed that in Spark Mlib RDD-based API only have Collaborative Filtering(ALS) for building recommendation engine. And i want to use this fantastic lightfm in pyspark, but i am not sure how to use it in terms of RDD-based. Does that mean i should modify lightfm source code to fit with RDD configuration?
Can you give me some advice on that? 
Thank you very much~! : )

**Comment by maciejkula** [comment]
LightFM accepts sparse matrices as input. If you can convert an RDD into a sparse matrix, you should have no problem using LightFM.

I do not myself use Spark so I will not be able to offer help.
