### ISSUE TITLE
Parameter to indicate explicit or implicit feedback

### ISSUE THREAD

**Issue by bdqnghi** [lyst/lightfm#277]
I want to ask if there is a parameter to indicate that this is an explicit or an implicit model.

Something like: 

model = LightFM(no_components=30)
model.fit(data, epochs=20, model=explicit)

Is there such parameter in the current version? Or it's in the future work? If not, how can tell LightFM that this dataset is an implicit or explicit one?

Thanks :)

**Comment by maciejkula** [comment]
The WARP and BPR losses are implicit feedback. Logistic is explicit.

Explicit feedback algorithms perform very poorly. I would suggest not using them.

**Comment by bdqnghi** [comment]
I see, thanks 👍
