### ISSUE TITLE
importing lightfm in project

### ISSUE THREAD

**Issue by AkibSadmanee** [lyst/lightfm#278]
Hello,
I have a python3 project and I have installed lightfm with pip3
`$ pip3 install lightfm `
and importing it like this

**from lightfm import LightFM
from lightfm.datasets import fetch_movielens**

but when I run the project I get the following error. 

Traceback (most recent call last):
  File "/home/akib/.local/lib/python3.6/site-packages/lightfm/datasets/movielens.py", line 171, in fetch_movielens
    item_metadata_raw, genres_raw) = _read_raw_data(zip_path)
  File "/home/akib/.local/lib/python3.6/site-packages/lightfm/datasets/movielens.py", line 17, in _read_raw_data
    with zipfile.ZipFile(path) as datafile:
  File "/usr/lib/python3.6/zipfile.py", line 1108, in __init__
    self._RealGetContents()
  File "/usr/lib/python3.6/zipfile.py", line 1175, in _RealGetContents
    raise BadZipFile("File is not a zip file")
zipfile.BadZipFile: File is not a zip file

During

 handling of the above exception, another exception occurred:

Traceback

 (most recent call last):
  File "movie_recomend.py", line 15, in <module>
    data = fetch_movielens(min_rating=5.0)
  File "/home/akib/.local/lib/python3.6/site-packages/lightfm/datasets/movielens.py", line 177, in fetch_movielens
    raise ValueError('Corrupted Movielens download. Check your '
ValueError: Corrupted Movielens download. Check your internet connection and try again.

**Comment by maciejkula** [comment]
There is a hint in the error message! What steps did you take to try to fix it?

**Comment by AkibSadmanee** [comment]
Thanks for your response.
I cloned the repository and tried to install it through that. But got the same result 
and I am new to python, trying to learn it for data science, So I suppose I am not getting the hint from the error.

**Comment by maciejkula** [comment]
```
ValueError: Corrupted Movielens download. Check your internet connection and try again.
```

This suggests that when the package tried downloading the dataset, the download failed. It should recover automatically, otherwise find the file (in the `lightfm_data` directory in your user directory), delete it, and try again.

Also, when reporting an issue, please use proper code formatting (have a look at the [guide](https://guides.github.com/features/mastering-markdown/)).

**Comment by AkibSadmanee** [comment]
Thank you very much.
and Sorry for that. Will have a look at the guide right away.

**Comment by maciejkula** [comment]
No worries. Did you manage to get it working?

**Comment by AkibSadmanee** [comment]
yes. thanks to your help
