### ISSUE TITLE
not all multiple cores ran in prediction stage

### ISSUE THREAD

**Issue by jellchou** [lyst/lightfm#283]
I have a machine with 16 physical cores. When in training time, I set the num_threads as 16, all cpus would run.
While came into the prediction, I also set the num_threads as 16, only 6 cpus ran.

**Comment by maciejkula** [comment]
How did you measure this? It sounds unlikely: the same code is used for both paths. My suspicion is that if you used something like `top`, your prediction job doesn't actually spend enough time in the multithreaded routines for an eyeball test like this to work.

**Comment by jellchou** [comment]
Yes, I used `top` to measure this. In prediction stage, the CPU usage is always slightly smaller than 600%.  Maybe each prediction job doesn't need to fully occupy the cpu.

**Comment by maciejkula** [comment]
I think that's probably what is happening. I'm going to close this for now, but please let me know if you hit any further problems.
