### ISSUE TITLE
How to deal with on-the-fly new user and new item recommendations?

### ISSUE THREAD

**Issue by bdqnghi** [lyst/lightfm#284]
According to the examples that I have seen in the documents, it seems like when a new user come in, we have no way to recommend the item to him on-the-fly but to retrain the whole models with additional information of such user or item. Is there any solution for this that currently available in LightFM?

**Comment by maciejkula** [comment]
You can recommend items to new users as long as you have metadata features for that user that were also present in the training set. You do this by constructing appropriate feature matrices.

If you are introducing new features, you will have to retrain the model to create embeddings for them.

**Comment by maciejkula** [comment]
Hope this helped. Let me know if you have any further questions!

**Comment by adrianob** [comment]
Hi @maciejkula , I'm having the same problem but I'm still at a loss about what to do.
I'm using LightFM as a simple Collaborative filtering model for now, so I only train it with user ids and item ids. If I try to predict a new item or user that wasn't in the training set I get a ```The user feature matrix specifies more features than there are estimated feature embeddings``` error.
My problem is that whenever a new user rates an item I want to show recommendations immediately, so retraining the whole model which takes almost 10 seconds is too slow. Is there any better solution?

**Comment by maciejkula** [comment]
I would suggest periodic (say, daily) retraining of the model.

**Comment by maciejkula** [comment]
I am working on other models that react to new information in real time, but they are not ready yet.

**Comment by maciejkula** [comment]
@vghiya06 Yes. You can use them in [Rust](https://github.com/maciejkula/sbr-rs) or [Go](https://github.com/maciejkula/sbr-go).

**Comment by hammadkhann** [comment]
Kindly make it for python please.

**Comment by oumaymalajili** [comment]
Hi , is anyone found a solution for this problem ?

**Comment by kshitijyad** [comment]
@maciejkula any implementation in Python ?

**Comment by johannb75** [comment]
@maciejkula  Have you done it for python? It would be helpful for a lot of people. Thanks
