### ISSUE TITLE
predict_ranks returns non-unique ranks when test and train have samples in common

### ISSUE THREAD

**Issue by artdgn** [lyst/lightfm#287]
Not sure if you consider this an issue but, if data source contains duplicates (and the user does not remove them) they might get into both train and test set. This would be bad enough, but an additional problem with that is that when running `predict_ranks` and supplying `train_interaction` to ignore, the returning ranks are non unique (e.g `[0, 0, 0, 1, 1, ...]`), which makes evaluation even more optimistic (on top of being methodically incorrect because of duplicates). 
Although it's the user's fault, the ranks shouldn't be non-unique (and optimistic). In any case, both problems may be solved by raising an error or a warning if an intersection of test and train is detected in `predict_ranks`. Would you accept a PR for that?

Code to reproduce:

```
import scipy.sparse as sp
import numpy as np

from lightfm import LightFM
lfm = LightFM()

train_mat = sp.csr_matrix(np.concatenate([np.ones((6,3)), np.zeros((6,3))], axis=1))
print(train_mat.toarray())

test_mat = sp.csr_matrix(np.concatenate([np.zeros((6,2)), np.ones((6,4))], axis=1))
print(test_mat.toarray())

lfm = lfm.fit(train_mat)

ranks = lfm.predict_rank(test_mat)
# without training exclusion ranks are unique
print(ranks.tolil().data)

# when trying to exclude training ranks have duplicates
ranks_no_train = lfm.predict_rank(test_mat, train_interactions=train_mat)
print(ranks_no_train.tolil().data)
```

**Comment by maciejkula** [comment]
Thank you for the report! How do you propose to check for the intersection?

**Comment by artdgn** [comment]
how about:
```
def number_of_intersections(mat_a, mat_b):
    return np.sum((mat_a.astype(bool).multiply(mat_b.astype(bool))).tocsr().data)
```
seems pretty quick on my data:
```
>>>mat
<707181x334671 sparse matrix of type '<class 'numpy.float64'>'
	with 11400380 stored elements in Compressed Sparse Row format>
>>>test_mat
<707181x334671 sparse matrix of type '<class 'numpy.float32'>'
	with 180605 stored elements in Compressed Sparse Row format>
>>>ts = time.time(); print(number_intersections(mat, test_mat)); print(time.time() - ts)
0
0.06684756278991699
>>>ts = time.time(); print(number_intersections(mat, mat)); print(time.time() - ts)
11400380
0.1686718463897705
```

**Comment by maciejkula** [comment]
Cool, this sounds fine. Could we make this an exception-throwing check that is disableable via a flag?

**Comment by artdgn** [comment]
Sure, I'll make a PR.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
