### ISSUE TITLE
Use of WARP for display adverstising

### ISSUE THREAD

**Issue by kunalkishore87** [lyst/lightfm#288]
Hi Maciej,

I'm here not for an issue but to have your advice on the following. Please bear with me.
I work in the re-marketing domain of Inmobi, a mobile ad-network. I am trying to solve recommendation problem for cold-start users. I wish to use lightFM, which I think is a really great project you have released in open-source.

Historical data I have: 
- supply+context+user features; eg: publisher, ad slot, day of week, user handset details, user's derived features etc. Hence forth these features will be referred to as Uf
- demand features ie features of items whose ads were shown; eg: brand, category, price, discount etc. Hence forth these feature will be referred to as Vf
- metric: CTR (clicks/impressions shown)
- Hence the data format is: Uf*Vf matrix of partially filled CTR values. 
- Note that user ids are not available. Only features are available.

Objective: 
- Show the most relevant product to the user. Prediction at user level is difficult due to latency issues. Hence Uf represent user type and Vf act as item type. Thus the refined objective is: show the most relevant item type to a user type. Traditional methods used are CTR prediction using classification models. 
- Once the best item type is selected for a given user type, we can choose ads of most popular items in that item type cohort to show to this user type. 

Two approaches I have thought of:
1. Use implicit matrix factorization using ALS/SGD, where implicit score = CTR and confidence = #impressions. In my understanding, this will give results similar to traditional classification methods. Eg: http://blog.ethanrosenthal.com/2016/10/19/implicit-mf-part-1/
2. Learning to rank using WARP loss. Intuitively this should given better results as we are concerned with only top k recommendations for each user type. eg: http://blog.ethanrosenthal.com/2016/11/07/implicit-mf-part-2/

Question I am struggling with, while trying to use lightFM:
1. Are there any flaws in above approaches? 
2. In the 2nd approach, how do I model the CTR matrix into implicit preference matrix? Is there something like "confidence" which can be incorporated? (just like in 1st approach)
3. My data doesn't have user id. Can I still employ any of the above approaches using lightFM? In my understanding, I can feed above Uf*Vf matrix as user*item matrix input to lightFM package and that should be fine?

It will be great if you guide me w.r.t. the above approaches and questions. Any other suggestion is most welcome as well.

Thank You 
Kunal Kishore

**Comment by maciejkula** [comment]
This sounds roughly right, I think what you suggest would work. You can use interaction weights to express confidence.

If you'd like more detailed information please drop me an email at `lightfm@zoho.com` and I'd be happy to talk more about your specific application.
