### ISSUE TITLE
lightfm not installing.

### ISSUE THREAD

**Issue by ravijoe** [lyst/lightfm#290]
so i am trying to make a movie recommendation system using lightfm . 
there are a couple of issue . first- the import lightfm wont work.
second - pip install lightfm wont work. 
third- i downloaded the python implementation( https://github.com/lyst/lightfm )but confused on how to work with that . any ideas ?

**Comment by maciejkula** [comment]
How does `pip install lightfm` not work?

(When asking questions, try to provide as much detail as you can. It will let me help you more quickly.)

**Comment by ravijoe** [comment]
i dunno there's this error .i am facing this issues also while importing modules directly from pycharm for example matplotlib etc .i'll also attach a screenshot
![capture](https://user-images.githubusercontent.com/29393328/39571020-c8320cec-4ee7-11e8-8b41-dd540fd7d1a4.JPG)

**Comment by maciejkula** [comment]
Follow this [guide](https://blogs.msdn.microsoft.com/pythonengineering/2016/04/11/unable-to-find-vcvarsall-bat/) or try installing from [Conda](https://anaconda.org/conda-forge/lightfm).
