### ISSUE TITLE
Role of user_features and item_features

### ISSUE THREAD

**Issue by simon19891101** [lyst/lightfm#296]
Hi Maciej,

Appreciate your contribution! I'm just trying to get a better understanding about the role of the input user_features and item_features: How are they involved during the training process? In the code they seem to be multiplied with the embeddings that come from matrix factorization, and eventually added up (as shown in the paper)? Please correct me if I'm wrong. Looking forward to hearing from you.

Many thanks.

**Comment by maciejkula** [comment]
The model estimates the embeddings for user and item features (via matrix factorization), then uses their elementwise sum as representations for whole users and items. Those summed representations are then combined via inner products to yield user-item scores.

**Comment by simon19891101** [comment]
Hi Maciej, thanks very much for replying. The overall workflow sounds pretty clear however I was wondering what happens if we pass an user-defined use_feature/item_feature rather than 'None' to the fit function? Please feel free to leave comments if I'm fundamentally wrong in understanding the logic. Cheers.

**Comment by simon19891101** [comment]
Hi Maciej, I just figured out how it works! There was a trivial mistake made when tired to undertsand the logic. Thanks.

**Comment by maciejkula** [comment]
:+1:
