### ISSUE TITLE
Inappropriate results of prediction for New Items

### ISSUE THREAD

**Issue by vndkmr** [lyst/lightfm#298]
Hi, thanks for developing such a wonderful library.  Below are the details of my data and hyperparameters.
1. Interaction Matrix (12982 X 47200)
2. User Features (12982 X 14567) 
3. Item Features (47200 X 48312)
User and Item features includes per user ad per item identity matrix respectively.
Fitted the model and got Percision@10 = 0.21 and AUC = 0.93, which seems great!!. Now, I have some confusion as following:
In my case I have like, I get 30 new items daily and removed them in 2-3 days. How to solve this huge Cold Start Problem. I have used the model to get the prediction but those are not much promising.Do I need to retrain the model periodically or this model can help in this scenario?

**Comment by maciejkula** [comment]
It should help if the new items are described by the features you used in training.

You will need to construct a new feature matrix containing the new items. After that, you should be able to get reasonable predictions for them.

(You will still want to occasionally retrain the model.)

**Comment by vndkmr** [comment]
Thank you !!
One last question I have is, for these 30 new items do I need to append these in item features matrix used during training and then give the proper indices in predict function or just create the new feature matrix for the items from 0 to 29 (note :  sharing the same features as in training set) and pass the item ids as 0 to 29 and item_features as [0..29 X no of features]?

As per I know LightFM, in predict function userid and itemid are just the indices in teh user and item feature matrices passed in predict function? Am i correct? If this is the case, then just I need to create the new matrix sharing the same features and run the prediction.
If new feature comes in, then I need to retrain the whole model.

**Comment by maciejkula** [comment]
Create the new feature matrix and give the items ids from 0 to 29 is the best option. 

Yes, you are exactly correct: they are simply indices, and you need to retrain when new features come in.

**Comment by EricC91** [comment]
I am in the same situation as vndkmr.
But I have a supplementary question: 
I would like to predict recommendations for items that are in the training set but also new items.
How I can do this ?

I think append features of new items to the training matrix is the best choice ? No ?
But there is no function to add features with your Dataset object...

**Comment by rabindra-c24** [comment]
@maciejkula can we score item based on item status or category . suppose some of my items are "reserved" so how do we score less those item compare to other item.
