### ISSUE TITLE
Problem with Item Features in Lightfm

### ISSUE THREAD

**Issue by gomayank** [lyst/lightfm#304]
@maciejkula 
Hi
I was trying to use LightFM for a college project.
I'm giving the model a item features matrix and user features matrix and interaction matrix
I can train my model with model.fit(train,epochs=5,num_threads=4, user_features=user_features,item_features=item_features), where train contain my interaction data matrix and item_features my item features matrix
After I train, if I want to predict something I get the following error:
Predict Function:-
 model.predict(
                        uid_array,
                        pid_array,
                        user_features=userFeatures,
                        item_features=TestingData,     #test property features.
                        num_threads=7)
ValueError: The user feature matrix specifies more features than there are estimated feature embeddings: 19378 vs 445918.

Do I need to feed in exactly same user and item feature matrix into the predict function as I used for the
training purpose ??

What can be causing this?

**Comment by maciejkula** [comment]
Can you please format your issue using Github Markdown? The code is hard to read.
