### ISSUE TITLE
sample weight's range

### ISSUE THREAD

**Issue by aldll** [lyst/lightfm#306]
Hi,
My question is the range of values in sample_weight matrix has any restrictions or rules?
I saw the parameter explanation said the default is 1, so first I tried range (0, 1] and the prediction changes ideally. Then I tried range [1, 100], but the prediction seems not change.

Could you tell me the range for sample_weight and how this weight work in latent embedding? Many Thanks!

**Comment by maciejkula** [comment]
The sample weights basically scale the learning rate up (above 1) or down (below 1) for a particular sample. Obviously, it doesn't make sense for this to be less than zero; similarly, I think very large values will make the model diverge.

**Comment by aldll** [comment]
Thanks for your reply.
I know the value should be > 0, so I want to set each sample_weight value start with 0.01 and if user take some actions(like, click many times etc), add up this value, but maximum is 1. Is this setting make sense?

**Comment by maciejkula** [comment]
That sounds sensible!

**Comment by aldll** [comment]
Got it! I'm very grateful for your help. Thank you!
