### ISSUE TITLE
Bug on data builder ??

### ISSUE THREAD

**Issue by EricC91** [lyst/lightfm#308]
Hi,

Thanks to release a data builder !!
I run your example of it and after this code :

```
from lightfm.data import Dataset

dataset = Dataset()
dataset.fit((x['User-ID'] for x in get_ratings()),
            (x['ISBN'] for x in get_ratings()))
```

If I do a :
`print(dataset.item_features_shape())`
It return : 
`(340553, 340553)`

It's normal than nb_feature = nb_items, It will not be 0 ?

Same things on user features...

Thanks

**Comment by maciejkula** [comment]
This is the desired behaviour (have a look at the [docs](http://lyst.github.io/lightfm/docs/lightfm.data.html#lightfm.data.Dataset)). The idea is that, by default, a feature is allocated for every item and every user.

(Please have a look at [this guide](https://guides.github.com/features/mastering-markdown/#) to learn to format code in issues correctly.)

**Comment by EricC91** [comment]
Ok 
I didn't see the parameters of the Dataset Class.
Sorry for the inconvenience.
