### ISSUE TITLE
New lightFM usage example

### ISSUE THREAD

**Issue by tdeboissiere** [lyst/lightfm#31]
Hi,

I have written a quick [ipython notebook example](https://github.com/tdeboissiere/Kaggle/blob/master/Ponpare/ponpare_lightfm.ipynb) where I used lightFM in the Kaggle [RECRUIT Ponpare competition](https://www.kaggle.com/c/coupon-purchase-prediction).

The goal of the competition was to predict user purchase on a specific week given a year of training data (log of purchase and visit). 

This naturally fits into the lightFM hybrid recommendation paradigm : implicit feedback data with user and item metadata

If that fits you, I can create a new pull request to add it to your example section.

Cheers

**Comment by maciejkula** [comment]
Yes, that sounds great! What were your results?

I think the notebook will need a bit of clean-up (for instance, I'd like to have utility functions that do all the data download/directory creation automatically; I'd also like the code to be close to PEP8 compliant), but it sounds like a useful addition!

**Comment by tdeboissiere** [comment]
I finished 68.

I will refactor the code to PEP8 and might add some figures as well. All directories should normally be created when cloning the repository. I can automatize the data downloading with wget. But you still need to have a Kaggle ID and password.

**Comment by maciejkula** [comment]
If you'd like to include the example in this repo, I think it should be entirely self contained (that is, no cloning of other repositories) and if possible have very minimal dependencies. Kaggle login details are a problem, is there no other way of getting the data?

If this all sounds too painful I would be happy to include a link to your notebook in the readme?

**Comment by tdeboissiere** [comment]
The competition organisers will release the data for research at some point but it is not yet clear when. In the meantime, there is no other option.

For now it might be better to simply include a link. I will refactor the notebook when the data is public.

**Comment by maciejkula** [comment]
Sure, that sounds like the best plan for the moment. Where would you like me to link to?

**Comment by tdeboissiere** [comment]
You can use the github link I gave in my first post. I will update the notebook when the data becomes public.

**Comment by maciejkula** [comment]
Made a PR in #34
