### ISSUE TITLE
random_train_test_split not working

### ISSUE THREAD

**Issue by AmiraAyadi** [lyst/lightfm#311]
Thanks this package, your work is great!

I am trying to split my dataset into train and test set using the code from lightfm.cross_validation.

But when I set a random_state ( at 42, for example) I have an `AttributeError: 'int' object has no attribute 'shuffle'` I understand that come from here `random_state.shuffle(shuffle_indices)`  in cross_validation.

How can I fix this?

Also, when I run it with `random_state=None` I got an `ValueError: Test interactions matrix and train interactions matrix share 29 interactions. This will cause incorrect evaluation, check your data split.` I know this is a 'random' split but is this suppose to happen ? How can I split my dataset otherwise ?

Any feedback would be greatly appreciated ! Thanks again

**Comment by maciejkula** [comment]
You should pass in an instance of `numpy.random.RandomState`. I will accept a PR that takes integers and transforms them into a `RandomState` as well, if you care to write one.

Do you have duplicate entries in your interactions matrix? Try converting it to CSR and back to COO.

**Comment by AmiraAyadi** [comment]
Converting the interaction matrix to CSR then back to COO format work! thank you! in fact, I did a "drop_duplicates" on my data but I forgot to specify on which column and as I had the date of purchase I found myself with duplicates without me noticing. I was sure there were no duplicates, sorry to have bothered you with that.

I will try to find time to write the PR that takes integers and transforms them into a `RandomState` :)

I have another question though, I have another question though, as I have my train and test set now. I'm getting pretty high results : 

`Collaborative filtering train AUC: 0.9123019
Collaborative filtering test AUC: 0.9124159`

and 

`Hybrid train AUC: 0.99997926
Hybrid test  AUC: 0.9999861`

it seems very odd to me...do you have any idea why I have these results?

**Comment by maciejkula** [comment]
In the hybrid case, hard to say. AUC of over 0.9 is quite normal, but these results look very high.

**Comment by AmiraAyadi** [comment]
in the other hand, Precision values seem normal:
`Precision: train 0.12, test 0.11.`
Should I work with these values or do you think there is a problem to look for in my data ?

**Comment by maciejkula** [comment]
I think precision and MRR are more reliable metrics than AUC: if those look OK, I think you'll be fine.

**Comment by AmiraAyadi** [comment]
that's great then! thank you for your amazing work and your help :)

**Comment by maciejkula** [comment]
My pleasure. Let me know if you have any further questions!

**Comment by adsk2050** [comment]
Just for someone who comes here again, The bug has been fixed in the github code but not released yet. So instead of an integer, pass ```random_state=np.random.RandomState(seed=<random_state_input>)``` in the function.
