### ISSUE TITLE
Explicit Feedback Recommender

### ISSUE THREAD

**Issue by LauraMitchell16** [lyst/lightfm#313]
Love this LightFM library - thank you!

I have used it to build a hybrid content-based and collaborative filtering model. My interactions matrix contains both positive (+1) and negative (-1) interactions as our customers were requested to vote yes or no on the items. Items that they have not interacted with yet should not be classed as a negative (as this is an Explicit Matrix Factorisation problem). 

When reviewing the AUC with loss 'warp', it scores very highly (c. 0.90). However, when using loss 'logistic' (as suggested to do  in the notes 'logistic: useful when both positive (1) and negative (-1) interactions are present.'), the AUC is very low (c. 0.30). 

Am I doing something wrong here or is my understanding incorrect and it cannot be used for Explicit problems?

Thanks in advance for any advice.

**Comment by maciejkula** [comment]
That's because explicit feedback recommenders are not very useful: https://github.com/maciejkula/explicit-vs-implicit.

Only use them if you are really sure what you're doing. In most cases they produce substandard results.

**Comment by LauraMitchell16** [comment]
Thanks for the response, that’s a shame. 

Could you recommend any other libraries that could help implement this hybrid explicit model? From my research it seems that Spotlight and Suprise libraries only implement Explict Collaborative Filtering models. Or if not a hybrid approach, could you recommend a library for a Explict Content-Based model?

**Comment by maciejkula** [comment]
I would recommend _not_ using an explicit feeback approach: most likely, it will perform worse than an implicit feedback approach.

You may also be interested in the discussion in https://github.com/lyst/lightfm/issues/310.

**Comment by yuxinchenNU** [comment]
Thanks for this great package @maciejkula .  I encountered the same situation where AUC is very low ~0.4 when using the logistic loss function and both +1 & -1 feedback, while AUC is ~0.9 using warp and only +1 feedback. I was wondering if you could point me to a reference for how the logistic loss function is used. Thanks!
