### ISSUE TITLE
How to rank by preferences a subgroup of items for one or more user(s)

### ISSUE THREAD

**Issue by phenric** [lyst/lightfm#314]
Hi,

This is not really an issue but more a question.

How could I sort a subgroup of items (from a category) following to the preferences of a user or more. In others words, I would like to rank a subclass of items for a subgroup of users.

As example, in the case of Movielens, if I would like to sort all Disney's movies (a subgroup) according to the preferences of one or more users, what should I do ?

I tried to be as clear a possible. Let me know if it does not.

Thanks for reading me & thanks a lot for the great job you do !

**Comment by maciejkula** [comment]
The `predict` method accepts a user id and a list of item ids: you should filter the item ids to only contain ids from the group you'd like to score, then compute predictions for the group of users you are interested in.

**Comment by phenric** [comment]
Thank you for your help !

If I want to calculate the prediction for 2 users and 4 items, I have to create a first array with the two user ids and another with 4 item ids as explained in the documentation, isn't it ?

>  an array containing the user ids for the user-item pairs for which a prediction is to be computed

Here what I did for my example 

```
    user_id = np.asarray([], dtype=np.int32)
    ar = sys.argv[1] 
    for x in ar:
        user_id = np.append(user_id, x)
```

And I do the same code to create the item_id.

With args as `[ [ 17, 15 ], [ 266, 285, 300, 315 ] ]`.

However, when I try to predict the model it results an _AssertionError_ with this line `assert len(user_ids) == len(item_ids)` in lightfm.py line 699.

Where is my error ? What's my problem ?

Thanks again !

**Comment by phenric** [comment]
Thank you for the answer.
But how could I do to get the merged prediction. Only one prediction that fit for two users as a kind of a "median" prediction ?

**Comment by maciejkula** [comment]
You can average or otherwise combine the individual predictions and return that averaged score for both users?

**Comment by phenric** [comment]
Ok it seems to work ! Thank you !
I created for loop to get the prediction for each user as you suggested. Then with another for loop, I add the score to zero numpy array. That's how I get my averaged prediction for few users.
Is that a correct way ? Is there a more efficient way ?

**Comment by maciejkula** [comment]
That sounds good enough :)

**Comment by phenric** [comment]
Thanks again for the help I will close the issue :)
