### ISSUE TITLE
Generating Predictions

### ISSUE THREAD

**Issue by jattenberg** [lyst/lightfm#315]
This may be a stupid question corresponding to basic functionality, but...

I have n users (`O(millions)`) and m items (`O(100k)`), with very sparse interactions. Building a csr matrix and training (in a pure CV case) is pretty straight forward. I'm interested in generating the top k (`O(100)`) recommendations for each user. Is there an example of how to do this? Is there an efficient batch operation? I can generate recs for each person individually, but, even with multithreading, generating recs for everyone will take days.

**Comment by maciejkula** [comment]
The easiest way is probably to use the `[get_item_representations](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_item_representations)` and `[get_user_representations](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_user_representations)` methods.

They return matrices of embeddings and arrays of biases, allowing you to perform fast batch multiplications via standard numpy `dot` operations. Combined with pre-allocating the receiver (using the `out` argument in `[dot](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.dot.html)`), this should give you pretty decent speed for predictions themselves.

For sorting, `[np.argpartition](https://docs.scipy.org/doc/numpy-1.14.0/reference/generated/numpy.argpartition.html)` may help for efficient partial sort up to 100, followed by a full argsort on the top 100.

Together, and parallelized using joblib or similar, this should take you close enough to C speed. If that is still too slow, you may have to distribute this across a cluster.

**Comment by jattenberg** [comment]
This is a good lead, thanks. i think i should be able to do some manipulation and use nmslib too.

**Comment by jattenberg** [comment]
Small followup for future generations: using nmslib with the option: `space='negdotprod'` does efficient approximate max inner product search, and seems to work pretty well for generating recs. I'd make a demo, but I don't think it'd me worth introducing the extra dependency.

**Comment by Tina-Bu** [comment]
Thanks for the thread!

**Comment by santoshgsk** [comment]
How will nmslib handle the bias terms of user and item representations?

**Comment by ddofer** [comment]
@jattenberg  Did you get this wokring/have an example? I also need to get top K predictions, and haven't used the numpy sparse matrix functions before.
