### ISSUE TITLE
maximum of precision@K?

### ISSUE THREAD

**Issue by AmiraAyadi** [lyst/lightfm#316]
Hi Maciej, 

I just have a question about the precision@k metric, in fact I just realise that if the AUC's maximum is 1, for  the precision@K it's depend on our data.

Please correct me if I am wrong : for` k=10`, if I have the mean of all purchases's count grouped by users equal to 0.14, then the maximum precision@10 I can achive is `0.14`, even with the best hybrid model I can build.

Is that right? 

If it is, I sent you my notebook by email last friday where I said at the end that I was hoping to get a bigger score than that, can I say now that this is not possible?

**Comment by AmiraAyadi** [comment]
Thank you very much.  I was not sure about it :)

**Comment by kj-lai** [comment]
Hi Maciej, 

I need guidance on calculating the max value of precision@k and recall@k. Let's say my test set has 100 users and each user has 5 item interactions.

For k = 10, 
max precision = (5/10) / 100 users = 0.005
max recall = (5/5) / 100 users = 0.01

1. is this correct?
2. is this precision formula a.k.a. mean average precision?
