### ISSUE TITLE
Building datasets

### ISSUE THREAD

**Issue by rayane-m** [lyst/lightfm#318]
Hello !

Thank you for this open source package, it help a lot and your work is amazing.

I just a have a silly question about dataset construction. I followed the example for my data:
user (160.000 x 300) and item (4000 x 4). 

```
dataset = Dataset()
dataset.fit(users=(x['id_user'] for x in user),
            items=(x['id_item'] for x in item),
            user_features=((x['id_user'], [[x[col] for col in list_columns_user]]) for x in user),
            item_features=((x['id_item'], [[x[col] for col in list_columns_item]]) for x in item))

```
But when I try `dataset.user_features_shape()` I get `(160000, 160000)`. shouldn't I rather have this `(160000, 300)` ?

Indeed, we can read in the documentation : 

> Returns
        -------
        (num user ids, num user features): tuple of ints

and my num user features is 300. So there is an error in what I did?

Sorry for the stupid question!

**Comment by maciejkula** [comment]
This is the expected result. By default, LightFM adds a feature per every user and item. You can disable that in the constructor.

**Comment by maciejkula** [comment]
(Well, you should get 160000 x 1600300 or something like that. Are your feature names the same as some of your user ids?)

**Comment by rayane-m** [comment]
Oh ok.

No, none of my features names are the same as user ids. 
Same for `item_features_shape` I got `(4000, 4000)`

**Comment by maciejkula** [comment]
What data are you passing as `user_features` and `item_features`? It should just be a list (or other iterable) of the names of user/item features.

**Comment by rayane-m** [comment]
I misunderstood this line in the example : `dataset.fit_partial(items=(x['ISBN'] for x in get_book_features()),
                    item_features=(x['Book-Author'] for x in get_book_features()))`

I was trying to do the same thing, obviously the wrong way.

by modifying using just the name, I have the right result. Thank you !

**Comment by maciejkula** [comment]
You need to pass an iterable of tuples of `(id, [list of features for that id])` into `build_features`. It looks like at the moment you're passing the same features for every user?

**Comment by rayane-m** [comment]
At the moment I pass the user features name in fact, that what I read in the doc.
I tried with the actual list of features for each id, like that:

`user_features = dataset.build_user_features(((x['id_user'], x[list_columns_user]) for x in user), True)
`
(user is a  `csv.DictReader` like in your example)

but it did change a thing :(

**Comment by maciejkula** [comment]
Are you passing features for the second user? Is the resulting matrix an identity matrix? Can you post a short gist that reproduces this?

**Comment by maciejkula** [comment]
(If you think the docs are unclear on this point please make a PR with improvements.)

**Comment by maciejkula** [comment]
One more pointer: if you are using generators over files, you can only iterate over it once: subsequent iterations will yield zero elements. Maybe you are creating one csv reader, using it for `fit`, then trying to use it again for `build_features`?

**Comment by rayane-m** [comment]
Sorry for late answer, I no longer had access to the data.
you nailed it! It was the generator problem, I didn't know that we can't iterate over it once.  I don't really know how to deal with this type. So I redid all the treatment with pandas (I know it better), and I think it works!
I build a new `user_features`  and it is a diagonal matrix with 0.0454 everywhere on the diagonal. Is the fact that it's the same value across the diagonal is excepted? 

I didn't normalized my values, just used the parameter `normalize=True` while building user/item features (with `build_item_features` and `build_user_features`) may be this can lead to a mistake ?

**Comment by maciejkula** [comment]
If all users have the same number of features the value on the diagonal will be the same for all of them.

**Comment by AmiraAyadi** [comment]
I see,
Thanks a lot for your time and help, you're awsome!

**Comment by rayane-m** [comment]
Got it. thanks a lot, I really really appreciated your help.

**Comment by kewlcoder** [comment]
> This is the expected result. By default, LightFM adds a feature per every user and item. You can disable that in the constructor.

Hi Maciej,
I couldn't find anything in the constructor that can disable the addition of a feature per every user & item. Can you please help.
Documentation link - [https://lyst.github.io/lightfm/docs/lightfm.html]

**Comment by igorkf** [comment]
It's possible to pass more than one user feature for each user?
Like: 
```
[
  (0, {'category': 'horror', 'sex': 'male'}),
  (1, {'category': 'romantic', 'sex': 'female'}),
   ...
]
