### ISSUE TITLE
ValueError: The user feature matrix specifies more features than there are estimated feature embeddings

### ISSUE THREAD

**Issue by PlissBurl** [lyst/lightfm#322]
Hello, 
I build a model and everything is good (thanks to your work). But now I have new user and new features with NO interaction (cold start) and I want to make a recommandation for these new users.

You said in other issues to use the `fit_partial` method, that what I did but I have `ValueError: The user feature matrix specifies more features than there are estimated feature embeddings
` and I don't know why.

Here what I did:

1. Fit_partial the dataset build in first place : 

```
dataset.fit_partial(users=(iterable of new user ids),
            items=(iterable of new item ids),
            user_features=terable of user features,
            item_features=iterable of item features)
```

2. I re build the first interaction matrix (with no new interaction) but with the new dataset mentionned in 1.

3. Build the new user features matrix as a concatenation of new and old users.

4. Build the new item features matrix as a concatenation of new and old items.

5. I used fit_partial on my old model:
`model.fit_partial(train, user_features=upd_user_features, item_features=upd_item_features, epochs=50)`

If this is wrong, how can I achieve my goal ? may I ask your help for this even if it's not an actual issue ?

**Comment by maciejkula** [comment]
You can't add new users or new items (or new user features or new item features) to an already estimated model.

**Comment by PlissBurl** [comment]
> You can't add new users or new items (or new user features or new item features) to an already estimated model.

OK, I thought it was the purpose of `fit_partial`.

> If you expect new users, you should train the original model allowing for them (even if they have no interactions yet).

So I have to re-train the model for all users (new and old) and all items every time I have new user/item ?
Is that it ? Sorry if I misunderstand.

It seems to be very heavy to compute all this, knowing that we want to use this recommendation also for visitor (as we have their meta data) and we have a lot of visits, re-compute all the model will take too much time. Is there an other solution ?

**Comment by maciejkula** [comment]
You have to retrain if you have a new user or item features.

You can make predictions for new items and users that use only the features that have been used in training. Simply construct the appropriate feature matrices.

Have a look at https://stackoverflow.com/questions/46924119/lightfm-handling-user-and-item-cold-start?rq=1 and https://github.com/lyst/lightfm/issues/210 for some more pointers.

**Comment by alexmilano** [comment]
@maciejkula I think this links are good: https://stackoverflow.com/questions/46924119/lightfm-handling-user-and-item-cold-start?rq=1 and #210, but the thing is that if you have new users giving ratings of your items, you can't give those users fast recommendations because you need to train that user with some interactions? 

Imagine a system that you train with all the movies data, and you have a website with a survey for any user that select their favorite movies, you need to upload the form and the re-train all the model for this user? without any user feature, just new interactions. I think is too much to retrain over and over and not have a solution for this. I thought that `fit_partial` solved this problem but I'm having the same issue as @PlissBurl

**Comment by CoteDave** [comment]
Same here... I think this is a major problem! Make it not usefull to retrain everything each time we have a new user... I think the problem come from the embedding matrix (The user feature matrix specifies more features than there are estimated feature embeddings).  I dont know what predict is doing under the hood but the new user data should be mapped on those existing feature embeddings not creating new ones
