### ISSUE TITLE
Drastic increase in training time when using item/user features

### ISSUE THREAD

**Issue by seniath** [lyst/lightfm#323]
I've spent the last couple of weeks working to improve our recommender, which uses your library under the hood, with the main goal being to include user features at training and prediction time.

My first step was to upgrade to LightFM 1.15 (previously we were on 1.09), so as to make use of `LightFM.Dataset` to replace our previously hand-rolled dataset generation.

We have ~8,000,000 users and ~5,500 items. Users have 13 features, and items have ~200 features.

Plugging this data into `LightFM.Dataset` gives me these datasets to use

- `interactions` (7954774, 5501)
- `weights` (7954774, 5501)
- `item_features` (5501, 5705) (with identity matrix)
- `user_features` (7954774, 13) (without identity matrix)

If I build and train a model in the following way, it takes approximately 15 minutes on my MacBook (a 2015 2.9 GHz Intel Core i5 MacBook Pro with 8Gb of RAM)

```python
model = lightfm.LightFM(no_components=32, loss='warp')
model.fit(
    interactions,
    sample_weight=weights,
    epochs=20,
    num_threads=4,
    verbose=True
)
```

However, when including the `item_features` and `user_features`, it takes approximately 30 minutes to do **one** epoch, let alone the full 20 (again, on my MacBook).

```python
model = lightfm.LightFM(no_components=32, loss='warp')
model.fit(
    interactions,
    sample_weight=weights,
    item_features=item_features,
    user_features=user_features,
    epochs=20,
    num_threads=4,
    verbose=True
)
```

This issue was flagged when I first deployed the above code to production. Our trainer runs on an AWS `c5.2xlarge` EC2 instance, and after it had been running for 4 hours we decided to kill it and revert the change, as it was going to impact some other overnight tasks.

Is this increase in training time to be expected, given these hyperparams and datasets, or is likely that I've made a mistake in my understanding of how LightFM should be used?

One final thing to note: I'm not a data scientist - I've taken ownership of this recommender from a colleague who has since left the company. I understand the Python side of things, but not the nuts and bolts of what your library is actually doing.

**Comment by maciejkula** [comment]
Thanks for the detailed problem description!

The running time of the algorithm is linear in the number of _nonzero_ item
and user features: if the average number of nonzero features per intem
increases from 1 (no item features) to 10, you can expect a (somewhat less
than) tenfold increase in training time. This in not because of an
inefficient implementation: it's just that more vector multiplications are
now required.

It looks like your observations are consistent with this expectation, so
all looks normal. To reduce training time I would recommend using
multithreading. You will need a Linux machine for this, because clang does
not support openmp.

**Comment by seniath** [comment]
> Thanks for the detailed problem description!

And thank you for the speedy reply! This is very useful information. I'll see if we can figure out a better solution to when and where our model is trained overnight.

**Comment by maciejkula** [comment]
My pleasure. If you install it in Docker you can train it with parallelism even on a mac.
