### ISSUE TITLE
Precision@k evaluation

### ISSUE THREAD

**Issue by eggie5** [lyst/lightfm#324]
Looking at the source for the precision at k implementation, it looks like it divides the sum of the true positives by k, which is fine. However, as the wikipedia article states, https://en.wikipedia.org/wiki/Evaluation_measures_(information_retrieval)#Precision_at_K ,  one shortcoming of this is that a perfect recommender can still get a low score if the number of test interactions is lower than k. So one implementation I've seen to remedy this is to take min `min(k, num_test_items)` so that it still works in the traditional sense, but also is adaptive for small test sets. What do you think?

Ref implementation: https://gist.github.com/mblondel/7337391#file-letor_metrics-py-L38

**Comment by maciejkula** [comment]
I'm OK with this as an option (triggered by an optional argument), although I don't think it really matters --- the main thing is that the metric allows you to reliably compare two models.

**Comment by eggie5** [comment]
Fair enough, was mostly trying to get your thoughts as I don't think you check Gitter anymore :)

**Comment by maciejkula** [comment]
Many people ask a question on Gitter while _at the same time_ asking a question on Github. Which is what you have done, and that is why I responded to you here but not on Gitter.
