### ISSUE TITLE
Using updated `user_features` at prediction time

### ISSUE THREAD

**Issue by seniath** [lyst/lightfm#325]
Our recommender trains overnight, but we're looking to encourage users to give us information (i.e. more `user_features`) by offering 'live' recommendations. It seems we can do this by passing in a set of `user_features` at prediction time, something like

```python
a = dataset.user_features.toarray()
a[394858] = np.array([1, 0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 1])
updated_user_features = sparse.csr_matrix(a)
model.predict(394858, dataset.item_ids, user_features=updated_user_features)
```
(As in my previous issue, the shape of `dataset.user_features` is `(7966874, 13)`)
However, I've two questions about this approach:

1. Is this correct - does providing new features for a user like this correctly improve the recommendations without retraining the entire model?
2. Performing this matrix operation is pretty expensive - do we need to pass in the full `user_features` matrix like this, or could we pass in a mostly-zero matrix of the same shape, but with nonzero values for the user in question, i.e:

```python
row = np.array([394858, 394858, 394858])
col = np.array([0, 6, 12])
data = np.array([1, 1, 1])
updated_user_features = sparse.csr_matrix(
    (data, (row, col)),
    shape=dataset.user_features.shape
)
model.predict(394858, dataset.item_ids, user_features=updated_user_features)
```

Using `%timeit` in ipython with the above results in `42.6 ms ± 445 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)`, vs `2 s ± 13.1 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)` for the more expensive operation. For something that is done as part of a user request, we'd like to avoid a 2s delay (not including network time etc)

**Comment by maciejkula** [comment]
1. This is correct.
2. Yes, you can also do that.

One additional way of speeding up requests is by using the [`get_item/get_user_representations`](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_user_representations) methods. Those will give you the latent vectors (and biases) given features, and you can just do `item_bias + dot(user_repr, item_repr)` from there.

**Comment by seniath** [comment]
> 2. Yes, you can also do that.

Would using a mostly-empty set of `user_features` such as this have an impact on the quality of the prediction - vs using a 'full fat' updated set?

> One additional way of speeding up requests is by using the [get_item/get_user_representations](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_user_representations) methods. Those will give you the latent vectors (and biases) given features, and you can just do `item_bias + dot(user_repr, item_repr)` from there.

I'll be honest, I don't fully follow this suggestion I'm afraid! Would it be possible to go into more detail?

**Comment by maciejkula** [comment]
No. After fitting with the full set, the model uses only the features for
the user (and items) you are predicting for.

Have you read the LightFM paper? The model works by estimating latent
vectors and bias terms for features; the representation for an item is then
a weighted sum of its feature vectors. The methods I mention give you these
sums given an estimated model and feature matrices. You can then computer
the scores efficiently using the latent vectors (taking their inner
product) and adding item biases.

**Comment by seniath** [comment]
> No. After fitting with the full set, the model uses only the features for the user (and items) you are predicting for.

Perfect 👨‍🍳 💋 

> Have you read the LightFM paper?

Not yet - will take a look, thanks!
