### ISSUE TITLE
Finding issues in the issues section is difficult. 

### ISSUE THREAD

**Issue by RothNRK** [lyst/lightfm#337]
I'd like to help with some issues related to lightfm but it is difficult to actually find them. None of the issues include tags and most of them are questions, not issues. 

I'd like to suggest the project starts to use Labels so issues and questions can clearly be separated.

**Comment by maciejkula** [comment]
That sounds like a good idea. I'll try to do that.

The _vast_ majority of user interactions are user questions, of varying degrees of sophistication. Have you found any actual issues that you think are worth addressing? I can tag them appropriately.

**Comment by RothNRK** [comment]
No I didn't even bother looking through them since the majority of them are questions. I think the project would get more help if it was clear of where people can help.
