### ISSUE TITLE
Building recommendation model when only one item selected per user

### ISSUE THREAD

**Issue by smidelius** [lyst/lightfm#338]
Hi,

I'm pretty new to lightfm and recommendation models. My problem is that I could not get satisfying results with the model. Precision@1 almost the same as the precision when choosing the most popular item to all users. The specialty of my data is that every user picks only one item. I have tried to add user features and item features but I get almost the same precision in all settings (only user features, only item features, user & item features).
Tried different hyperparameters but I could not get significant improve in terms of precision.

Is it possible that the model can not function well because the interaction matrix is to sparse? 
 
Thanks!

**Comment by maciejkula** [comment]
This is a _very_ unusual setting. The only way this will work better than random is if you use user features. If those are reasonably predictive, you should be able to get an OK model.

Have you tried something simpler that tries to predict the items as a function of user features, like a random forest?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
