### ISSUE TITLE
Create Dataset

### ISSUE THREAD

**Issue by 0x5eba** [lyst/lightfm#341]
Hi,
I am trying to feed multiple user features to my dataset, but I don't know how to do it in the right way.

For 1 feature:
```python
users = pd.read_csv('./ml-1m/users.dat', sep='::', engine='python', 
                        names=['userid', 'gender', 'age', 'occupation', 'zip'])
ratings = pd.read_csv('./ml-1m/ratings.dat', engine='python', 
                          sep='::', names=['userid', 'movieid', 'rating', 'timestamp'])
movies = pd.read_csv('./ml-1m/movies.dat', engine='python',
                         sep='::', names=['movieid', 'title', 'genre'])

dataset = Dataset()
dataset.fit(ratings['userid'], ratings['movieid'], user_features=set(users['age']), item_features=set(movies['genre']))

user_features = dataset.build_user_features( ((i[0], [users['age'][i[0]-1]]) for i in ratings.values) )
```

But what should I do to add `users['gender']` and `users['age']` in user_features ?

**Comment by maciejkula** [comment]
Have you had a look at https://github.com/lyst/lightfm/issues/330?

**Comment by maciejkula** [comment]
What do you mean when you say it doesn't work?

**Comment by 0x5eba** [comment]
When I do `dataset.build_item_features(user_features)` it says that can not find the feature 'F' (from users['gender']).
The error is: `"Feature {} not in eature mapping. " "Call fit first.".format(feature)
ValueError: Feature F not in eature mapping. Call fit first.`

**Comment by maciejkula** [comment]
Is that feature in `set((users['age'][i[0]-1], users['gender'][i[0]-1]) for i in ratings.values)`?

**Comment by 0x5eba** [comment]
Yes, is inside `users['gender'][i[0]-1]`. Every row of users['gender'] contain 'M', or 'F'.

**Comment by maciejkula** [comment]
But is it in `set((users['age'][i[0]-1], users['gender'][i[0]-1]) for i in ratings.values)`? It look to me like that set contains tuples of (age, gender) rather than age and gender separately.

**Comment by 0x5eba** [comment]
I think that's the problem.
How should i put both (`users['age']` and `users['gender']`) inside the `dataset.fit(user_features=)` ?

**Comment by maciejkula** [comment]
Just make them into a single flat collection.

**Comment by 0x5eba** [comment]
I found the problem. 
I was using `dataset.build_item_features` instead of `dataset.build_user_features`, problem solved.

Thanks for your help.

**Comment by williamcao-01** [comment]
@0x5eba Hi, i am using the same dataset but couldnt fit the user features. Tried using your code too. Experiencing the exact same problem as  `Feature F not in eature mapping. Call fit first.`  How did you solve it?
