### ISSUE TITLE
d-dimensional user and item feature embeddings 

### ISSUE THREAD

**Issue by IsotopesOfPlatinum** [lyst/lightfm#346]
Dear Maciej,

In your white paper on this recommender system, you talk the storage of each item and user feature as a d-dimensional vector known as the embedding. I would like to clarify how we deal with the "d-dimensional" part of the implementation of this system. 

Do we have to specify 'd' at some point in the initialization or is it given to us? How would the different sizes of d affect the results and runtime of the algorithm? I ask this after walking through all the example implementations from the lightfm docs and not seeing any particular mention to it.

**Comment by maciejkula** [comment]
It's called `no_components` in the code.

Increasing it will always increase runtime; after some point this brings diminishing accuracy returns, and may even worsen accuracy.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
