### ISSUE TITLE
How to inteprete the precision-at-k? Under what criteria then a prediction is relevant?

### ISSUE THREAD

**Issue by bdqnghi** [lyst/lightfm#348]
P@K is the proportion of retrieved documents that are relevant. In this case, what are the criteria of relevance? For example, the scale of my rating score is from 0-5, and I want to define if a prediction is > 3.5, then it would be relevant, otherwise, it's not. Another case is from 0-1 and I want to define if a prediction is > 0.7 then it would be relevant, something like that according to my understanding. 

But in this case, I don't understand how lightFM measures the P@K when I just put any kind of rating into the precision_at_k function? I'm not saying that lightFM should follow my example, just want to understand this. Thanks :)

**Comment by bdqnghi** [comment]
My guess, the algorithm doesn't care about the threshold, as long as there is interaction, says > 0, means relevant, it is correct?

**Comment by maciejkula** [comment]
That's correct!

**Comment by bdqnghi** [comment]
Thanks :)
