### ISSUE TITLE
about train/test intersections in model evaluation

### ISSUE THREAD

**Issue by tianpunchh** [lyst/lightfm#349]
Hi,
I have a question about the evaluation functions, in the end, it is all about predict_rank() function. From the documentation, I feel that if we provide train_interactions and turn on the check_interactions flag, it will remove the positive interactions seen in the training? 

For example, if testing_interaction for a user is [0, 1, 0, 1, 0] and training_interaction for this user is [0, 1, 0, 0, 0], then the interaction at index 1 would be removed from the final rank as a true positive point because it has been observed in the training. But I feel that even though it is observed in the training, it does no harm that you recommend it again for most situations. Is there a strong dislike for a recommender to recommend the same thing the user has liked before ? Or maybe I do not understand your implementation correctly ?

Thank you so much

**Comment by maciejkula** [comment]
I think this is an accurate description.

The purpose of this is as follows:
1. A good recommender model will definitely recommend items the user has already seen.
2. The test set does not contain the items the user has already seen, so if they are ranked highly, this will reduce the measured accuracy on the test set.
3. To eliminate this effect, we can exclude the already-seen items from the evaluation.

**Comment by tianpunchh** [comment]
cool, thank you
