### ISSUE TITLE
How to use lighfm in production??

### ISSUE THREAD

**Issue by hammadkhann** [lyst/lightfm#352]
I was reading your paper and read this 

> We store model state, including feature embeddings and
accumulated squared gradient information in a database.
When new data on user interaction arrives, we restore the
model state and resume training, folding in any newly observed
features. Since our implementation uses per-parameter
diminishing learning rates (Adagrad), any updates of established
features will be incremental as the model adapts to
new data
Can you explain how do perform this task of resuming the training of my lightfm model  in production.
Please guide me the steps to take and how train my model continuously in production if any new user or entity comes or any new interaction happens?

**Comment by RothNRK** [comment]
You would likely pickle your trained model after training. When new data becomes available you would load the model object and then fit the model with the new data using [fit_partial](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.fit_partial).
