### ISSUE TITLE
Memory issues during prediction.

### ISSUE THREAD

**Issue by RothNRK** [lyst/lightfm#354]
Hello.

I need to make predictions for 150k users and 30k items. While I appreciate this will create a large array (~36 gigs), it requires much more (crashes a 64 gig machine). Since I only need the top 10 item recommendations I tried to solve this by calling the predict method in batches of 10k users for 30k items, and save the indices of the top n item recommendations. This works much worse and required machines with ~488 GB of ram to make all of the predictions.

I would appreciate any suggestions you have.
Thank you.

**Comment by maciejkula** [comment]
For batch predictions like these, I would suggest getting the embeddings out (`get_item_representations`, `get_user_representations`) and performing the prediction using those.

If you would not mind something slightly slower, I would call `predict` for every user separately, perform the sorting and storing of top items, then move on to the next user. Setting aside the storage of results, you should be able to perform this in constant memory.

**Comment by RothNRK** [comment]
Your second suggestion is what I am doing, just for a group, and the memory requirements grow at a massive rate. How would doing this for each user change anything? 

I'll look into the first suggestion. Thank you.

**Comment by hammadkhann** [comment]
For batch predictions like these, I would suggest getting the embeddings out (get_item_representations, get_user_representations) and performing the prediction using those.  @maciejkula how can we perform this?

**Comment by maciejkula** [comment]
@RothNRK sure, but let's first make sure that `predict` works in constant memory. Can you post a snippet here that reproduces the unbounded memory growth problem on the Movielens dataset? I'll then run it on my end and see if I can find the culprit.

**Comment by maciejkula** [comment]
Any luck? Are you still experiencing problems?

**Comment by RothNRK** [comment]
Hey, I haven't been able to recreate the problem so I've been focussing on my project. I'm pretty sure this should be closed but wanted to hold off for a bit. Thanks for your patience.

**Comment by RothNRK** [comment]
Hey. Sorry about this ticket. Looks like the problem was on my side.
