### ISSUE TITLE
get affinity score for unseen item

### ISSUE THREAD

**Issue by tianpunchh** [lyst/lightfm#356]
Does lightfm have an api (or we can easily obtain it somehow) for this task which I think is natural?

Given a user that is involved in the training (basically the model has his/her latent embedding already), if we have a new item that is not seen by the model, but we know its features. And those features are already trained and therefore already have embedding in the training (for example, I know its item features like book author, publisher, subject... other books in the training also use these features, according to lightfm the embeddings of author, publisher ... are done), how can I predict the affinity score of this new item to this user? 

For an already-seen item, we can use model.predict(uid, item_id) since both are registered within the model. For this particular problem, we have user_latent_embedding and of course we can derive item_embedding by weighted sum all feature embeddings together, my question is: is the "score" in the lightfm just the inner product between user and item embeddings? Does lightfm have some convenient way to accomplish this task?

**Comment by maciejkula** [comment]
1. It's the dot product plus item bias.
2. Yes. Construct an item feature matrix that includes the new items as a column, then pass it to `predict`. User and item ids are just row indices into their corresponding feature matrices, so as long as you point at the right row with the right features you can predict for an item/user with any combination of features whose embeddings were estimated during training.

**Comment by tianpunchh** [comment]
@maciejkula I tried and actually find a problem. Because the model has a default identity feature column for each item, when a new item is introduced,  the model does not have the corresponding identity latent embedding for the new item, and it will break. Do you have any idea to get around this issue? Not using the identity feature?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
