### ISSUE TITLE
Exception: Number of item feature rows does not equal the number of items

### ISSUE THREAD

**Issue by hammadkhann** [lyst/lightfm#357]
I am getting this error I dont know why it is coming help needed

**Comment by AjiNugroho** [comment]
hi @hammadkhann how did you fix that ?

**Comment by vladimir-rigvava** [comment]
What could I do in this case?

I have user/items interactions sparse matrix, but some items have no interactions with users at all.
Tried these two options:
1) Build item features for all items. Can't do this, because there is no mappings for some of the items as there is no intteractions info about them. Getting error "item id {entity_id} not in item id mappings".

2) Build item features only for those items, which have interactions with users. Here I get "n_items > item_features.shape[0]" error.

**Comment by Abdul-Rehman-Liaqat** [comment]
As written here:

https://github.com/lyst/lightfm/blob/master/lightfm/lightfm.py


def predict(
        self, user_ids, item_ids, item_features=None, user_features=None, num_threads=1
    ):
        """
        Compute the recommendation score for user-item pairs.
        For details on how to use feature matrices, see the documentation
        on the :class:`lightfm.LightFM` class.
        Arguments
        ---------
        user_ids: integer or np.int32 array of shape [n_pairs,]
             single user id or an array containing the user ids for the
             user-item pairs for which a prediction is to be computed. Note
             that these are LightFM's internal id's, i.e. the index of the
             user in the interaction matrix used for fitting the model.
        item_ids: np.int32 array of shape [n_pairs,]
             an array containing the item ids for the user-item pairs for which
             a prediction is to be computed. Note that these are LightFM's
             internal id's, i.e. the index of the item in the interaction
             matrix used for fitting the model.
        user_features: np.float32 csr_matrix of shape [n_users, n_user_features], optional
             Each row contains that user's weights over features.
        item_features: np.float32 csr_matrix of shape [n_items, n_item_features], optional
             Each row contains that item's weights over features.
        num_threads: int, optional
             Number of parallel computation threads to use. Should
             not be higher than the number of physical cores.
        Returns
        -------
        np.float32 array of shape [n_pairs,]
            Numpy array containing the recommendation scores for pairs defined
            by the inputs.
        Notes
        -----
        As indicated above, this method returns an array of scores corresponding to the
        score assigned by the model to _pairs of inputs_. Importantly, this means the
        i-th element of the output array corresponds to the score for the i-th user-item
        pair in the input arrays.
        Concretely, you should expect the `lfm.predict([0, 1], [8, 9])` to return an
        array of np.float32 that may look something like `[0.42  0.31]`, where `0.42` is
        the score assigned to the user-item pair `(0, 8)` and `0.31` the score assigned
        to pair `(1, 9)` respectively.
        In other words, if you wish to generate the score for a few items (e.g.
        `[7, 8, 9]`) for two users (e.g. `[0, 1]`), a proper way to call this method
        would be to use `lfm.predict([0, 0, 0, 1, 1, 1], [7, 8, 9, 7, 8, 9])`, and
        _not_ `lfm.predict([0, 1], [7, 8, 9])` as you may initially expect (this will
        throw an exception!).

**Comment by AlexHFrench** [comment]
Another thing to note is that the method counts the number of items by taking the max id number and adding one.
Thereby assuming your IDs start at 0. If you have them starting at 1 or not being contiguous then it will incorrectly calculate the number of items you have passed

**Comment by gdubbs100** [comment]
> Another thing to note is that the method counts the number of items by taking the max id number and adding one. Thereby assuming your IDs start at 0. If you have them starting at 1 or not being contiguous then it will incorrectly calculate the number of items you have passed

This is problematic for doing KFoldCV - I'm splitting my data, which means I have non-contiguous item ids - and hence I cannot predict on my test set.
