### ISSUE TITLE
Similar Items cold-start Using Item Features

### ISSUE THREAD

**Issue by fischjer4** [lyst/lightfm#359]
I'm wondering if it is possible to retrieve similar items for an item that has NOT been incorporated into the model yet based off of the item's features. I'm aware of how to handle cold-start recommendations for users using user features, but not sure how to for items.

For instance, take the MovieLens data. Let's say I train the model with user features and item features and are able to get similar movies using the below `similar_items` function. Now let's say a new movie _test_ is added with the features `['Genres_animation', 'Genres_childrens', 'Genres_comedy']`. Is it in anyway possible to get similar items solely based off of the features?

```
def similar_items(internal_idx, item_feat_mtx, model, num_res=10):
    item_representations = model.get_item_representations(features=item_feat_mtx)[1]

    scores = item_representations.dot(item_representations[internal_idx, :])

    item_norms = np.linalg.norm(item_representations, axis=1)
    item_vec_norm = np.linalg.norm(item_representations[internal_idx, :])
    # normalize scores
    scores = np.squeeze(scores / item_norms / item_vec_norm)

    best = np.argsort(-scores)[0 : num_res]
    return sorted(zip(best, scores[best]), key=lambda x: -x[1])
```

**Comment by maciejkula** [comment]
This is absolutely correct. You can simplify your code by converting `feat_idxs` to a sparse matrix and then getting out the representation by calling `get_item_representations` (this is _preceisely_ the use case this method is for). For example:
```python
def cold_start_similar_items(feat_idxs, item_feat_mtx, model, N=10:
    feat_mat = scipy.sparse.coo_matrix((np.ones_like(feat_idxs),
                                                               (feat_idxs, np.zeros_like(feat_idxs)))
    repr, bias = model.item_embeddings(feat_mat)
    scores = item_representation.dot(repr[0].T)
```
(Treat the above as pseudocode.)

Slight fix to your code: you should not be using biases, these have no use for similarity computation.

**Comment by fischjer4** [comment]
@maciejkula Great! Thank's for the help!
