### ISSUE TITLE
how save trained model in a format useful for other environments?

### ISSUE THREAD

**Issue by hodaraad** [lyst/lightfm#360]
I saw in another issue that the trained model of Lightfm can be saved like a pickle object and then loaded back to Python object. But, I actually need to use the trained model in a Ruby environment (train using Python and then use on production which is in Ruby). Any hint how this might be possible? 

I looked at lightfm class and train returns lightfm instance and then predict/test use that instance to access different things. But, could it return something more general and cross-platform object such as a numpy array or a Tensorflow graph? I could use those on the Ruby side then.

Thanks.

**Comment by eggie5** [comment]
Is this a deployment question? Do you just want to run inference/predictions in another environment. If that's the case since light if is a matrix factorization model you just need to export your user and item embeddings. For example, export the embeddings to csv. Then, in ruby you can load the embeddings into memory and make recommendations using the dot product.

**Comment by maciejkula** [comment]
@hodaraad as @eggie5 suggests, you can dump user/item representations ([these](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.get_item_representations) methods) into numpy arrays, then perform the user-item dot products (+ item biases) on the Ruby side as desired.

**Comment by hodaraad** [comment]
Yes, my question was about deployment and prediction only. I went over your paper (http://ceur-ws.org/Vol-1448/paper4.pdf) after posting this question and almost came into the same conclusion as what @eggie5 posted. So I should export "self.user_embeddings", "self.item_embeddings", "self.item_biases" and "self.user_biases" and use them as in equation 1 of the paper, right?

The only thing is I checked "predict" method of LightFM class to have a sense of how things should be calculated on our production side, and it seems it calls "predict_lightfm" method from here looked https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template. In that method,  I don't see these embedding and bias variables of the lightfm object to be used in calculating the predictions/scores for test items. Instead 4 set of other variables ("lightfm.user_features", "lightfm.user_features", "lightfm.user_biases", "lightfm.item_biases") are used to get representation of new test items. Are these the same as the earlier variables I mentioned? cause LightFM class does not seem to have any instance variables with the name "user_features" for instance. What am I missing?

Thanks

**Comment by eggie5** [comment]
As you can see in: https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template#L320

It is indeed taking the dot product between the user and item embedding. 

`item_features` and `user_features` are side-information which you can ignore if you want to approach this a classic matrix factorization problem. If you have side information/meta-data you can use it in the training routine (see arguments to `fit` function) at which point you depart from classical MF and doing a hybrid approach which he highlights in referenced paper as a remedy for cold-items.

**Comment by maciejkula** [comment]
@hodaraad you should use the methods I liked to above.

**Comment by hugos0910** [comment]
@maciejkula  I followed the paper and used item_embeddings, user_embeddings, item_biases, and user_biases to calculate the prediction score, and was able to do so for the matrix factorization model (without using user and item metadata).  However, if I put in user and item metadata the dot product of the matrices no longer produce the score (incorrect dimensions).  Thanks in advance.

**Comment by eggie5** [comment]
If you use feature side-info you to get the user/item representation you need to multiply the embedding matrix by the feature matrix for user and item respectively as per this function: http://lyst.github.io/lightfm/docs/_modules/lightfm/lightfm.html#LightFM.get_item_representations

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
