### ISSUE TITLE
How use LightFM for a session-based case?

### ISSUE THREAD

**Issue by hodaraad** [lyst/lightfm#362]
I have this problem where we cannot track users and we only work at the session-level. So, each new session is assumed to be a new user. Given a session that has progressed to some level (some items have already been visited in that session), I wanted to predict the other interesting items for that session. I thought I could just assign a new user-id to each session and build the interaction matrix from the training data (it will probably be a sparse one). I also did not use any user/item features yet. But then at prediction, given a new session I was confused how to proceed given it will be a new user-id not seen in the training data. It will not be exactly a cold-start user problem as the session has some data and we know some of the interacted items for that session. The only problem is how to represent the new session using the previously seen item in the training. Is there any way to represent them in the user-features like the answer you gave here:
https://stackoverflow.com/questions/46924119/lightfm-handling-user-and-item-cold-start

Or should I build the interaction matrix in the training considering the initial part of the test sessions as well? like if session s has n items, and we want to give predictions for item n+1, we should include session s with its n items in the training as well?

Thanks

**Comment by maciejkula** [comment]
For this sort of real-time updating I would recommend trying another package of mine. I wrote a [blog post](https://maciejkula.github.io/2018/07/27/recommending-books-with-rust/) on how to use it.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
