### ISSUE TITLE
QUESTION:lightFM,predict()

### ISSUE THREAD

**Issue by letotefrank** [lyst/lightfm#363]
Hi,Maciej!
I would like to ask how predict() is calculated?
I think it should be like this, like user 1 for item 1:
```
user_biases = model.get_user_representations()[0]
user_embeddings = model.get_user_representations()[1]
item_biases = model.get_item_representations()[0]
item_embeddings = model.get_item_representations()[1]
user1 = user_embeddings[0]
item1 = item_embeddings[0]
score = u1.dot(i1.T)
ub1 = user_biases[0]
ib1 = item_biases[0]
result = score + ub1 + ib1
```
However, the calculation result is inconsistent with predict(1,[1]),  please answer the wrong place, thank you for your reply!

**Comment by letotefrank** [comment]
0 index in numpy means user1,so it's right.
In my consequence : result=-3.568,but predict(1,[1])=17.025.
I think that'sshould be equal in your paper with LightFM.

**Comment by maciejkula** [comment]
You need to use the same index in your code and in the `predict` call.

**Comment by maciejkula** [comment]
This passes, using your code from above, fixing variables `u1 -> user1` and `i1` to `item1`:

```python
    import numpy as np
    from lightfm import LightFM, datasets
    data = datasets.fetch_movielens()

    model = LightFM(learning_rate=0.05, loss="bpr", random_state=SEED)
    model.fit_partial(data['train'], epochs=10)

    user_biases = model.get_user_representations()[0]
    user_embeddings = model.get_user_representations()[1]
    item_biases = model.get_item_representations()[0]
    item_embeddings = model.get_item_representations()[1]
    user1 = user_embeddings[1]
    item1 = item_embeddings[1]
    score = user1.dot(item1.T)
    ub1 = user_biases[1]
    ib1 = item_biases[1]

    result = score + ub1 + ib1
    predict = model.predict(1, [1])

    assert np.allclose(result, predict[0])
```

**Comment by dwy904** [comment]
The 2nd item from my matrix did not pass.

**Comment by jzlixiao** [comment]
> Not all of the values match exactly. How could that be?
> 
> ```python
> # find the best model
> model_bpr_ult = model_bpr[np.argmax(bpr_map_test)]
> 
> # reformulate the interaction matrix. 
> user_biases = model_bpr_ult.get_user_representations()[0]
> user_embeddings = model_bpr_ult.get_user_representations()[1]
> item_biases = model_bpr_ult.get_item_representations()[0]
> item_embeddings = model_bpr_ult.get_item_representations()[1]
> user1 = user_embeddings[0]
> item1 = item_embeddings
> score = np.matmul(user1, item1.transpose())
> ub1 = user_biases[0]
> ib1 = item_biases
> 
> # test on user_1
> result = score + ub1 + ib1
> predict = model_bpr_ult.predict(0, list(range(len(item1))))
> 
> Counter(np.argsort(result.round(3)) == np.argsort(predict.round(3)))
> ```
> 
> > Counter({False: 340, True: 13201})

for example: There are 943's user and 1682'2 item in movielens100k，  model.predict（943,[1]） or model.predict（1,[1682]） will error. So, model.predict（942,[1]） is user943 to item0.
