### ISSUE TITLE
How to correctly construct the user-user_feature matrix

### ISSUE THREAD

**Issue by hugos0910** [lyst/lightfm#364]
Hi,

I have constructed a user-user_feature matrix with the shape of (n_users, n_features).  The features are ethnicity of the user, so the matrix is one-hot-encoded.  For some reason, my predicted scores become highly negative after including this matrix into my model.  What am I doing that's incorrect?

Thanks

**Comment by hugos0910** [comment]
@maciejkula Thank you, is there any normalization I need to do to the user-user_feature matrix or using it one-hot-encoded is just fine?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
