### ISSUE TITLE
What is the right approach to handle categorical features with Dataset of lightfm ?

### ISSUE THREAD

**Issue by astrung** [lyst/lightfm#370]
With a data frame like that: 

    user_features = [{"user_id":"1","user_city":"X"},
    {"user_id":"2","user_city":"Y"},
    {"user_id":"3","user_city":"Z"}]

To use `user_city` feature with Dataset of lightfm, we have 2 ways: 

* `Method1`: Set each X, Y, Z values as an independent features ( one hot encode ) to fetch into dataset, like that ( it is written on [lightfm docs]( http://lyst.github.io/lightfm/docs/examples/dataset.html#building-the-id-mappings )): 

     `dataset.fit( ..., user_features=['X', 'Y', 'Z'])`
     `user_features = dataset.build_user_features( [('1', ['X']), ('2', ['Y']), ('3', ['Z'])] )`

* `Method2`: Encode X as 1, Y as 2, Z as 3 and fetch for only one feature: `user_city`:

     `dataset.fit( ..., user_features=['user_city'])`
     `user_features = dataset.build_user_features( [('1', { 'user_city':1 }), ('2', {'user_city': 2}), ('3', {'user_city': 3}) ] )`

In my problem, each features can have so many distinct values by using `method1`, it can create a huge matrix, so it will slow down computation. Also, i don't know how Lightfm model will handle addition features if using `method2` , because it is not recommended in documents, it can reduce model performance or accuracy.

So which approach i should choose ?

**Comment by DoronGi** [comment]
I can understand why you would want to avoid ```method1``` (it wouldn't only slow down computation; unless you have plenty of users in **each** city, your model won't be able to learn significant representation for most city features) , but I don't think ```method2``` makes any sense. As far as I understand LightFM will construct the representation for each user as a linear combination of its features representations, and you suggest to use a different weight for the ```user_city``` for each city. If you arbitrarily assign numbers to cities I can't see how that can help your model understand the user better.

You could however try different approaches:

- Define few city features which you think are relevant to you problem (e.g. ```big_metropolis```, ```small_village```, ```coastal``` etc.) and map each city to the corresponding feature (one hot encoded).

- Define even fewer city features (e.g. ```big_city```) and map each city to a weight of the relevant features, such that New York would get a higher ```big_city``` weight than Seattle.

Keep in mind that the model can only be as good as the data you provide.

**Comment by astrung** [comment]
From what you recommended, it may be like as dimension reduction - replace `user_city` one hot encoded vector ( huge dimensions ) into another small dimension vector ? 
If i do that, it is like as i need to implement content based filtering from scratch :(

**Comment by astrung** [comment]
Well, does anyone has other ideals ?

**Comment by maciejkula** [comment]
You should use method 1. This is what the built-in Dataset class does.

The feature matrices are sparse, so you don't have to worry about matrix
dimensions.

**Comment by DoronGi** [comment]
@maciejkula wouldn't you at least suggest to remove cities with very few users/interaction? I found it to improve predictions for my model (trained with little data).

**Comment by astrung** [comment]
Thank everyone for help, but i still have 2 questions:

1.  Why one [docs](http://lyst.github.io/lightfm/docs/lightfm.data.html#lightfm.data.Dataset.build_item_features), it said that we can use feature weight for every items. But if we use different weights of a feature for every row, can it build and predict correctly ? 

2. How can we handle  and fetch continuous features for lightfm model ?

**Comment by maciejkula** [comment]
1. Yes. Every row can have different feature weights. Think of it as a sparse matrix.
2. The continuous value is basically the feature weight.

**Comment by astrung** [comment]
@maciejkula Thank you for your responses.
1.please correct me if my approach is correct for continuous features.
If we have a dataset like this:

    user_features = [{"user_id":"1","age":13},
    {"user_id":"2","age":23},
    {"user_id":"3","age":30}]

**Should i fetch into a model like that ? :**

    dataset.fit( ..., user_features=['age'])
    user_features = dataset.build_user_features( [('1', { 'age':13 }), ('2', {'age': 23}), ('3', {'age': 30}) ] )

2. **Can i use this approach for a continuous feature with very big value like money or income ? ( from 0$ to 1.000.000$ ) ?**

**Comment by astrung** [comment]
I am still waiting for responses. For current models,  I convert all continuous features into categorial features and fetch it.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
