### ISSUE TITLE
How to include per-user (per-item) features (that is, an identity matrix) as part of the feature matrix you supply???

### ISSUE THREAD

**Issue by hammadkhann** [lyst/lightfm#376]
Reading your documentation how exactly can I perform this task? Right now I am passing user and item like this 

> item_features = [item1,[feat1,feat2,feat3,feat4]]
> user_features = [user1,[feat1,feat2,feat3,feat4]]

What do I need to add in these matrices to perform the below task?

> Note: when supplying feature matrices, an implicit identity feature matrix will no longer be used. This may result in a less expressive model: because no per-user features are estimated, the model may under fit. To combat this, include per-user (per-item) features (that is, an identity matrix) as part of the feature matrix you supply.

**Comment by hammadkhann** [comment]
can you give a code example? @hugos0910

**Comment by olddaos** [comment]
I believe something like  scipy.sparse.csr_matrix(np.eye(your_data.shape)) will create the required sparse identity matrix for you.

**Comment by hammadkhann** [comment]
@olddaos  and then just stack that with  my original matrix?

**Comment by olddaos** [comment]
Yeah, like this:
# Need to hstack item_features
eye = sp.eye(item_features.shape[0], item_features.shape[0]).tocsr()
item_features_concat = sp.hstack((eye, item_features))
item_features_concat = item_features_concat.tocsr().astype(np.float32)

**Comment by hugos0910** [comment]
I'm late, @olddaos beat me to it!  But yeah, @hammadkhann that's the way to go

**Comment by hammadkhann** [comment]
`features = [(x["entity_id"], x["tags"].split(", "))
    for (index, x) in entity_data.iterrows()]
            eye = sp.eye(features.shape[0],features.shape[0]).tocsr()
            item_features_concat = sp.hstack((eye,features))
            item_features_concat = item_features_concat.tocsr().astype(np.float32)            
            item_features = dataset.build_item_features(features)`
@hugos0910  @olddaos  is this the right way?

**Comment by maciejkula** [comment]
The [Dataset](http://lyst.github.io/lightfm/docs/datasets.html#lightfm.datasets.movielens.fetch_movielens) class does this automatically. Have a look at the class docstring.

**Comment by hammadkhann** [comment]
@maciejkula  thanks

**Comment by 50stars** [comment]
> The [Dataset](http://lyst.github.io/lightfm/docs/datasets.html#lightfm.datasets.movielens.fetch_movielens) class does this automatically. Have a look at the class docstring.

Hey,
I am trying to use the Dataset class for multiple features (in the example it's only for a single one)
could you help me with an snippet example of fit and build_item_features?

**Comment by Terfy03** [comment]
@50stars, late to the party but I found this useful: https://towardsdatascience.com/how-i-would-explain-building-lightfm-hybrid-recommenders-to-a-5-year-old-b6ee18571309
