### ISSUE TITLE
How to adjust the weight？

### ISSUE THREAD

**Issue by letotefrank** [lyst/lightfm#379]
@maciejkula 
Hi! How to adjust the weight with user or product?
For example,The more the user group acts on the same item, the higher the feature weight corresponding to the item.
Thank you for your reply!

**Comment by maciejkula** [comment]
Have you tried the [weights](http://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.fit) argument to `fit`?

**Comment by letotefrank** [comment]
not at all @maciejkula

**Comment by maciejkula** [comment]
Did that help?

**Comment by jmaldon1** [comment]
Could I bring this question back, as i have the same question. Maybe i can clarify it. 
For example if a user likes 2 products that contain "blue", would the feature weight look like this: `[{"color:blue": 2}]`? 

Or would it look like `[{"color:blue": 1}, {"color:blue": 1}]`

Or do you just remove dupes?
