### ISSUE TITLE
Same item recommendations against every item.

### ISSUE THREAD

**Issue by hammadkhann** [lyst/lightfm#380]
I am getting same recommendations against every item with or without using item_features both the times I am getting same recommendations against every item recommendations only changes when I use different user_id can anybody explain why this is happening??

**Comment by hammadkhann** [comment]
@trepca @ogrisel @RothNRK @maciejkula @jongwook ??

**Comment by OktayGardener** [comment]
@hammadkhann Homeboy why are you tagging me I’ve just submitted one PR 😂. You should explain whatever you’re trying to do a bit (when I say a bit I mean a lot) more clearly and give us information about your environment. We can’t really help or deduce anything from the information you’ve provided.

**Comment by RothNRK** [comment]
@hammadkhann I'd also suggest that you read Maciej's paper. It's pretty accessible and a better understanding of the library will likely help you clear up questions faster than tagging us.

https://arxiv.org/abs/1507.08439

**Comment by maciejkula** [comment]
Hey all, sorry about the spam. I've blocked Mr Khan from posting any further issues in this repository.
