### ISSUE TITLE
item_id_mapping and item_feature_mapping is the same, and not able to construct dataset?

### ISSUE THREAD

**Issue by hugos0910** [lyst/lightfm#381]
I've successfully created the interaction matrix and used fit_partial to fit item features, I used the following code:

```python
dataset=Dataset()
dataset.fit(users=df['user_id'], items=df['item'])
dataset.fit_partial(items=df['item'], item_features=df['item_feature'])
(interactions, weights) = dataset.build_interactions(((x, y) for x, y in zip(df['user_id'], df['item'])))
```
When I tried to build the item features with the following code, I get an error
```python
dataset.build_item_features(((x, y) for x, y in zip(df['item'], df['item_feature'])))
```
```Feature v not in eature mapping. Call fit first.```

I also encountered a different issue when I'm trying to get item_feature_mapping.  ```item_id_mapping``` and ```item_feature_mapping``` turned out to be exactly the same.  The code I used is followed:
```python
user_id_mapping, user_feature_mapping, item_id_mapping, item_feature_mapping = dataset.mapping()
```
Not sure if these two issues are related, but I appreciate anyone who can share some insights on what I'm doing wrong here.

**Comment by DoronGi** [comment]
According to the documentation the call for ```dataset.build_item_features``` should have a data parameter in the form of ```(item id, [list of feature names]) or (item id, {feature name: feature weight})```. Even if each user has only one feature, you still need to provide it in list form. Try:
```dataset.build_item_features(((x, [y]) for x, y in zip(df['item'], df['item_feature'])))```
This should solve both your problems.

**Comment by hugos0910** [comment]
@DoronGi Thanks for the help, I just implemented your suggestion and I was able to build the item feature matrix.  However, I am still unable to get the ```item_feature_mapping```.  ```item_id_mapping``` and ```item_feature_mapping``` are still returning the same dictionary.

**Comment by hugos0910** [comment]
I was skimming through the dictionaries, not realizing there are extra entries in ```item_feature_mapping```, careless mistake on my part!  Thanks for the help @DoronGi , I will be closing the thread now.
