### ISSUE TITLE
Calculating max value of Precision & Recall 

### ISSUE THREAD

**Issue by kj-lai** [lyst/lightfm#382]
Hi @maciejkula 

I need guidance on calculating the max value of precision@k and recall@k. Let's say my test set has 100 users and each user has 5 item interactions.

For k = 10, 
max precision = (5/10) / 100 users = 0.005
max recall = (5/5) / 100 users = 0.01

1. is this correct?
2. is precision a.k.a. mean average precision? (Edited: This question is solved. TQ)

I have read about this issue #316, but I still don't understand.

**Comment by hugos0910** [comment]
Here's a good link that discusses precision & recall @k:
https://medium.com/@m_n_malaeb/recall-and-precision-at-k-for-recommender-systems-618483226c54

For precision, take the number of recommended items that are positive interactions in the test set and divide by the number of recommended items @k.

**Comment by kj-lai** [comment]
The explanation is still unclear to me in finding the MAXimum value of precision and recall. How do I know how well the recommender performs with the precision and recall value if i don't know the maximum value?
I hope there would be a section in showing this example some day in the tutorials.

**Comment by hugos0910** [comment]
The max precision that can be obtained depends on the number of interactions in the test set and the k you choose.  Assume that every user in your test data has exactly 5 interactions, and you want to do a precision@10, the max precision you can obtained would be 5 (assume you hit 5 out of 5) / 10, which is 0.5.  If you change the k to 5, the max precision you can get would be 5 / 5, which is 1.0.  If each user in the test set has different number of interactions, the max precision you can obtain for each user is different.

**Comment by maciejkula** [comment]
@hugos0910 that's a great explanation, thank you!

**Comment by kj-lai** [comment]
@hugos0910, thank you for your explanation.
