### ISSUE TITLE
about source code

### ISSUE THREAD

**Issue by blancyin** [lyst/lightfm#383]
Hi，great work. 
I have some problems about lightfm:
I want to read the source code of warp loss, is it in _lightfm_fast.pyx.template?
If i fix the code _lightfm_fast.pyx.template,  how it works ?
I think the file "_lightfm_fast_openmp.c" is generated by _lightfm_fast_openmp.pyx, where i can read the code?

**Comment by DoronGi** [comment]
The template file is indeed the one you edit. There is an explanation at the bottom of the project page:

> Development
> Pull requests are welcome. To install for development:
> 
> Clone the repository: git clone git@github.com:lyst/lightfm.git
> Install it for development using pip: cd lightfm && pip install -e .
> You can run tests by running python setup.py test.
> LightFM uses black (version 18.6b4) to enforce code formatting.
> When making changes to the .pyx extension files, you'll need to run python setup.py cythonize in order to produce the extension .c files before running pip install -e ..

**Comment by maciejkula** [comment]
This is exactly correct. Thanks again!
