### ISSUE TITLE
Train model without user features

### ISSUE THREAD

**Issue by hugos0910** [lyst/lightfm#385]
I a bit confused on how LightFM make predictions if we do not supply user features at training.  From my understanding, only the user features and item features are needed at prediction.  If we do not supply user features, how does the model know what to recommend for the user even though the user we are predicting has interactions in the training data?

Looking at the sample code provided below:
```python
def sample_recommendation(model, data, user_ids):


    n_users, n_items = data['train'].shape

    for user_id in user_ids:
        known_positives = data['item_labels'][data['train'].tocsr()[user_id].indices]

        scores = model.predict(user_id, np.arange(n_items))
        top_items = data['item_labels'][np.argsort(-scores)]

sample_recommendation(model, data, [3, 25, 450])
```
How does the model differentiate user 3, 25, and 450, since user id is suppose to point to the user feature matrix, not the interaction matrix?

A follow up question: if we supply the same user features for two users, will we get the same recommendations?

**Comment by DoronGi** [comment]
The feature matrix in this case is indeed ```n_user x n_user``` identity matrix (one-hot-encoded), but each of these ```n_user``` features has its own ```1 x no_components``` embedding, which is trained to predict the positive items to the corresponding user.

**Comment by maciejkula** [comment]
This is correct. Thanks for your suggestions, @DoronGi!
