### ISSUE TITLE
Scores returned by predict() with & without user/item features

### ISSUE THREAD

**Issue by kj-lai** [lyst/lightfm#388]
Hi @maciejkula, 

I have encountered another issue during prediction. I have trained a hybrid recommender model with the dataset built by `Dataset()` . There are two ways I had used in getting the predicted score:

Method #1:

`model.user_embeddings[0,:].dot(model.item_embeddings[0:3].T) + model.user_bias[0] + model.item_bias[0:3]`
this will return the ranking scores of 3 items for the first user
`array([-1.9818221, -1.5506961, -1.3330014], dtype=float32)`

Method #2:
`model.predict(0,[0,1,2])`
returns
`array([-1.98182154, -1.5506959 , -1.33300209])`

The results for both looks fine. But, when user and item features are inputted into Method 2,
`model.predict(0,[0,1,2],user_features=USER_F[0],item_features=ITEM_F[:3])`
returns
`array([-226.33410645, -226.36463928, -226.31826782])`

`USER_F` and `ITEM_F` are csr matrices from `dataset.build_user_features()` and `dataset.build_item_features()`

By inputting user and item feature matrices, I get a whole new different scores, the ranking also changes.  Should I just ignore the feature matrices? It would be a great help if you could advise me on this problem. Thanks in advance.

**Comment by kj-lai** [comment]
Apologies for the trouble.

After reading the documentation more thoroughly, i found out my mistake. Here is the solution for my problem.

`Users’ and items’ latent representations are expressed in terms of their features’ representations. If no feature matrices are provided to the lightfm.LightFM.fit() or lightfm.LightFM.predict() methods, they are implicitly assumed to be identity matrices: that is, each user and item are characterised by one feature that is unique to that user (or item). In this case, LightFM reduces to a traditional collaborative filtering matrix factorization method.`

so the -1s score referes to CF whereas -226s score refers to hybrid method.

**Comment by SantiDu** [comment]
For more detailed answer, can go to https://github.com/lyst/lightfm/issues/360
