### ISSUE TITLE
Could not find symbol

### ISSUE THREAD

**Issue by jakubLangr** [lyst/lightfm#39]
When running this on the (almost) unmodified jupyter/all-spark-notebook docker image, when attempting to run Python I get the following issue,

>>> import lightfm                                                                      
Traceback (most recent call last):                                                      
  File "<stdin>", line 1, in <module>                                                   
  File "/opt/conda/lib/python3.4/site-packages/lightfm/__init__.py", line 1, in <module>
    from .lightfm import LightFM                                                        
  File "/opt/conda/lib/python3.4/site-packages/lightfm/lightfm.py", line 7, in <module> 
    from .lightfm_fast import (CSRMatrix, FastLightFM,                                  
ImportError: /opt/conda/lib/python3.4/site-packages/lightfm/lightfm_fast.cpython-34m.so:
 undefined symbol: GOMP_parallel   

Things I have tried: 
1. Going to the file `lightfm.py` and moving all of the dependencies onto one line like so:

from .lightfm_fast import (CSRMatrix, FastLightFM,
                           fit_logistic, predict_lightfm,
                           fit_warp, fit_bpr, fit_warp_kos)

to 

from .lightfm_fast import (CSRMatrix, FastLightFM, fit_logistic, predict_lightfm, fit_warp, fit_bpr, fit_warp_kos).

*Same error*.

2. Also tried ".lightfm" to "lightfm" to change from relative import. *Same error*
3. Checking gcc and kernel versions:
gcc 4.9.2
Ubuntu 14.04
Linux 00846c176840 3.13.0-67-generic #110-Ubuntu SMP Fri Oct 23 13:24:41 UTC 2015 x86_64
GNU/Linux

But I think if you just pull the docker image and do a pip install lightfm it should replicate the error precisely.

**Comment by maciejkula** [comment]
Can you link to the dockerfile please? I'll pull it and try to reproduce.

**Comment by jakubLangr** [comment]
https://github.com/jupyter/docker-stacks/tree/master/all-spark-notebook

2015-11-12 18:10 GMT+00:00 maciejkula <notifications@github.com>:

> Can you link to the dockerfile please? I'll pull it and try to reproduce.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/lyst/lightfm/issues/39#issuecomment-156187088>.
>



-- 
Jakub Langr
Mobile (UK): +44 7511 624 004
Mobile (CZ): +420 606 754 679
Mobile (US): +1 650 338 8807
See my blog at jakublangr.com <http://goo.gl/Zbq4t3>!

**Comment by maciejkula** [comment]
This is probably due to an old version of `gcc`, can you try with a newer version?

**Comment by maciejkula** [comment]
You can now use the Dockerfile from the lightfm repo to set up your dependencies.
