### ISSUE TITLE
Fitting with 0 threads crashes

### ISSUE THREAD

**Issue by EdwardJB** [lyst/lightfm#396]
When fewer than one thread is specified during fitting:

```python
LightFM().fit(data, num_threads=0)
```
The result is:

```console
free(): invalid next size (fast)
Process finished with exit code 134 (interrupted by signal 6: SIGABRT)
```

Obviously that's a silly thread parameter, but I was using a function to choose threads, which was returning 0 unexpectedly on a particular config. Would be good if the value was sanity checked by LightFM, rather than just crashing.

```console
$ lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Pop!_OS 18.04 LTS
Release:	18.04
Codename:	bionic
```

**Comment by maciejkula** [comment]
Fixed in #401. Thanks @DPGrev!
