### ISSUE TITLE
Update/Change user_feature values

### ISSUE THREAD

**Issue by kj-lai** [lyst/lightfm#400]
Assuming I have trained a model with the current user_feature,
```
id   A   B   C   D
10   0   1   0   1
```
and after sometime, i wanted to update/change the values in the user_feature matrix using `fit_partial()` function,
``` 
id   A   B   C   D
10   1   1   0   0
```
1. in this case will the user_feature values be overwritten or there will be two of them?
2. if there are two of them, which one will be considered by the model during prediction?

**Comment by maciejkula** [comment]
The user feature matrix is just a matrix object: you can change it however you like. When you pass the changed value into fitting or prediction routines the change will be reflected.

**Comment by kj-lai** [comment]
Noted, thank you for your explanation.
