### ISSUE TITLE
Model Evaluation with embedded user and/or item features

### ISSUE THREAD

**Issue by Jayp496** [lyst/lightfm#403]
Hello everyone,

I have created a LightFM built-in dataset with an interactions matrix containing 474430 users and 8938 items in total. In addition, I have built item and user features out of iterables of the form:

`[
('id',
  {'Feature1': 'a',
   'Feature2': 'b',
   'Feature3': 'c',
   'Feature4': 'd',
   'Feature5': 'e'}),
 ...]`

For the items, all features are categorical. For the users, there are numerical as well as categorical features. It works to create both user and item features:

`print(repr(item_features))
<17876x17881 sparse matrix of type '<class 'numpy.float32'>'
        with 17876 stored elements in Compressed Sparse Row format>`

`print(repr(user_features))
<474430x474437 sparse matrix of type '<class 'numpy.float32'>'
        with 474430 stored elements in Compressed Sparse Row format>`

When the model is built, I am also able to predict recommendation scores for given users. However, when I want to evaluate the model with any of the provided evaluation scores, I receive an error message:
"ValueError: Incorrect number of features in item_features". When I build the model only with user features, I receive the same error with "incorrect numer of features in user_features".
I am training the model with an interactions matrix containing 80% of my transactions data and provide a test interactions matrix containing the other 20% of the data for the evaluation functions.

Could anyone help me out please? If something is unclear to do so, please let me know and I will clarify.

**Comment by DPGrev** [comment]
Hi Jayp496,

Are you using the `random_train_test_split` function for splitting you train and test set?

If so are you sure you are feeding in the item and user features when evaluating the model like so:

```python
precision_at_k(model,
               test,
               item_features=item_features,
               user_features=user_features,
               k=10)
```
Otherwise LightFM will go the error  you are reporting.

**Comment by Jayp496** [comment]
Hi DPGrev,

I am not using the `random_train_test_split` because I have chronological transaction data which I don't want to break. Therefore, I build interaction matrices for training and testing separately with respect to the dates.

But you were right, I missed to specify item_features and user_features in the precision_at_k command! Now it works. Thank you very much!
