### ISSUE TITLE
Updating model with new interactions for same user

### ISSUE THREAD

**Issue by amw5g** [lyst/lightfm#405]
When serving a LightFM model in production, what is the suggested way for handling a new user-item interaction for an existing user?  

That is, a model is built off of user A's positive interaction with items 1, 2, and 4.  User A subsequently interacts with existing item 3 (maybe as a result of a recommendation for item 3! ;)).  User A's latent representation is now updated.  And Item 3's latent representation is also now likely updated.  

Does the interaction matrix need to be updated and the entire model re-fit?

**Comment by DPGrev** [comment]
Hi amw5g,

I think this will answers your questions: [Lightfm in production](https://github.com/lyst/lightfm/issues/347)

**Comment by amw5g** [comment]
Thanks DPGrev, it sort of does.  I'd started down that thread before, but perhaps I didn't read it as well or gave up too soon.  It sounds like fit_partial() may be the way to go.  If I understood it (and clearly I should just try it out), when an existing user has updated interactions, fit_partial() is appropriate.
Cheers!

**Comment by maciejkula** [comment]
Thanks @DPGrev!
