### ISSUE TITLE
item_feature unexpectedly presented in my model

### ISSUE THREAD

**Issue by lampda** [lyst/lightfm#407]
Hi there,
My code is like these below:

<pre>
df = pd.DataFrame([[uid_1,iid_x,1],[uid_2,iid_y,3],....])
r_df = df.pivot(index='uid',columns='iid',values='score')

interacts = sparse.csr_matrix(r_df.values)
train_df, test_df = random_train_test_split(interacts, test_percentage=0.2)

model = LightFM(loss='warp')
model.fit(train_df, item_features=None, user_features=None)

uid=0
item_ids = np.array([iid_x, iid_y, ....])
model.predict(uid, item_ids)
</pre>

However, I got ValueError,

<pre>
ValueError: the item features matrix specifies more features than there are estimated feature embeddings: 733 vs 2884
</pre>

But are there any bug? Since I trained and specified No item_features, No user_features?
What was I doing wrong?

**Comment by lampda** [comment]
I found the reason for the issue above.

uid=0 is of integer type, then it will be converted to np.ndarray with the length of the number of total item_ids, say 733 here in my case.

item_ids is also converted to np.array if it is of type list or tuple, for example the item_ids=array([1,200,2883,123,99,124,...]).

Since there is NO user_features NOR item_features, the model trained will issue `model._construct_features_matrices` with inputs n_user, n_items, and internally call `user_features =sp.identity(n_users, dtype=CYTHON_DTYPE, format="csr")` and `item_features = sp.identity(n_items, dtype=CYTHON_DTYPE, format="csr")`.

The problem is here: **n_users = user_ids.max()+1 and n_items = item_ids.max()+1** from `model.predict(....)` before they are passed to `model._construct_features_matrices`.
Why is this problematic? user_ids and item_ids we passed to the function `model.predict()` are the (array of) raw ids, while _construct_features_matrices will use internal ids converted from `model.predict`.

Users like me are **NOT** aware of this setting will confront the issue above. Here, I passed **user_id=0** and **item_ids=array([1,200,2883,123,99,124,...])** with the length of 733 and the max item_id 2883. Then `mode._construct_features_matrices` constructed a wrong * item_features*.

One need to use some kind of internal ids, rather than the raw ids. But how to do this mapping?

**Comment by lampda** [comment]
@maciejkula  So, why the 'model.predict' will use the max values? why not just use the length of list/array/tuple of ids?

I suggest there is an improvement or hot fix for this:

**n_users = len(user_ids)** and **n_items = len(item_ids)**
Instead *n_users = user_ids.max()+1* and *n_items = item_ids.max()+1* in line 807 and line 808 of the lightfm.py.

And there maybe other files with this logic to be modified accordingly.

**Comment by maciejkula** [comment]
You have to map your ids to a contiguous range starting at zero. The [Dataset class](http://lyst.github.io/lightfm/docs/lightfm.data.html) helps with this.

**Comment by lampda** [comment]
Thanks for the point.

btw, during this time, I managed to figure out how to map my data with internal ids. However, I think it is better to use your idea anyway.

solved.
