### ISSUE TITLE
Can we pass pre-trained user or item embedding to model?

### ISSUE THREAD

**Issue by rahmanidashti** [lyst/lightfm#411]
Hi,

Can we pass pre-trained user or item embedding to model? For example, when I learn an item embedding with word2vec, can I pass it as initialization instead of random values?

**Comment by jithurjacob** [comment]
I'm also looking for something similar. I have the images of the products. I wanted to know how to add latent vectors from Auto encoders as item features.

**Comment by pigooosuke** [comment]
I tried to add those dense values. But, it failed.
validation score was down in my case.
if you use word2vec, its dimension size will be about 200-300 and values are dense, so it spends a lot of time to train.

**Comment by rahmanidashti** [comment]
https://github.com/rahmanidashti/pretrain-lightfm

**Comment by maciejkula** [comment]
You can always set the embedding and bias attributes on the model instance to your pre-trained embeddings.

**Comment by rahmanidashti** [comment]
> You can always set the embedding and bias attributes on the model instance to your pre-trained embeddings.

So, could you please let's know how we can do it in the code? I checked the code, and I found you have just to `user_feature` and `item_feature` to pass the content information.

**Comment by maciejkula** [comment]
You can set the embedding fields on your model instance to whatever you desire.

This is circumventing the public API of the model, but will allow you to accomplish what you are trying to do.

**Comment by Chirag-Amin** [comment]
@maciejkula Deviating slightly from the original question, but in your original paper, you mention using a bag-of-words representation on the CrossValidated dataset (tags + about). How were the bag-of-word representation vectors included in the model? 

I found the following example but I couldn't find the (tag + about) example. https://github.com/lyst/lightfm/blob/master/examples/stackexchange/hybrid_crossvalidated.ipynb
