### ISSUE TITLE
recall at k logic

### ISSUE THREAD

**Issue by majd1239** [lyst/lightfm#414]
I'm not sure how the recall score could ever be 1.0 if k is less than the number of positive examples for the user.
Say a user have 50 positive interaction and k=10. So even if we have a perfect precision where all the top 10 ranks are positive examples, the recall would be 10/50 = 0.2.
Every user would have a different number of total positive examples so not sure how to interpret the mean of the total n recall scores for an evaluation of n users given a fixed k?

**Comment by maciejkula** [comment]
Could you restate your question for me? I am not quite sure what you are asking.

**Comment by majd1239** [comment]
Can the recall at k ever be equal to 1.0 if k is less than the total number of positive examples for each user? 
If all the predicted top k recommended items are correct, but the total number of positive examples is different for each user, how can we know what's a good score for the recall?

**Comment by maciejkula** [comment]
This feels like a question more about the motivation and advantages of various information retrieval metrics than LightFM. Others will be more competent here than I will. Perhaps try CrossValidated?

**Comment by EralpB** [comment]
@majd1239 I think you are right, recall at k alone for a single model is not very helpful, but don't take it as an absolute value, you can train 2 models and compare their recall at k's (obviously with the same k!!)

recall at k being 0.1 doesn't mean it's bad or 0.9 doesn't mean it's good, it's a comparative metric. 1 is the hypothetical upper bound but nothing practical really.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
