### ISSUE TITLE
Huge model size when save to pickle

### ISSUE THREAD

**Issue by nazmiasri95** [lyst/lightfm#415]
Hi, I did follow the following code to store the model into pickle file but the model size is too huge for me to use it in production (Google App Engine env):

```
import pickle

model = LightFM()
model.fit(data)

with open('savefile.pickle', 'wb') as fle:
    pickle.dump(model, fle, protocol=pickle.HIGHEST_PROTOCOL)
```

When I save it to pickle, it gave me a file with 200++MB size. It would be trouble some to get the pickle and predict every time user is hitting the endpoint (the size too huge to be store in GAE cache, unless I'm using external memcache, it might works). Is there any other way to store the trained model into smaller size ?

**Comment by maciejkula** [comment]
This is why ordinarily you would not deserialize on every request. It is more common to deserialize once at server start up, then keep it in memory to serve multiple requests.

I am not familiar enough with the specific of Google App Engine to say what the equivalent there is.
