### ISSUE TITLE
Best way to encode missing features

### ISSUE THREAD

**Issue by mikkelam** [lyst/lightfm#416]
Hi

I'm wondering what's the best way to encode missing features? 

For example say i have three items
```
item A: antique=True
item B: antique=False
item C: antique=np.nan
```
Where np.nan in this scenario means it is unknown whether or not Item C is unique.
Say I'm onehot encoding this scenario, I'd like to avoid having B and C both be 0, as I suspect this would create problems. Is there any way to avoid this scenario? The algorithm would not work with np.nan entries right?

**Comment by mikkelam** [comment]
Nvm. I realised I can just add another column for the nan

**Comment by maciejkula** [comment]
I would suggest creating three features, corresponding to all possible values of your input. This way the model can learn three sets of parameters: what it means for the feature to be there, not to be there, and be unknown.

**Comment by mikkelam** [comment]
..That absolutely makes sense, thanks! Also think you for your great project good sir
