### ISSUE TITLE
Individual item ranks vs global averaged item ranks

### ISSUE THREAD

**Issue by FrancescoI** [lyst/lightfm#417]
My question isn't really about any issues on implementation side but more about interpreting and correctly treating final predictions.

I had been asked to provide top10 recommended items for our users, which was fine and really straightforward using this package.

I had also been asked to output a sorted list of "most preferred" items among all my customers. 
It sounded to me like "most popular" items so I extracted them directly from my DB. Easy peasy.

But here I decided to test another approach and I took the average rank of my items among every users' predictions (using LightFM for the predictions).

I found out that averaged "global" item ranks resemble most popular ones and I was wondering if it has something to do with some maths/statistical properties of CF systems or something.

**Comment by maciejkula** [comment]
That's actually quite a nice result. I am not sure whether this is guaranteed in a ranking model. However, if you were to treat the model as a probabilistic model, estimating the probabilities that a given item will be watched by a given user via maximum likelihood, you would hope that this global property would hold.

**Comment by FrancescoI** [comment]
Thanks @maciejkula .
