### ISSUE TITLE
ModuleNotFoundError: No module named 'lightfm.dataset'

### ISSUE THREAD

**Issue by SethiPawandeep** [lyst/lightfm#418]
Hi
I had installed lightfm using `pip install lightfm` 

The following is the code:
```python
from lightfm.dataset import fetch_movielens
from lightfm import LightFM
```
The error I am receiving is 
![image](https://user-images.githubusercontent.com/9217168/52947045-a2747780-339b-11e9-9e16-8a1cbea54e54.png)

Googled it already but couldn't find anything that could help, so opening an issue here.

**Comment by SethiPawandeep** [comment]
It was just a silly mistake. Was supposed to be datasets and not dataset.

**Comment by naureen3** [comment]
im having the same problem... but i wrote the right code

**Comment by naureen3** [comment]
i first checked conda list it had lightfm included 
then pip it had it 
then pip3... it didn't 
so i type 'pip3 install lightfm' it shows:
C:\Users\DELL>pip3 install lightfm
Collecting lightfm
  Using cached https://files.pythonhosted.org/packages/e9/8e/5485ac5a8616abe1c673d1e033e2f232b4319ab95424b42499fabff2257f/lightfm-1.15.tar.gz
Requirement already satisfied: numpy in c:\program files\python37\lib\site-packages (from lightfm) (1.16.4)
Requirement already satisfied: scipy>=0.17.0 in c:\program files\python37\lib\site-packages (from lightfm) (1.3.0)
Requirement already satisfied: requests in c:\program files\python37\lib\site-packages (from lightfm) (2.22.0)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\program files\python37\lib\site-packages (from requests->lightfm) (1.25.3)
Requirement already satisfied: certifi>=2017.4.17 in c:\program files\python37\lib\site-packages (from requests->lightfm) (2019.6.16)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\program files\python37\lib\site-packages (from requests->lightfm) (3.0.4)
Requirement already satisfied: idna<2.9,>=2.5 in c:\program files\python37\lib\site-packages (from requests->lightfm) (2.8)
Building wheels for collected packages: lightfm
  Building wheel for lightfm (setup.py) ... error
  ERROR: Complete output from command 'c:\program files\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-87l22ias\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\DELL\AppData\Local\Temp\pip-wheel-x3eff8uj' --python-tag cp37:
  ERROR: Compiling without OpenMP support.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\lightfm
  copying lightfm\cross_validation.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\data.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\evaluation.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\lightfm.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\_lightfm_fast.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\__init__.py -> build\lib.win-amd64-3.7\lightfm
  creating build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\movielens.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\stackexchange.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\_common.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\__init__.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\_lightfm_fast_no_openmp.c -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\_lightfm_fast_openmp.c -> build\lib.win-amd64-3.7\lightfm
  running build_ext
  building 'lightfm._lightfm_fast_no_openmp' extension
  error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
  ----------------------------------------
  ERROR: Failed building wheel for lightfm
  Running setup.py clean for lightfm
  ERROR: Complete output from command 'c:\program files\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-87l22ias\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all:
  ERROR: Compiling without OpenMP support.
  running clean
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed cleaning build dir for lightfm
Failed to build lightfm
Installing collected packages: lightfm
  Running setup.py install for lightfm ... error
    ERROR: Complete output from command 'c:\program files\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-87l22ias\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-yifclbl_\install-record.txt' --single-version-externally-managed --compile:
    ERROR: Compiling without OpenMP support.
    running install
    running build
    running build_py
    running build_ext
    building 'lightfm._lightfm_fast_no_openmp' extension
    error: [WinError 3] The system cannot find the path specified: 'C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\VC\\PlatformSDK\\lib'
    ----------------------------------------
ERROR: Command "'c:\program files\python37\python.exe' -u -c 'import setuptools, tokenize;__file__='"'"'C:\\Users\\DELL\\AppData\\Local\\Temp\\pip-install-87l22ias\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\DELL\AppData\Local\Temp\pip-record-yifclbl_\install-record.txt' --single-version-externally-managed --compile" failed with error code 1 in C:\Users\DELL\AppData\Local\Temp\pip-install-87l22ias\lightfm\

and if i test code it says the same thing that you showed, 
and if i test it in VS-code it freaks out and says this module doesn't even exist what the heck are you doing to me woman -_-

**Comment by srmunoza** [comment]
I also have the same problem, were you able to solve it :( ?
