### ISSUE TITLE
Question about the evaluation of recall and precision @ k 

### ISSUE THREAD

**Issue by jeydn** [lyst/lightfm#420]
I'm building my recommendation model in two different ways.
 When I use it with user_features my precision, recall and F1 are quite low but the train and test values are similar.

```
Precision @ 4: train 0.13, test 0.10
Recall @ 4: train 0.28, test 0.29
F1 @ 4: train 0.17, test 0.15
```

In contrary when I build my recommendation without user_features my precision, recall and F1 for the train is high but the value for test is low. 

```
Precision @ 4: train 0.38, test 0.08
Recall @ 4: train 0.90, test 0.21
F1 @ 4: train 0.54, test 0.11
```
What could be the cause of it? 

Some information about my dataset: 

- On average 3.7 interactions per user 
- Users are fairly similar: 62 % share the same user_feature (Could this be the issue?) 

I have another question regarding precision and recall: Does it always test for a cold-start scenario, as the model gets fitted on the train set? Would it be correct to assume if I want to predict recommendations for users that I already now to fit the model on all interactions? (I hope that makes any sense ) 

Thanks for the help and great framework!

**Comment by maciejkula** [comment]
It's hard to say without knowing what your features are, but this does not look unusual. Features allow you to generalize better beyond the training set when your data is sparse.

I'm not sure I get your second question!

**Comment by jeydn** [comment]
After checking the documentation again I think I'm running into issues of the train/test split. So that might cause the different values of train and test.
