### ISSUE TITLE
Item cold-start example results in error

### ISSUE THREAD

**Issue by mattflo** [lyst/lightfm#421]
[lightfm_hello_world.html.gz](https://github.com/lyst/lightfm/files/2891571/lightfm_hello_world.html.gz)
[duplicate_coordinates.html.gz](https://github.com/lyst/lightfm/files/2891592/duplicate_coordinates.html.gz)

Attached is a notebook `lightfm_hello_world.html.gz` following the code examples at http://lyst.github.io/lightfm/docs/examples/hybrid_crossvalidated.html

It fails with the error:

```
ValueError: Test interactions matrix and train interactions matrix share 5 interactions. This will cause incorrect evaluation, check your data split.
```

It appears there are duplicate coordinates in the `stackexchange_crossvalidated.npz` file at https://github.com/maciejkula/lightfm_datasets/releases. See the attached notebook `duplicate_coordinates.html.gz`

One quick solution would be to add `tocsr().tocoo()` to the matrix initialized here https://github.com/lyst/lightfm/blob/master/lightfm/datasets/stackexchange.py#L103

I haven't checked the other npz dataset files.

**Comment by maciejkula** [comment]
Thanks! Would you care to make a PR? [This](https://docs.scipy.org/doc/scipy/reference/generated/scipy.sparse.coo_matrix.sum_duplicates.html#scipy.sparse.coo_matrix.sum_duplicates) should be an efficient way of doing it.

**Comment by mattflo** [comment]
Done! https://github.com/lyst/lightfm/pull/423

**Comment by Rcubes** [comment]
Hi guys,
I noticed this issue seems to be resolved, but I keep getting the same error. I tried the .tocsr().tocoo() aproach but it didn´t work for me (I don´t have any experience using scipy). 

```python
from lightfm.datasets import fetch_stackexchange

data = fetch_stackexchange('crossvalidated',
                           test_set_fraction=0.1,
                           indicator_features=False,
                           tag_features=True)

train = data['train'].tocsr().tocoo()
test = data['test'].tocsr().tocoo()
```

I keep having the same issue.

I tried the solution given in this issue using sum_duplicates() but it doesn't work either.
How can I see the PR reflected in the package?

I installed lightfm via conda forge in windows, not sure if that could be a reason.

Thanks,

**Comment by barbarasilveiraf** [comment]
Hi @Rcubes,

Were you able to solve the problem?

I had the same problem.

Thanks.

**Comment by i-Hun** [comment]
Is it really a problem that train and test share some interactions?
Anyway 5 it's not not a big number so you can always ignore this error using dirty fix like 
```python
from lightfm import LightFM
LightFM._check_test_train_intersections = lambda x, y, z: True
```

**Comment by kholoudsaa** [comment]
Hi 

I have the same issue, and I don't know how I can solve it
Please help!!

Thank you

**Comment by simongiles1** [comment]
Hi @maciejkula, I have been having the same problem here. I had roughly about 350 shared interactions within 4116 interactions in the test and 35520 interactions. I tried the .tocsr().tocoo() to no avail. I haven't yet tried the sum duplicates method as that will take me some time to figure out but I did try i-Hun's solution to suppress the error which worked but I get the following results:
Pure CF model:
 - AUC for the train set is 0.928
  - AUC for the test set is 0.867
  - setting the biases to 0 i get an AUC of 0.733
Hybrid model:
 - AUC for the train set is 0.911
 - AUC for the test set is 0.871
 
So the test set only increased by 0.04. Based on your notes here: 
https://making.lyst.com/lightfm/docs/examples/hybrid_crossvalidated.html#a-hybrid-model
The CF model test set should be much lower. Do you think my super high number has anything to do with me suppressing the error using i-Hun's solution or is something else going on?
Any help would be much appreciated.
Thanks
