### ISSUE TITLE
Add an example of fast prediction via BLAS to documentation

### ISSUE THREAD

**Issue by inpefess** [lyst/lightfm#427]
There is already one optimisation PR for predict method: https://github.com/lyst/lightfm/pull/105

But sometimes one probably can do it in a simpler way (just using numpy with BLAS):
https://github.com/inpefess/lightfm/blob/predict_comparison/examples/batch_predict/predicting_with_matrix_multiplication.ipynb

@maciejkula what do you think about adding another, say predict_numpy/predict_all method like that for batch predictions? If yes, I can prepare a PR from the example code above.

**Comment by maciejkula** [comment]
One of the reasons of the `get_item/user_embeddings` method is to allow fast prediction via BLAS, as you do in your example.

There are tricky balancing issues here:
1. Materializing the embedding matrices is slow.
2. Materialized matrices are large.
3. There is an operating point where `predict` is faster than doing the above.
4. What does the signature of the hypothetical `fast_predict` function look like? Does it compute recommendations for all users? A subset of users? All products? Subset of products? How much memory does it take to store all predictions for all users?

For that reason I have so far been reluctant to add this to the library. If you're interested, we could add a guide for fast predictions to the documentation?

**Comment by inpefess** [comment]
A scenario which I encountered myself in a couple of projects and which several people I consulted also had is the following:
* there are not too many items (all item_embeddings can fit the memory of one server)
* prediction is done by batches of users
* recommendations for one batch of users and all items fit into the memory of one server

In this scenario, one needs a function computing recommendations for a batch of users.
I agree that this case is far from being universal, but it could be useful for some people.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
