### ISSUE TITLE
How does item features build for numerical values

### ISSUE THREAD

**Issue by Ivanclj** [lyst/lightfm#433]
Hi,

I m using lightfm to do a recommendation project right now and my dataset involves longitude and latitude of cities. I wanted to pass those in as item features but when I am done building it, the item features dimension increased from (10000,10000) to (10000,23000). I checked that the longitude and latitude combined have 13000 unique values so it must takes each unique value and made a feature for it. Is this right that for numerical values you still take each unique value and make a feature for it? And do lightfm try to do one-hot encoding for these numerical values in this case? 

Any help would be greatly appreciated!!

**Comment by SimonCW** [comment]
Hi @Ivanclj,

> Is this right that for numerical values you still take each unique value and make a feature for it? And do lightfm try to do one-hot encoding for these numerical values in this case?
I am pretty sure this is how it works and LightFM "one-hot encodes" these unique long-lat pairs. 

You could either bin your values or come up with sensible features (country, region, tropics, subtropics, etc).

**Comment by DoronGi** [comment]
I believe LightFM let you choose between having all you features as on-hot encoded, or as continuous variables. The latter is achieved by passing a dictionary ``` {feature name: feature weight}``` instead of a list of features per user. you can use it for the coordinates (after normalization), and weight 1 for one-hot encoded features, but I would be surprised if it would benefit your model. It makes more sense to try and create new features from these coordinates, according of what your model is trying to predict.

**Comment by maciejkula** [comment]
Great answers, @DoronGi and @SimonCW.

@Ivanclj you could try one of the following things:
1. Use city names instead of coordinates.
2. Compute geohashes (tuning the granularity) from your location data.

**Comment by Ivanclj** [comment]
> Great answers, @DoronGi and @SimonCW.
> 
> @Ivanclj you could try one of the following things:
> 
> 1. Use city names instead of coordinates.
> 2. Compute geohashes (tuning the granularity) from your location data.

Thank you all so much for answering! So does it mean Lightfm works best with only categorical variables? Does it calculate similarities (cosine or pearson) anywhere internally when doing recommendations that works well with both numerical value features and one-hot encoded features?

**Comment by maciejkula** [comment]
It works OK with continuous variables. The bigger issue is that, in your case, it doesn't really make sense to treat lat/lon as continuous variables: do you really believe that a certain item should be recommended in proportion to how far north or south of the equator it is?

**Comment by freytheviking** [comment]
> I believe LightFM let you choose between having all you features as on-hot encoded, or as continuous variables. The latter is achieved by passing a dictionary ` {feature name: feature weight}` instead of a list of features per user. you can use it for the coordinates (after normalization), and weight 1 for one-hot encoded features, but I would be surprised if it would benefit your model. It makes more sense to try and create new features from these coordinates, according of what your model is trying to predict.

@DoronGi , thanks for answering this thread. I have been experimenting with `LightFM` and some of my item features are also numeric. In this post, you mentioned normalization. Is this a requirement for LightFM to perform well?
