### ISSUE TITLE
BPR loss have lower AUC than WARP

### ISSUE THREAD

**Issue by Ivanclj** [lyst/lightfm#436]
Hi,

I am building a recommendation engine for a side project right now and I tried both BPR and WARP loss in the model building phase. Since in the document it states that BPR is used to optimize AUC and WARP is used to optimize Precision@k. But after training and hyper parameter tuning for both loss, I found out that BPR generally have much lower AUC values compared to WARP. Am i doing something wrong or WARP is just a better loss function?

**Comment by maciejkula** [comment]
I think WARP is simply a better loss function: it outperforms BPR across the board in my experience.
