### ISSUE TITLE
Does Warp also work for negative interaction?

### ISSUE THREAD

**Issue by Ivanclj** [lyst/lightfm#437]
Hi,

I am currently training a rec sys using the Yelp dataset. It contains user rating of each restaurant on a scale of 0-5. I centered the rating by subtract each user's average rating and any rating > 0 I change them to 1 and any below 0 to -1. So  i have an interaction matrix contain 1 (user likes), 0 (user did not interact with), -1 (user dislikes). 

Originally, I was training using logistic loss according to the document. However, I found out that logistic is not giving me good result, so i switch to WARP just to see what it gives me. Surprisingly, WARP gave me a much higher AUC score and MRR. So I was wondering how does WARP train the model in the presence of negative interaction?  Does it take -1 as the negative sample or does it treat -1 and 0 both as negative samples? Is the way i am using WARP ok or do I need to change all -1 to 0 in order to make the interaction matrix only contains 1 and 0? But I also want to distinguish between user has not interacted with (0s) and user explicitly dislike (-1s), so I was hesitating changing all -1 to 0. 

Any advice would be greatly appreciated!

**Comment by maciejkula** [comment]
WAPR simply [drops](https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template#L831) all rows where the value is non-positive. There are good ways to use both implicit and explicit data, but they are beyond what LightFM does; for most recommender algorithms, I argue [against using ratings](https://maciejkula.github.io/2018/07/19/dont-use-explicit-feedback-recommenders/).
