### ISSUE TITLE
Ranking with weigths/confidence

### ISSUE THREAD

**Issue by CireS31** [lyst/lightfm#438]
**THIS IS A QUESTION NOT AN ISSUE**

Hello,

First of all, thank you for lightfm.

Can we imagine with lightfm to get a ranking with a weight/confidence level as follow (with the existing output from the tool)?

Example item top 3 ranking for user_1 and user_2:
user_1|user_2
-------|-------
1 item_18 80%  | 1 item_3   80%
2 item_5   60%  | 2 item_18 70%
3 item_14 60%  | 3 item_2     5%

**If yes, how to do it?**

Thank you in advance

**Comment by maciejkula** [comment]
This is not something supported in LightFM; [this paper](https://arxiv.org/pdf/1506.02142.pdf) on dropout as a Bayesian approximation might give you some ideas on how this might be implemented in general.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
