### ISSUE TITLE
Different predictions when adding user_features to predict()

### ISSUE THREAD

**Issue by abdelkarim336** [lyst/lightfm#439]
Hi,
I've built a lightfm model using user/items interactions and user features.

```
data_process=Dataset()
data_process.fit_partial(train_data['Id_user'].unique(), train_data['Id_item'].unique() , user_features=pd.unique(one_row_per_user[features_cols].values.ravel('K')))
```
My items_id ranges from 500 to 561, i'm generating predictions (3 predictions per user) for each user using the following code:

```
lfm_mapping=data_process.mapping()
nb_users=len(test_data['Id_user'].unique())
predictions=[]
for i in range(nb_users):
    user_id=test_data['Id_user'].unique()[i]
    predictions.append(model.predict(lfm_mapping[1][user_id],np.array(range(interactions_test.shape[1]))).argsort()[-3:][::-1])
```
This seems to work well even though it takes a lot of time to run for a big number of users,
the problem is that when I add the user features matrix as an argument for predict i get different scores for items, so my questions are:
1) Which predictions are correct, I mean with or without user_features matrix ?
2) Is there a faster way to generate code for every user ?

Thanks a lot

**Comment by maciejkula** [comment]
1. If you fit your model with features, you should pass features into `predict`.
2. Try profiling the code and seeing where the slow parts are.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
