### ISSUE TITLE
What does BPR learn in Movielens dataset? 

### ISSUE THREAD

**Issue by zjplab** [lyst/lightfm#440]
Movielens gives you only user ratings. But BPR algorithm only deals with implicit data. So what kind of preprocessing will lightFM do, or what the in the end does matrix factorization get?

**Comment by EralpB** [comment]
:+1: I would be happy if someone could clarify to avoid confusion

**Comment by maciejkula** [comment]
It will binarize the data to treat watches as positives, and non-watches as negatives.

You may well believe that only ratings > 3 (or similar arbitrary threshold) should be counted as positive: that's quite common in the recommender system literature.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
