### ISSUE TITLE
Usage with k-means?

### ISSUE THREAD

**Issue by Tjorriemorrie** [lyst/lightfm#443]
As a nescient beginner, I was wondering if it is possible to use knn clustering with the `get_user_representations`? I wish to cluster the users, and maybe the questions as well. Is it possible (i.e. do you have an example) or would you have a better solution?

**Comment by impaktor** [comment]
I assume it should be possible. Alternative, one could use an auto encoder, to compress the latent space further, or just use DBscan + tSNE?

**Comment by impaktor** [comment]
I haven't read this, but looks like they're clustering in latent space:
https://www.zillow.com/data-science/embedding-similar-home-recommendation/
