### ISSUE TITLE
About online update or delta training of model 

### ISSUE THREAD

**Issue by FrancisFok** [lyst/lightfm#446]
Suppose a model have been trained by a dataset D, could it be possible to re-train the model by a dataset (D + D') where D' is a new records such that starting all weights from the previous model?

I have read the source code 'lightfm.py'. There is a initialization or _reset_state in the code. Is it possible to add a controlling flag to by-pass the re-initialization?

**Comment by maciejkula** [comment]
Yes: have a look at [fit_partial](https://lyst.github.io/lightfm/docs/lightfm.html#lightfm.LightFM.fit_partial).

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
