### ISSUE TITLE
R-Precision instead of @K

### ISSUE THREAD

**Issue by ajhepburn** [lyst/lightfm#448]
Hi, I was wondering how to retrieve the R-Precision of a model? I understand that R-Precision is Precision@K where K equals the number of relevant documents returned. So I wanted to ask, how would it be possible to retrieve the total number of relevant documents returned during training/testing?

I'm trying to compute the F1 Score of my recommendation model and I think this is done with an overall Precision/Recall? Or am I better just using MRR?

**Comment by ljmartin** [comment]
Hi @ajhepburn , 
I was after this as well and wrote the below to calculate it. _Please_ use at your own risk, I have not checked if it works but it seems reasonable to me. I am also going on a fresh understanding or R-precision, where you change k to be equal to the number of positive records for each individual user. So if user=10 has 15 positive ratings, k=15. Note that it doesn't count the users where there was not a single test record, because precision was always going to be zero for these users since k=0.

```
#predict ranks of all test users
ranks_matrix = model.predict_rank(test)

precision_relevant = list()
for row in range(ranks_matrix.shape[0]):
    ranks_row = ranks_matrix.getrow(row).data
    if len(ranks_row>0):
        relevant_docs = len(ranks_row)
        frac_relevant = len(np.where(ranks_row<relevant_docs)[0])/relevant_docs
        precision_relevant.append(frac_relevant)
```

**Comment by ljmartin** [comment]
If anyone has been using the above, then dont :) It doesn't count the known positives in R, so if you have two test positives and 8 train positives, R-precision would be equal to zero even if those positives were ranked top ten, along with the other 8 training positives. 

This is better, but a little bit slower:

```
train, test = cross_validation.random_train_test_split(sparse_mat)
test_predictions = model.predict_rank(test)

def calcRprecision(model, test_predictions_matrix, train):
    precision_relevant = list()
    #iterating over users:
    for row in tqdm(range(test_predictions_matrix.shape[0])):
        #gather the predicted ranks of the test positives, and also get the train positives 
        test_row = test_predictions_matrix.getrow(row).data
        train_row = train.getrow(row).data
        #check to see we have at least 1 test data point:
        if len(test_row>0):
            #total relevant docs is all the training and all the test known positives:
            relevant_docs = len(test_row) + len(train_row)
            frac_relevant = len(np.where(test_row<relevant_docs)[0])/relevant_docs
            precision_relevant.append(frac_relevant)
    
    return np.array(precision_relevant)

rp = calcRprecision(model, test_predictions, train.tocsr())
print(rp.mean())
```

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
