### ISSUE TITLE
Negative example sampling

### ISSUE THREAD

**Issue by JohnPaton** [lyst/lightfm#449]
Hello,

I was wondering if it's possible to influence which interactions come into consideration for sampling by BPR/WARP.These losses assume that "missing" interactions are negative, but I'm interested in the effect of filtering out those interactions that were not even possible. This can happen for short-lived items that were removed before the user's account was created, meaning that they had no chance to ever interact, even though they may have otherwise done so. This would help to reduce sparsity and seems like an intuitive choice to me, though I realize it would add additional complexity.

**Comment by maciejkula** [comment]
I agree that this is a good idea, but, as you say, it's not clear how to implement it in a way that's both simple and widely applicable.

One alternative approach is to express information about product's lifetimes in product features: this would help the model capture these relationships more easily.

**Comment by JohnPaton** [comment]
Do you have any recommendations on how that would look? The first thing that comes to mind is a real-valued `created_at` and `removed_at`, combined with a `created_at` for users. But that seems like a difficult feature to work with for the model.

**Comment by maciejkula** [comment]
Perhaps have an indicator variable for every month/quarter of your product history, set to 1 if a product was available during that time, and 0 otherwise? That might help.

**Comment by JohnPaton** [comment]
Ah that’s a great idea, thanks! I’ll look into it

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
