### ISSUE TITLE
What is the expected format of a dataset - binary, [-1,1], (1-5), (1-10)?

### ISSUE THREAD

**Issue by ljmartin** [lyst/lightfm#450]
Hi all,
Thanks for lightfm. 

What is the expected format of a dataset: binary, [-1,1], (1-5), (1-10)? I note that downloading the movielens dataset allows to set a 'minimum rating' which indicates to me a binary input, i.e. YES vs NO, but the actual values in the sparse matrix aren't [0,1], they're all 5. 

I've fit (using warp, which I realise now zeroes out negative values) on my dataset and despite the input being [-1,1] it was predicting results greater than 1. So i tried fitting on values in the range (0,10) and then the max predicted was around 6. 
Thanks!

I tried to make some minimal code. While this doesn't show values greater than the input, it does show values below the input which is nearly the same the same 'problem'. 

```
sparse_mat = scipy.sparse.coo_matrix(([0,0,0,1,1], ([0,0,0,1,1], [0,1,2,0,1])))
model = lfm.LightFM(no_components=5, loss='warp')
model.fit(sparse_mat, epochs=5, num_threads=1)
model.predict(user_ids=[0], item_ids=[0,1,2], user_features=None, item_features=None)
```

**Comment by ljmartin** [comment]
I read a bit further and realize that only explicit data should be input as [-1,1]. Implicit data with BPR or YARP can just be input as 1's. Still, this is returning predicted values greater than 1 to me?

**Comment by maciejkula** [comment]
The predictions only have meaning when used to sort products: their magnitude of sign is irrelevant, and they are not supposed to bear any relation to the values in the interactions matrix.

**Comment by ljmartin** [comment]
Great ! Thanks a lot
