### ISSUE TITLE
How lightfm work with short-living items ? 

### ISSUE THREAD

**Issue by andradron** [lyst/lightfm#452]
Unlike movielens, where we can recommend any film at any time, th
For example, we have user metadata like interests, categories he bought, etc. Item metadata like category, price, etc. And user-item interactions like purchasing. All items have a short lifetime when they could be bought, therefore all interactions can be made only during that period. New users are also coming every day. Recommendations have to contain only actual items. How does lightfm handle this situation?

**Comment by raphgt2** [comment]
Perhaps look at #449?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
