### ISSUE TITLE
Similar Items to Item A vs Prediction Based on user with only Item A

### ISSUE THREAD

**Issue by luciahouse33** [lyst/lightfm#456]
To give some background:

I preallocated a new user in my interactions matrix. And I fit the model on this interactions matrix. Then, I allow an input of items, which I then use to "fill in" the new user. I use fit_partial on this new interactions matrix. 

I then predict the top N recommendations using the model. 

I also calculate cosine similarity between items using the item embedding matrix. 

My question: 

If my new user only interacts with item A, why are the top N recommended items and the top N similar items not the same?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
