### ISSUE TITLE
Application crashes during training 

### ISSUE THREAD

**Issue by clappis** [lyst/lightfm#458]
Hello everyone,

I need to run a lightfm application inside a docker container.
This is my Dockerfile:

```javascript
FROM python:3.6.8-slim

WORKDIR /usr/src/app

RUN apt-get update \
        && apt-get install -y curl apt-transport-https gnupg2 build-essential libxml2 libxslt-dev gcc \
        && curl https://packages.microsoft.com/keys/microsoft.asc | apt-key add - \
        && curl https://packages.microsoft.com/config/debian/9/prod.list > /etc/apt/sources.list.d/mssql-release.list \
        && apt-get update \
        && ACCEPT_EULA=Y apt-get install -y msodbcsql17

RUN apt-get install -y unixodbc-dev

COPY requirements.txt ./
RUN pip install --no-cache-dir -v -r requirements.txt > install.log

ENV TZ=America/Sao_Paulo
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone

COPY . .

CMD ["python","-u","main.py"]
```

When my container is running, then error below is throwed:
[9496254.935906] traps: python[45650] trap invalid opcode ip:7f3bf6731489 sp:7ffd515191e0 error:0 in _lightfm_fast_openmp.cpython-36m-x86_64-linux-gnu.so[7f3bf670b000+49000]

This happens when I call method .fit()

**Comment by maciejkula** [comment]
It looks like the machine you're compiling on differs from the machine you are running on. You may want to change the compilation flags to something less performant but more architecture independent. You can do this by making changes to [setup.py](https://github.com/lyst/lightfm/blob/master/setup.py#L15).

**Comment by clappis** [comment]
Do you mean to remove the compiler flags [-ffast-math, -march=native, -fopenmp] ?

**Comment by maciejkula** [comment]
Yes. I would start with `-march=native`, then `-ffast-math`. I don't think it's `-fopenmp`.

**Comment by clappis** [comment]
I'll try it.
Thanks a lot for your help!

**Comment by clappis** [comment]
Works @maciejkula .
Thanks a lot!
