### ISSUE TITLE
Learning LightFM from an "Architectural" perspective - Several "basic" / "newbie" questions

### ISSUE THREAD

**Issue by keeppace** [lyst/lightfm#459]
I am brand new to Recommendation Engines, and have been spending the past few weeks getting up to speed.    I will admit it has been a while since I have coded (so I am not fluent in Python) - which I am sure would help me greatly answer these questions 

If nothing else, I hope these questions can serve as the basis to an "Intro to LightFM for those not a Data Scientist" ; )

I think I have progressed that I understand the Collaborative Model enough.   It is the Content Model that I am struggling with, more from a how to get the data ready and I guess setting my expectations as to what LightFM can / can't do 

**1.   Metadata Questions** 

My assumption is that I can have whatever Metadata for both the User / Item.    Since the Movie database is used consistently as an example,  lets make up some metadata attributes 

**User** 

- Age 
- Personality Type (Introvert / Extrovert) 
- Income 
- Sex
- Family Size 

**Movie**

- Movie Budget 
- Number of "A-List" Movie Stars
- Movie Running Length 

Questions 

1.  Can I assume that LightFM is creating the appropriate vectors for each of these attributes? 

2.  Specific to subsequent calls to LightFM,  lets say I have a new user - and I only know 3 of those 5 pieces of Metadata.   Will LightFM still be able to provide a recommendation ? 

**Metadata Format** 

One of the things that would be incredibly helpful to me, is if someone can explain how metadata information is presented to the LightFM Library.    (Again, its been a while since I have coded)  -   I ask, because as I look thru the LightFM documentation - I get a little confused.

For example, in the  Articles and Tutorials - specifically the MetaData Embeddings

http://building-babylon.net/2016/01/26/metadata-embeddings-for-user-and-item-cold-start-recommendations/

The beginning of the article shows adding tags to various metadata (which look like key/value pairs) .    Programmatically though, is this a matter of creating a User Table / Array and have each column representative of that particular metadata with a Value / 0 / Null ?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
