### ISSUE TITLE
add a 0 to the user embedding end got same result, why use this trick?

### ISSUE THREAD

**Issue by jt120** [lyst/lightfm#460]
for offical demo: annoy_nsmlib_example.ipynb

I found this description: "Basically we add a nomalizing factor to each item vector - making their distances equal with each other. Then when we query with a user vector, we add a 0 to the end, and the result is proportional to the inner producct of the user and item vectors. This is a sneaky way to do an aproximate maximum inner product search."

# question:
I use different method to calculate dot product, and got same result, so why not append 0 to vector and norm item vector?

# method 1:
```
user_id=3
r = item_embeddings.dot(user_embeddings[user_id])
index = np.argsort(-r)[:3]
[movielens['item_labels'][i] for i in index]
```

# method 2:
```
user_id = 3

norms = np.linalg.norm(item_embeddings, axis=1)
max_norm = norms.max()
extra_dimension = np.sqrt(max_norm ** 2 - norms ** 2)
norm_data = np.append(item_embeddings, extra_dimension.reshape(norms.shape[0], 1), axis=1)

u = np.append(user_embeddings[user_id], 0)
r = norm_data.dot(u)
index = np.argsort(-r)[:3]
[movielens['item_labels'][i] for i in index]
```

**Comment by maciejkula** [comment]
This question might be more appropriate in the annoy/nmslib github issues.

**Comment by jt120** [comment]
> This question might be more appropriate in the annoy/nmslib github issues.

thanks, maciejkula

finally, I found the answer from this paper 'Speeding Up the Xbox Recommender System Using a Euclidean Transformation for Inner-Product Spaces'
