### ISSUE TITLE
item_alpha and user_alpha meaning

### ISSUE THREAD

**Issue by bcc008** [lyst/lightfm#461]
Are Item_alpha and user_alpha L2 penalties just for item and user_features or do they also apply to the weights of the user/item latent factor as well? From the documentation it seems like they're applied to just the optional metadata/descriptive features. However, from cross-validation, I noticed that the best performing hyperparameters usually have small item and user_alphas so I am assuming they are also applied to the latent factors. In the original BPR paper, L2 regularization is similarly applied to the weights of the latent factors.

![image](https://user-images.githubusercontent.com/33501320/58595859-df67ca00-8226-11e9-9912-c2adfb8099bc.png)

**Comment by maciejkula** [comment]
Regularization applies to parameters you learn: in this case, the user and
item latent factors. Weights in the item and user features matrices are
fixed inputs into the model.

Feature latent factors and user/item latent factors are the same thing as
far as LightFM is concerned.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
