### ISSUE TITLE
Understanding precision @ k

### ISSUE THREAD

**Issue by nick-dewaide** [lyst/lightfm#462]
Hi, I have some questions about weights and precision in LightFM. It seems like a very powerful recommendation tool, but I am confused about how evaluation is working.

Why does .fit() on a LightFM object accept sample_weights, but precision_at_k() does not accept sample_weights?

If sample_weights tells us how highly the user rated an item, then how does it determine the number of positive samples in the test data without using weights? Based on experimentation, it looks like precision_at_k() still treats everything as equally weighted when I use weights for the test_interactions parameter.

If our weights for interactions are 0 to 20, is it possible to know what threshold LightFM uses for a positive interaction?

Thank you for the library and your support!

**Comment by EralpB** [comment]
this is an implicit recommender system, so everything is actually boolean there is no 0-20 scala there is 0 or 1 :)

I think weight is confusing for beginners (like me!) I learned that it's just used to adjust the learning speed of the algorithm. so if during the training user X is not recommended item L the algorithm "learns" by adjusting it's parameters, the length of the step is depending on the weight of that interaction.

I suggest you to map 0 to 0 and 1-19 to 1 and stop using weights.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
