### ISSUE TITLE
scikit-learn dependency should be required

### ISSUE THREAD

**Issue by davidesarra** [lyst/lightfm#466]
`scikit-learn` isn't required for the installation, however the module `lightfm.data` depends on it.

Tests are passing because `scikit-learn` is required (and used elsewhere) in the test suite.

However, importing the `data` module leads to importing `sklearn.preprocessing`, which in turn raises a `ModuleNotFoundError`.

The workaround is to explictly add `scikit-learn` to one's project requirements, but this is not ideal.

PR #464 aims to fix this issue by amending the installation requirements. Additional details are provided in the PR itself.

**Comment by impaktor** [comment]
Sounds like this can be closed now, yes?

**Comment by davidesarra** [comment]
Sure, #464 has now been merged.
