### ISSUE TITLE
Loss functions in LightFM

### ISSUE THREAD

**Issue by Hasham2424** [lyst/lightfm#472]
I recently came across LightFM while learning to train a recommender system. And so far what I know is that it utilizes loss functions which are logistic, BPR, WARP and k-OS WARP. I did not go through the math behind all these functions. Now what I am confused about is that how will I know that which loss function to use where?

**Comment by impaktor** [comment]
By testing. This is discussed in the manny issues already open, please refer to them. WARP is in general the best bet.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
