### ISSUE TITLE
Finding the best feature weight settings and dealing with missing feature values

### ISSUE THREAD

**Issue by DaStapo** [lyst/lightfm#473]
Let's say I have several features per item (price, category, color). Is it the right approach to simply  try out all combinations of weight values (1-5) and see which has the best results (e.g. setting weight to 5 for all color features and setting weight to 2 for all price features)? With a lot of data and features, it might be difficult to try out all possible combinations.

If for example with the explained approach we determine that the category feature requires a lot more weight, what is the best thing to do with an item that has no category? If we are convinced, that the missing category won't have correlations with anything else, is it still reasonable to add the feature `(item id, {category:NaN: 5})`? Wouldn't that worsen the model due to simply being heavy-weighted noise which dampens other features which might carry meaningful value?

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
