### ISSUE TITLE
Predicting item-user scores

### ISSUE THREAD

**Issue by zombiesingh** [lyst/lightfm#476]
Hi, I know that `model.predict(user_ids, item_ids, item_features=None, user_features=None, num_threads=1)` gives us **recommendation score for user-item pairs**

I would like to know how could we get the recommendation score for item-user pairs, that is given an item, the recommendation score for the given list of user_ids.

**Comment by impaktor** [comment]
I think this question has already been asked before, please see previous issues. One possiblilyt discussed back then, was just treat your users as items, and vice versa

**Comment by zombiesingh** [comment]
Thank you, @impaktor I had tried one way treating users as items and vice versa. But it didn't work. 
Then after you reiterated that fact, I tried again, this time rigorously vetting the data for training too. It works!
