### ISSUE TITLE
Illegal instruction (core dumped)

### ISSUE THREAD

**Issue by AlistairLR112** [lyst/lightfm#477]
(base) alistair@ip-xx-xx-x-xx:~$ python
Python 3.7.3 (default, Mar 27 2019, 22:11:17)
[GCC 7.3.0] :: Anaconda custom (64-bit) on linux
Type "help", "copyright", "credits" or "license" for more information.
>>> import lightfm
Illegal instruction (core dumped)

(base) alistair@ip-xx-xx-x-xx:~$ pip freeze | grep lightfm
lightfm==1.15

Does anyone know why I might be getting this error? I haven't changed anything on my server

**Comment by impaktor** [comment]
I suspect a minimum (non-)working example would help, and backtrace? Does lightfm examples on in the docs work?

**Comment by AlistairLR112** [comment]
I couldn't import lightfm at all without the core dumping.

I have fixed this by uninstalling lightfm via pip then reinstalling via conda.

**Comment by dbalabka** [comment]
The same problem appears for me. I have installed lightfm from conda docker image `continuumio/miniconda3`. Here is some debug information:
```
>>> import lightfm

Program received signal SIGILL, Illegal instruction.
0x00007f5fcc64c444 in PyInit__lightfm_fast_openmp () from /opt/conda/lib/python3.7/site-packages/lightfm/_lightfm_fast_openmp.cpython-37m-x86_64-linux-gnu.so
```

**Comment by dbalabka** [comment]
To fix this issue I have recompiled the package inside the docker image via conda:
```
name: base
channels:
  - anaconda
  - conda-forge
dependencies:
  - python=3.7
  - cython=0.29.14
  - pip:
      - git+https://github.com/lyst/lightfm.git@1.15
```
