### ISSUE TITLE
what if the feature name is the same as the item name

### ISSUE THREAD

**Issue by peterpanhjh123** [lyst/lightfm#478]
hi, i have a problem .the code is shown below
`dataset = Dataset()
ISBN=[0,1,2,3,4]
Book=[0,1,2,3,1]
dataset.fit_partial(items=ISBN,item_features=Book)`

that is my item name is 0/1/2/3/4, and my feature name  let's say is price ,so that will be 
0,1,2,3,1 like i mentioned above

i check the source code in fit_partial,
`        if items is not None:
            for item_id in items:
                self._item_id_mapping.setdefault(item_id, len(self._item_id_mapping))

                if self._item_identity_features:
                    self._item_feature_mapping.setdefault(item_id, len(self._item_feature_mapping))`

then i think i will not get the mapping correctly , right? please correct me if i am thinking the wrong way. if i am right , that is i should transform the feature name to another name ? or the lightfm support this but i don't know . glad to hear your answer ,thanks a lot

**Comment by peterpanhjh123** [comment]
by the way i wonder how you calculate auc in auc_score function?do you treat all nonzero entries as positive samples and zero entries as negative.

i use predict to calculate the scores and feed them to the metrics.roc_auc_score function(the sample label is defined above),i get 0.62 auc .but i call the auc_score function ,i get 0.86 auc

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
