### ISSUE TITLE
User Explicit profile

### ISSUE THREAD

**Issue by katsiatyna** [lyst/lightfm#488]
Hello,
Thank you for a great model!
I am trying to build a news recommendation engine. I have already figured out (I hope :)) how to add time-decay and all, but there is still one thing I can't seem to figure out (I have read all open issues).
So, the news articles are described by keywords (**tags**), which work well as item features. But we also want to display those tags and allow user to **"follow"** a tag, which indicates user's interest in this particular tag. Aside from regular filtering by tag, we also want to **include these "interests" into user profile for recommendation**. Is there a way (or a workaround) for that?
I know I can add user's followed tags as user features, but in that case I will have the same set of tags duplicated as separate features (user and item). I feel like I am missing something... 
In general, does your model have a representation of "user profile" and how is it implemented? Is there a way to modify this profile explicitly?
My only idea for now is to save user profile (tags + weights) on my side (from the items that user has interacted with), train LightFM with **item features only**, and then **calculate user embedding user item features** according to user's profile, and make my own predict method. Will that make any sense?

Thank you in for any advice,
Kate

**Comment by impaktor** [comment]
If you don't want to add tagged features as separate user feature, you could test to increase weight of that feature, perhaps.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
