### ISSUE TITLE
Regarding server requirements

### ISSUE THREAD

**Issue by elieobeid7** [lyst/lightfm#490]
I know this isn't the best place to ask about it, but what is the recommended ec2 instance to do product recommendations in production?

**Comment by elieobeid7** [comment]
Where is the right place to ask about the server requirements for using this library then? the thing is ML and stuff are resource-heavy.

You as a developer might not care, but when I was given an ML project they told me 3 things.

- Present an architecture: I did
- We give you a dataset, we want you to tell us what ML  you want to use, we want you to use one that uses TensorFlow: Okay I told the team we're going to use lightfm
- Okay great before you start coding, we want you to tell us what is the appropriate server to buy for this library, we'd like to generate daily recommendations for our uses, we get between 10k and 30k users per month, so we have to know what are the server requirements for the library you chose to estimate a budget and in order to know if we can keep it running and generate real-time recommendations or not.

I answered 2 out of 3 questions, who are the qualified people to answer the last question? not me obviously because I haven't used it before, and this question needs to be answered obviously so that we know if we stick with the library or not and because the client needs to know how much money he will be spending.

That leaves me with 2 choices then:

- To google around and try to find the best estimation I could, which is what I did because I asked this question 25 days ago, the client ain't gonna wait months for me to get an answer here
- I could also try to ask the people who used this library and see what they have to say.

Now, apart from this very issue tracker, do you think there's a hidden place I could find lightfm users? I don't think so, therefore I had to ask it here.

Anyhow, I'm going to close this, because we ended using amazon personalize, why? simply because the [pricing](https://aws.amazon.com/personalize/pricing/) is easy to calculate.

For anyone intending to use this project for commercial purposes or more specifically for a client, this question is vital, because if the team is unable to send a clear quotation, he'll move on, as we did.

**Comment by maciejkula** [comment]
Hey, I'm sorry you didn't find any information to help you.

It's very hard to answer your question accurately, as there are so many possible factors affecting the answer. In many cases, it's easiest to try to simulate your usage. 

In this case, let's say we have 30k users and 10k possible items. The most expensive thing we can do is to generate recommendations for all users and all items every day; this is our cost upper bound. To get an idea of how expensive that is, we can simulate the cost of using a LightFM model with 30k users and 10k items.

A fitted LightFM model gives you two embedding matrices of (30k x embedding_dim) and (10k x embedding_dim). Generating the recommendations is equivalent to multiplying the two matrices.

I ran a back-of-the-envelope calculation like this in this [colab](https://colab.research.google.com/drive/1usEw7g7om6a9NN1jSk3wJYB6s3TSIwon). It appears it takes roughly 700 nanoseconds to calculate the recommendations for all items and all users.

For a problem of this size, you don't need a large server at all; you may not even need a server for more than a couple of minutes a day if you stash the results in a cache. If, however, you have 10 million items, the problem changes, and you will need to compute your own numbers.

It feels like you're taking a measured approach to your project, and I'm sure it'll be successful. Good luck!

**Comment by elieobeid7** [comment]
@maciejkula Thank you so much for answering the question. I made mistakes in my answer above.

- We have 10k to 30k users per day not per moth
- Around 300k items to recommend from, the library is growing by 100 items daily
- We want something that's as close as possible to real-time recommendations, if possible

That's what I was told.
