### ISSUE TITLE
Recommending something new to user/Based on frequently bought together items..

### ISSUE THREAD

**Issue by sukritkb** [lyst/lightfm#492]
Hi,
I'm new to lightFM and currently trying to build a cross sell recommendation system using the same..
I have a user item matrix.. based on which i would like to recommend a new item to the user which he already hasnt bought.. 
I have already trained one model and using the sample recommendations im getting the same items which the user has already purchased.. would rather that there are new recommendations which the user is more likely to buy

**Comment by kshitijyad** [comment]
You will have to manually tweak that. The login is that give all the items purchased a large negetive value so that the recommendation score for those items become very low and doesn't come in the top recommended results.

Interation is the sparse interaction matrix.
Click content is the content which was click/purchased


 ```
        clicked_content = interactions[user,:].toarray() # Get the ratings from the training set ratings matrix
        clicked_content = clicked_content.reshape(-1) + 1 # Add 1 to everything, so that items not purchased yet become equal to 1
        clicked_content[clicked_content > 1] = -10 # Make everything already purchased high negetive
        
        predictions=self.model.predict(user,np.arange(len(self.itemID_to_index)))
        recommendations=clicked_content+predictions
```

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
