### ISSUE TITLE
Predict new items for users

### ISSUE THREAD

**Issue by andrewng88** [lyst/lightfm#495]
Following this link, I was able to predict items for new users. 
https://stackoverflow.com/questions/46924119/lightfm-handling-user-and-item-cold-start

However, when I modified the code to predict users for new items, I obtained the following error. 
https://i.imgur.com/hNRV761.png

```
scores = model.predict(np.array(df_tags_customers["customers_id_num"]), np.array(0), user_features=customer_features, item_features=item_features)

explanation :
np.array(df_tags_customers["customers_id_num"]) ( the whole list of customers )
np.array(0) ( i'm not sure about this as the stackoverflow example uses 0 for new user )
user_features=customer_features ( the features all customers )
item_features=item_features ( the feature for the new item )
```

Please advise on how to correct the error. Thanks.

**Comment by SimonCW** [comment]
I’m closing this issue because it has been inactive for a long time. If you still encounter the problem, please open a new issue.

Thank you!
