### ISSUE TITLE
installation problem

### ISSUE THREAD

**Issue by shashank2123** [lyst/lightfm#496]
base) C:\Users\shash>pip install lightfm
Collecting lightfm
  Using cached https://files.pythonhosted.org/packages/e9/8e/5485ac5a8616abe1c673d1e033e2f232b4319ab95424b42499fabff2257f/lightfm-1.15.tar.gz
Requirement already satisfied: numpy in c:\programdata\anaconda3\lib\site-packages (from lightfm) (1.16.5)
Requirement already satisfied: scipy>=0.17.0 in c:\programdata\anaconda3\lib\site-packages (from lightfm) (1.3.1)
Requirement already satisfied: requests in c:\programdata\anaconda3\lib\site-packages (from lightfm) (2.22.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\programdata\anaconda3\lib\site-packages (from requests->lightfm) (2019.9.11)
Requirement already satisfied: idna<2.9,>=2.5 in c:\programdata\anaconda3\lib\site-packages (from requests->lightfm) (2.8)
Requirement already satisfied: urllib3!=1.25.0,!=1.25.1,<1.26,>=1.21.1 in c:\programdata\anaconda3\lib\site-packages (from requests->lightfm) (1.24.2)
Requirement already satisfied: chardet<3.1.0,>=3.0.2 in c:\programdata\anaconda3\lib\site-packages (from requests->lightfm) (3.0.4)
Building wheels for collected packages: lightfm
  Building wheel for lightfm (setup.py) ... error
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"'; __file__='"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' bdist_wheel -d 'C:\Users\shash\AppData\Local\Temp\pip-wheel-imqk6zf5' --python-tag cp37
       cwd: C:\Users\shash\AppData\Local\Temp\pip-install-h7huaehr\lightfm\
  Complete output (23 lines):
  Compiling without OpenMP support.
  running bdist_wheel
  running build
  running build_py
  creating build
  creating build\lib.win-amd64-3.7
  creating build\lib.win-amd64-3.7\lightfm
  copying lightfm\cross_validation.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\data.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\evaluation.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\lightfm.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\_lightfm_fast.py -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\__init__.py -> build\lib.win-amd64-3.7\lightfm
  creating build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\movielens.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\stackexchange.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\_common.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\datasets\__init__.py -> build\lib.win-amd64-3.7\lightfm\datasets
  copying lightfm\_lightfm_fast_no_openmp.c -> build\lib.win-amd64-3.7\lightfm
  copying lightfm\_lightfm_fast_openmp.c -> build\lib.win-amd64-3.7\lightfm
  running build_ext
  building 'lightfm._lightfm_fast_no_openmp' extension
  error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
  ----------------------------------------
  ERROR: Failed building wheel for lightfm
  Running setup.py clean for lightfm
  ERROR: Command errored out with exit status 1:
   command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"'; __file__='"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' clean --all
       cwd: C:\Users\shash\AppData\Local\Temp\pip-install-h7huaehr\lightfm
  Complete output (3 lines):
  Compiling without OpenMP support.
  running clean
  error: [WinError 2] The system cannot find the file specified
  ----------------------------------------
  ERROR: Failed cleaning build dir for lightfm
Failed to build lightfm
Installing collected packages: lightfm
  Running setup.py install for lightfm ... error
    ERROR: Command errored out with exit status 1:
     command: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"'; __file__='"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shash\AppData\Local\Temp\pip-record-c2doi7dd\install-record.txt' --single-version-externally-managed --compile
         cwd: C:\Users\shash\AppData\Local\Temp\pip-install-h7huaehr\lightfm\
    Complete output (7 lines):
    Compiling without OpenMP support.
    running install
    running build
    running build_py
    running build_ext
    building 'lightfm._lightfm_fast_no_openmp' extension
    error: Microsoft Visual C++ 14.0 is required. Get it with "Microsoft Visual C++ Build Tools": https://visualstudio.microsoft.com/downloads/
    ----------------------------------------
ERROR: Command errored out with exit status 1: 'C:\ProgramData\Anaconda3\python.exe' -u -c 'import sys, setuptools, tokenize; sys.argv[0] = '"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"'; __file__='"'"'C:\\Users\\shash\\AppData\\Local\\Temp\\pip-install-h7huaehr\\lightfm\\setup.py'"'"';f=getattr(tokenize, '"'"'open'"'"', open)(__file__);code=f.read().replace('"'"'\r\n'"'"', '"'"'\n'"'"');f.close();exec(compile(code, __file__, '"'"'exec'"'"'))' install --record 'C:\Users\shash\AppData\Local\Temp\pip-record-c2doi7dd\install-record.txt' --single-version-externally-managed --compile Check the logs for full command output.

please help me with this issue i don't know what to do?

**Comment by ginger0106** [comment]
hey I have the same problem, have you fix it? thanks

**Comment by rbcabreraUPM** [comment]
same problem using pipenv.

**Comment by BILLXZY1215** [comment]
same issue... maybe it requires Visual C++?
