### ISSUE TITLE
About build interaction matrix

### ISSUE THREAD

**Issue by xiaop1987** [lyst/lightfm#50]
I'm reading the code of warp in test_movielens , get one problem about the input, why make all values > 4.0 to 1s and  <= 4.0 to -1s?

**Comment by springcoil** [comment]
Your interaction matrix needs to be positive and negative. The value 4.0 is arbitrary you could pick 3.0 for example.

**Comment by springcoil** [comment]
Is this correct @maciejkula ?

**Comment by maciejkula** [comment]
Yes, you need to do this for logistic loss.

For WARP loss you only need positives, as the negatives are sampled from other users' interactions. So in that sense this is not necessary. I guess the interpretation here is that only values above some X are actual positives.

**Comment by xiaop1987** [comment]
@springcoil  @maciejkula Thanks very much for your attention, 
I may had big problem about understanding WARP loss, I made the items(movies in this case) that current user rated as the positive items and the rest items as negative items for current user.

**Comment by maciejkula** [comment]
@xiaop1987 are you happy about this answer? Or can I expand more?

**Comment by xiaop1987** [comment]
@maciejkula surely I'm happy, thanks a lot :).

 I take this step as making explicit feedback training data, but when I reading the example/movielens/readme.md which said that warp loss is used in implicit feedback, did I miss anything?

btw: I'm implementing warp loss in [spark](spark.apache.org) as  recommending algorithm, but the  result is not so good, would you mind if I posted some problems about warp loss(wsabie)  by email?

**Comment by maciejkula** [comment]
Yes, WARP loss is for implicit data. So this step basically drops anything less than 4 (but you could equally well leave everything in).

Sure, should I drop you an email at list.gutj@gmail.com?

**Comment by xiaop1987** [comment]
@maciejkula  yes, that would be very appreciated

**Comment by maciejkula** [comment]
Done, let me know if you didn't get it!
