### ISSUE TITLE
Interpretation of prediction Score(Combination of positive and negative)

### ISSUE THREAD

**Issue by yashkan27** [lyst/lightfm#505]
Hi,
I am calculating the scores through predict function after providing only the interactions sparse matrix.
I am using the "warp" loss so all my positive interactions are 1 and negative interactions are 0.
When getting the resulted scores I sorted the scores in Descending order. But what should I do when dealing with negative scores? (Should I get the absolute value of the scores). Also, we can use events such as clicking, added to cart and buying?
Thanks

**Comment by ljmartin** [comment]
The scores are for ranking and do not correspond to a predicted rating. So the absolute value doesn't matter - just the relative value. Which means you can keep the scores as they are and just 'recommend' the top 10 products, no matter what their value is. 

For clicking/cart/buying, yes you can either treat these as positive interactions and add a 1 to the interactions matrix as you already have. Or if you'd like them to have a different weight, you will need to add a separate column (i.e. a column for 'clicked on product X')  to the interaction matrix and then pass in values for each column for 'sample_weight' in the fit method.

**Comment by yashkan27** [comment]
Thanks, @ljmartin.
Just to clarify, If I need to make use of event feature(View, click, buy) then
1. I need to replace the corresponding 1's to their event value(1 for view,2 for click etc) and change loss function. 
OR
2. As you mention above. Adding separate columns for viewing and clicking. Can you guide me on how to add a column so that we can represent every click of the user on every product with the single column?

**Comment by ljmartin** [comment]
1. Keep using just the '1'. With implicit feedback, buying or viewing or clicking are all counted as a '1'. If you want to treat them separately (say buying is very important feedback to you, but viewing is not very important feedback to you), then you would have to create the separate columns - one column for Bought, one for Clicked, and one for Viewed
2. I dont know what format your input data is in. But if it's a numpy array you can just use `np.hstack`:

```
interaction_matrix = #your interaction matrix
clicks = #a single column array with a 1 for each customer that clicked on this item

new_interaction_matrix = np.hstack((interaction_matrix, clicks))
```
