### ISSUE TITLE
adding delta rating data of users and items

### ISSUE THREAD

**Issue by eveTu** [lyst/lightfm#506]
Hi,  
I am trying to build a hybrid recommendation model and I need a bit of help to understand the fitting in the real-world process.

The `fit` function initializes the model prediction with the current data that exists.
and the `fit_partial` supposed to add a delta data of user-item interactions without training all the data again.
for example: if I have 100 rows interaction in the first init - and I add now 40 interaction - the new model will be learned with 140 interaction rows.

**BUT** 

what about new user/product features? should the `fit_partial` **item_features** include all the existing items plus the new ones?  and the user_features include all the existing users include the exist and the new ones? 
for example, if added 4 new users to the rating area, and the previous unique users were 10, now the nunique user_features will be  14 users or only the delta?  

**Thanks a lot for the help and the detailed documentation**

**Comment by impaktor** [comment]
This question has been asked and answered very many times here on the issue page, please look though the open and closed issues.

In summary, if you want to add new users/products you need to train a new model. There are methods to work around this.
