### ISSUE TITLE
How to partial train an existing model for a new user interactions to items?

### ISSUE THREAD

**Issue by Gaurav470** [lyst/lightfm#509]
Hi,
I have a dataset which contains user-item interactions with item features available. (no user features are present) 
New users will be added to the dataset which are not previously present i.e. the New User - Item interaction is not present.
So will i have to re-train my whole model for every New User addition in the dataset every time a new user is introduced.
A suggestion/solution will be really helpful.
Thanks in advance.

**Comment by impaktor** [comment]
> So will i have to re-train my whole model for every New User 

Yes.

Please read previous issues. It's been answered many times.
