### ISSUE TITLE
How do i get specific recommendations for a user based on his categories selected?

### ISSUE THREAD

**Issue by Gaurav470** [lyst/lightfm#511]
Hi,
My data consists of user and video interactions with video meta-data consisting of a number of features including the category of the video.
An existing user hits my API with the user id as well as his categories he want to watch the videos of.
Where should i put a filter to the recommended list so that only videos of those particular categories received through the API of the user gets recommended to him only.

**Comment by andodet** [comment]
Even if probably inefficient, I believe a way might be to retrieve all recommendations for the user and filter the right categories through a lookup table of some sort.

**Comment by zkid18** [comment]
You can either pre-filter results or post-filter. Try both approaches and compare them based on your metrics. [This](https://link.springer.com/chapter/10.1007%2F978-3-642-03964-5_32) paper might be a good starting point.

**Comment by Gaurav470** [comment]
> Even if probably inefficient, I believe a way might be to retrieve all recommendations for the user and filter the right categories through a lookup table of some sort.

**Comment by Gaurav470** [comment]
Thanks for the reply. I post filtered my categories.
