### ISSUE TITLE
How to predict

### ISSUE THREAD

**Issue by AjiNugroho** [lyst/lightfm#513]
hi, i have trained my model with this
``` 
model.fit(interactions,         #this is my interaction csr format (uids,iids,rate)}
          user_features,          #format csr (uids,[feature1,feature2,..])
          item_features,          #format csr (iids,[feature1,feature2,..])
          weights,epochs=5,num_threads=2, 
          verbose=True)
```
and got auc 0.97 that's great.

then i tried to make predictions at a specific user id that appear during training with 
```
scores = model.predict(
            uid,         #single user_id
            item_id, 
            item_features=item_features,
            user_features=user_features)
```
but got error
`Number of user feature rows does not equal the number of users`

what's wrong with my code ? were we need to predict all user_ids ?

thanks in advance

**Comment by impaktor** [comment]
do note, the uid needs to be the index of the matrix the model uses, i.e. 0...N-1, for N users. and I'm venturing a guess that you should only send in the features for _that_ user, not all features for all users?

**Comment by AjiNugroho** [comment]
@impaktor 
i created interaction, user feature, item feature, using Dataset(). 
how can i know what index of my uid should be ?
please tell me how to convert those uid into index. thanks a lot for your help.

**Comment by AjiNugroho** [comment]
sorry sir @impaktor 
i had tried your instruction
```
model.predict(
uid,        #single user_index
item_ids, #all item index
user_feature, #sparse matrix np.int32 with shape 1x(number of all user feature)
item_feature #sparse matrix np.int32 with shape number of item_ids x number off all item feature
)
```
but still got an error 
Exception: Number of user feature rows does not equal the number of users

was there any missing ?
thanks
