### ISSUE TITLE
Predictions using only item features and no user features

### ISSUE THREAD

**Issue by chakra1166** [lyst/lightfm#516]
Hi,

I am trying to understand if the lightfm can make predictions if it is trained only with item features and no user features. Basically we are using word embeddings for item features and would like to predict for a new item in production. We will re training this model regularly so it is fine if we can't predict for new users

Thanks

**Comment by zkid18** [comment]
You certainly can! You need to create a Dataset and pass your item embeddings in a proper format. Something like this:

```
dataset = Dataset()
dataset.fit(
        df['user_id'].unique(),
        df['item_id'].unique()), 
        item_features = df_train[item_features_list].values.flatten,
)
```

You can [refer](https://making.lyst.com/lightfm/docs/examples/dataset.html) this tutorial
