### ISSUE TITLE
Pre-processing support

### ISSUE THREAD

**Issue by zkid18** [lyst/lightfm#517]
Hi, Maciej Kula, thanks for building such a great tool. I wonder if you plan support of pre-processing (eg. normalization) in the LightFM's roadmap? For example [Surprise](https://github.com/NicolasHug/Surprise) offer tools for handling data pre-processing.

**Comment by maciejkula** [comment]
I think for now I'm happy for folks to use a combination of numpy/sklearn to do their own processing.
