### ISSUE TITLE
how can we give recommendations for new user if we only have user and item interaction data for new user

### ISSUE THREAD

**Issue by namansahore** [lyst/lightfm#540]
Hello team, 

I have a data-set like user movie matrix, in such a way suppose every row and column has unique user and movie respectively. 
Now let we don't have the ratings but we have whether the user watched the movie or not. 

Let, if we have a new user N, with information that what movies he/she already watched from our existing data set. So now how can we give recommendations of new movies using LiftFM model.

Regards,

**Comment by johannb75** [comment]
Hello @namansahore.
I'm facing the same issue
Have you found any solution ?
