### ISSUE TITLE
How to create feature_matrix when using hybrid model

### ISSUE THREAD

**Issue by dabasmoti** [lyst/lightfm#571]
Hi,
There are many issues about low p@k when using hybrid model , i am struggling with the same issue
the preformance of p@k 
pure cf = 0.28
hybrid = 0.23
in the docs there is a note that i am not understand 

`Note: when supplying feature matrices, an implicit identity feature matrix will no longer be used. This may result in a less expressive model: because no per-user features are estiamated, the model may underfit. To combat this, include per-user (per-item) features (that is, an identity matrix) as part of the feature matrix you supply.`

What does it means "as part of the feature matrix you supply"?
Do I need to concat it? How?
Thanks

my code is:
```

def create_feature_list(df_,cols):
    feature_list = []
    for col in cols:
        feature_list += list(set(df_[col].to_list()))
    return feature_list

def build_features(df_):
    return [(row[0],
             [row[i] for i in range(1,len(row))]) 
            for row in df_.itertuples(index=False)]


def train_fm(train_,epochs=30,items_features= None,users_features=None,loss='warp',n_comp=64):
    model_ = LightFM(loss=loss,no_components=n_comp)
    model_.fit(train_, epochs=epochs,
              item_features=items_features,
              user_features=users_features, 
              num_threads=16,
              verbose=True)
    return model_

items = uid[['article_id','section_primary','writer_name']].drop_duplicates().reset_index(drop=True)
users = uid[['uid','popular_section','popular_platform','popular_sources']].drop_duplicates()

dataset = Dataset()
features_list = create_feature_list(items,cols=['section_primary','writer_name'])
user_features_list = create_feature_list(users,cols=['popular_section','popular_platform','popular_sources'])

dataset.fit(users=uid.uid.unique(),
            items=uid.article_id.unique(),
            item_features=features_list,
            user_features=user_features_list)

(interactions, weights) = dataset.build_interactions((x.uid,x.article_id) for x in uid.itertuples())


item_features = dataset.build_item_features(build_features(items))
user_features = dataset.build_user_features(build_features(users))

tr,te = random_train_test_split(interactions,test_percentage=0.2)

model_with_features = train_fm(tr,users_features=user_features,items_features=item_features,loss='warp')

evaluate_fm(model_with_features,te,tr,users_features=user_features,items_features=item_features)
```

**Comment by SimonCW** [comment]
Hi @dabasmoti , 

the `Dataset()` class has two parameters that handle the creation of the identity features for you ([Docs](https://making.lyst.com/lightfm/docs/lightfm.data.html#lightfm.data.Dataset)). Note that the default value is True. You can also see this from the dimensions of your item_features and user_features. Your item_features should have the dimensions (n_items, (n_item_features  + n_items)). If you set ` item_identity_features=False` you should get a matrix of dimensions (n_items, n_item_features). 

Getting worse metrics with additional meta-data is not unheard of, see: https://github.com/lyst/lightfm/issues/430
Maybe your model is performing better for cold-start users / items?

**Comment by SimonCW** [comment]
I tried to refactor the docs a bit to clarify this. You can have a look and comment here: #574

Closing this. Feel free to reopen if your issue isn't solved.
