### ISSUE TITLE
lightfm features size issues

### ISSUE THREAD

**Issue by elliebiessek** [lyst/lightfm#576]
I have managed to train the model successfully both with and without user/item features, but I can't evaluate the model with features due to size incompatibility. 
My train interactions are 39326 x 2569
My test interactions are 39326 x 2569
My user features (from train) are 39326 x 2577 (because I merged 2569 with 8 extra user features)
My item features (from train) are 2569 x 39326

Question 1. which dimension is wrong?
Question 2. I know that for train:
train_auc = auc_score(model2, train_interactions, train_user_features, train_item_features).mean()
but for test_auc is it 
auc_score(model2, test_interactions, test_user_features, test_item_features).mean()
or
auc_score(model2, test_interactions, train_user_features, train_item_features).mean()
?

**Comment by SimonCW** [comment]
Hi @elliebiessek 
Where are the test_user_features and test_item_features coming from? Unless I am completely mistaken, you shouldn't need these. Which item/user features have been interacted with is handled "internally" through the interactions matrix you provide. Also, something seems to be off with your function calls to auc_score, I'd recommend to use named function arguments for clarity and to avoid bugs.

I recommend to use the dataset class to build train and feature matrices if you haven't done already: https://making.lyst.com/lightfm/docs/lightfm.data.html. 

Maybe it also helps to go through the hybrid model example in the docs: https://making.lyst.com/lightfm/docs/examples/hybrid_crossvalidated.html

And lastly, I am trying to improve documentation a bit concerning the use of user/item feature. Maybe the WIP already helps you. If not, I would welcome your feedback: 
https://github.com/lyst/lightfm/pull/574/files

**Comment by elliebiessek** [comment]
Dear Simon
Thank you so much for your comprehensive answer. This sounds very helpful! Of course it will take me time time to try to implement it and see if it works but I haven't used the build in method to create the features so maybe that will help. I have used the method no 2 (features plus interactions) but this joined matrix is fed to user/item features but for the interactions I only passed interactions. The model trains fine but obviously something is wrong as it doesn't evaluate due to shape error. Will check this build in method but thank you so much for your help!
Ellie
    On Saturday, 19 December 2020, 11:24:23 GMT, Simon Weiß <notifications@github.com> wrote:  
 
 


Hi @elliebiessek
Where are the test_user_features and test_item_features coming from? Unless I am completely mistaken, you shouldn't need these. Which item/user features have been interacted with is handled "internally" through the interactions matrix you provide. Also, something seems to be off with your function calls to auc_score, I'd recommend to use named function arguments for clarity and to avoid bugs.

I recommend to use the dataset class to build train and feature matrices if you haven't done already: https://making.lyst.com/lightfm/docs/lightfm.data.html.

Maybe it also helps to go through the hybrid model example in the docs: https://making.lyst.com/lightfm/docs/examples/hybrid_crossvalidated.html

And lastly, I am trying to improve documentation a bit concerning the use of user/item feature. Maybe the WIP already helps you. If not, I would welcome your feedback:
https://github.com/lyst/lightfm/pull/574/files

**Comment by SimonCW** [comment]
Hi @elliebiessek
I'm happy I could help! I'm closing this then.

**Comment by ankurrajdev** [comment]
Hi @SimonCW,
I am wondering the same. Which one to use out of the following:

```train_auc = auc_score(model2, train_interactions, train_user_features, train_item_features).mean()
but for test_auc is it
auc_score(model2, test_interactions, test_user_features, test_item_features).mean()
or
auc_score(model2, test_interactions, train_user_features, train_item_features).mean()
?```

If the data is chronological, the values in user_features can differ. For instance, take average_order_value. It should be different if we are evaluating test and train separately. If we use the same one i.e. train, I would think that would cause data leak.

It awould be great if you can confirm this.

**Comment by SimonCW** [comment]
Hey @ankurrajdev,

You shouldn't split your user and item features by test and train, this is handled automatically by the interactions matrix you use, ie. if you use test interactions, only the item and user features corresponding to these test interactions will be used.
