### ISSUE TITLE
Dealing with Missing Item Features 

### ISSUE THREAD

**Issue by keryums** [lyst/lightfm#577]
Hello,

How does this package deal with the case of **passing in item features for fewer items than is in the user-item utility matrix**? We've noticed that the model will train and we can extract item representations from the trained model even without explicitly imputing for these missing item features.

Thanks

**Comment by SimonCW** [comment]
Hi @keryums

maybe this excerpt from the notes in the documentation is helpful: 

> If no feature matrices are provided to the lightfm.LightFM.fit() or lightfm.LightFM.predict() methods, they are implicitly assumed to be identity matrices: that is, each user and item are characterised by one feature that is unique to that user (or item). In this case, LightFM reduces to a traditional collaborative filtering matrix factorization method.
https://making.lyst.com/lightfm/docs/lightfm.html

If you pass in features to the fit calls and you have used the built-in dataset construction, than adding one "identity feature" per user and item is also the default. See: https://making.lyst.com/lightfm/docs/lightfm.data.html#lightfm.data.Dataset

If this doesn't clear things up, maybe you could provide a concrete example, e.g. shape of your matrices, way of constructing them.

**Comment by keryums** [comment]
Thank you that makes sense!

Ker-Yu
415-312-2148

**Comment by SimonCW** [comment]
Perfect, then I'll close.
