### ISSUE TITLE
[Troubleshooting] Illegal Instruction when calling model.predict in Docker image

### ISSUE THREAD

**Issue by parhamfh** [lyst/lightfm#604]
Hi! We have a setup where we create Docker images using LightFM in Github Actions (GHA) and then run them in GKE in GCP. There is some non-deterministic behaviour in those images built (possibly dependent on GHA runner provisioned for us) were some images created are broken and exit with status code 132 Illegal Instruction upon executing `model.predict`. 

We have debugged and found the problem to boil down to a shared object library for the compiled `FastLightFM` class. Using gdb:

```
> /root/.local/share/virtualenvs/app-UJp1QuvJ/lib/python3.8/site-packages/lightfm/lightfm.py(744)predict()
-> def predict(
(Pdb) c

Thread 1 "python" received signal SIGILL, Illegal instruction.
0x00007f79682c796c in ?? () from /root/.local/share/virtualenvs/app-UJp1QuvJ/lib/python3.8/site-packages/lightfm/_lightfm_fast_openmp.cpython-38-x86_64-linux-gnu.so
```
Obviously we cannot go further than this with debugging but we are guessing that there are some CPU instructions the images get built towards. So, we would like to ask if there is any way we can check what flags or options LightFM were built with so that we can compare and troubleshoot the broken and working images. Any assistance would be greatly appreciated 🙏🏽

**Comment by SimonCW** [comment]
Hi, 
if you clone and install via `pip install . -vv` you can see the flags in the end of a line that usually starts with "gcc". For example, mine looks like this
> gcc -pthread -B /home/simon/miniconda3/envs/test2/compiler_compat -Wl,--sysroot=/ -Wsign-compare -DNDEBUG -g -fwrapv -O3 -Wall -Wstrict-prototypes -fPIC -I/home/simon/miniconda3/envs/test2/include/python3.7m -c lightfm/_lightfm_fast_openmp.c -o build/temp.linux-x86_64-3.7/lightfm/_lightfm_fast_openmp.o -ffast-math -march=native -fopenmp

There, you see that `-ffast-math -march=native -fopenmp` were used. In my experience ffast-math is often problematic. You can avoid it by setting an environment variable, i.e.
`export LIGHTFM_NO_CFLAGS=1 && python -m pip install .  -vv`
This is the [relevant line in setup.py](https://github.com/lyst/lightfm/blob/d05289982928f81b957c1f0ff63dcaee0e915f3b/setup.py#L17)

Alternatively, you can install the pre-compiled package from conda-forge where we also compile without ffast-math.

**Comment by parhamfh** [comment]
Thank you so much for the help, @SimonCW, this information will help us debug the problem! 🙌🏽
