### ISSUE TITLE
model.predict() and embedding multiplication gave different results

### ISSUE THREAD

**Issue by viyx** [lyst/lightfm#642]
Hello! 
I get nearly the same results when I use native lighfm.LightFM.predict and embedding multiplication (up to 1e-6). I can't understand why they are different. It affects following ranking functions. 
I read [617](https://github.com/lyst/lightfm/issues/617) and [474](https://github.com/lyst/lightfm/issues/474) but I couldn't find the answer to my question.

```python
import numpy as np
from numpy.testing import assert_allclose
import lightfm
from lightfm.datasets import fetch_movielens


data = fetch_movielens(min_rating=5.0)
model = lightfm.LightFM()
model.fit(interactions=data['train'], epochs=50)


def lfm_dot_product(uid, lfm_model):
    item_biases, item_factors = lfm_model.get_item_representations()
    user_biases, user_factors = lfm_model.get_user_representations()
    scores = user_factors[uid].dot(item_factors.T)
    scores += user_biases[uid]
    scores += item_biases
    return scores

testee_result = lfm_dot_product(0, model)
truth_result = model.predict(0, np.arange(data['train'].shape[1]))

assert testee_result.dtype == truth_result.dtype == np.float32
assert_allclose(testee_result, truth_result, rtol=0, atol=1e-7)
```

We can see almost the same results on output (when atol=1e-6 we pass the test)

```
AssertionError: 
Not equal to tolerance rtol=0, atol=1e-07

Mismatched elements: 1005 / 1682 (59.8%)
Max absolute difference: 1.4305115e-06
Max relative difference: 3.082396e-07
 x: array([5.848966, 3.664918, 3.890586, ..., 2.37985 , 2.37596 , 2.414136],
      dtype=float32)
 y: array([5.848967, 3.664918, 3.890586, ..., 2.37985 , 2.37596 , 2.414137],
      dtype=float32)
```

**Comment by Ganners** [comment]
I'd assume some quirk given how at predict time this calculation is handled in Cython code

https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template#L320-L334

**Comment by viyx** [comment]
I think this is due numpy fast computing libraries. I try numpy dot-product and manual product (similar to https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template#L320-L334) and I get different results too. So the problem is in numpy fast computing. Also I find out that float64 arrays don't have the issue, but it's not the case as we can't change embedding type in lighfm model class.

**Comment by viyx** [comment]
> I'd assume some quirk given how at predict time this calculation is handled in Cython code
> 
> https://github.com/lyst/lightfm/blob/master/lightfm/_lightfm_fast.pyx.template#L320-L334

thank you for the tip

**Comment by Ganners** [comment]
Out of curiosity - why are you concerned by the small floating point precision errors? Is it just a matter of curiosity?

**Comment by viyx** [comment]
because it affects ranking, top@k are different.
`(sum(ranks_from_lighfm != ranks_from_numpy)  /  len(ranks_from_numpy)) `~ 0.01
