### ISSUE TITLE
How do I choose the proper threshold for result of predict？

### ISSUE THREAD

**Issue by Beytab** [lyst/lightfm#647]
Here is the result of predict of our dataset：
```python
predictions = model1.predict(test_user_ids,
                             test_item_ids,
                             user_features=user_features_matrix)

predictions is like array this：array([ -8.672923, -13.849941, -12.703363, ..., -14.409408,  -9.897023,  -11.761951], 
 dtype=float32)
```
Here is the question:
if the prediction is the distance between users and items, if so, how do I choose the proper threshold for result of predict?

**Comment by Michele971** [comment]
Hi @Beytab,
According to LightFM documentation, did you try `top_items = data['item_labels'][np.argsort(-scores)]` ? [source](https://making.lyst.com/lightfm/docs/quickstart.html) 

Now I have a question for you. You said that the prediction score represents a distance. Where did you read this? 

Thanks!
