### ISSUE TITLE
Possible values of `item_alpha`

### ISSUE THREAD

**Issue by josemazo** [lyst/lightfm#96]
Hi!

I'm getting an strange behavior. If I train (`fit`) a model with `item_features` and a L2 penalty on the item features (`item_alpha`) equal to `0.05`, and then obtain all the item predictions for a user, all that predictions have the same value.
Also, if I obtain all the item predictions for another user (with the same model), again all the predictions have the same value, but different from the previous user.

Also, the `auc_score` of that model is `1.0`. :pensive:

**Comment by maciejkula** [comment]
A L2 penalty of 0.05 is extremely strong, probably leading all parameters to be zero. Can you try `1e-05`?

**Comment by josemazo** [comment]
Yep, you are completely right! A million thanks!

**Comment by maciejkula** [comment]
Great, no worries!
